### ISSUE TITLE
事前・各種申請にAPIから接続する方法について

### ISSUE THREAD

**Issue by shugo1107** [moneyforward/expense-api-doc#100]
### 内容
Swaggerを見る限り、APIから経費精算を申請することはできますが、事前・各種申請へのエンドポイントが存在せず、APIからの申請はできないとお見受けします。
これらは実装予定などありますでしょうか？

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@shugo1107 
お問い合わせありがとうございます。
経費精算含め現在は、申請を出すところはAPIで対応できておりません。
（経費明細の登録はできますが）
承認者の指定であったり、事前・各種申請の場合は任意の申請フォームが作成できて構造もなかなか複雑なため、
その辺りがハードルとなっています。

ただ、経費精算だけなどから将来的には対応したいと思っています
