### ISSUE TITLE
仮払集計に含まれる仮払明細リストの取得について

### ISSUE THREAD

**Issue by y-takeda0** [moneyforward/expense-api-doc#101]
### 内容
いつもお世話になっております。

仮払申請において集計に紐づく仮払明細を取得したいのですが、
APIドキュメント上ですと仮払については支払仕訳を返すAPIしか用意されておりません。

仮払申請の集計情報や仮払明細はどのように取得できるかご教示頂けないでしょうか。

以上、宜しくお願い致します。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
別ラインで回答致しますのでこちらはcloseいたします
