### ISSUE TITLE
「事業者全体の経費明細リストを返す」APIについて

### ISSUE THREAD

**Issue by koobex** [moneyforward/expense-api-doc#102]
### 内容
標題のAPIを使用して中間システムに経費明細を取り込む独自システムあるのですが、12/7までは正常動作しており、12/15に実行したところ経費明細データは必ずあるはずなのですが、対象データなしとシステム上に表示され正常に動作しない状態です。開発元に確認したところ、以下の回答がありました。
----------------
APIのエラーにつきまして、applauseでは「事業者に所属する従業員一覧を返す」、「経費科目一覧を返す」、「事業者全体の経費明細リストを返す」の3つのAPIを利用しております。
その中で「事業者に所属する従業員一覧を返す」、「経費科目一覧を返す」の2つのAPIに関しましては返却値のステータスが「200 OK」で問題ございませんが「事業者全体の経費明細リストを返す」に関しましては返却値のステータスが「400 Bad Request」となっており値が空ではなくエラーになっております。
また、返却値が「200 OK」になっているAPIが2つございますのでoffice_idパラメータもお間違いないかと思います。
こちらでの調査に関しましてはLinuxのcurlコマンドというものを利用して返却値とステータスの確認を行っております。
----------------
尚、前回の正常動作時からシステムの改修などは行っておらず、弊社の実行環境は何も変わっていない状況です。何か対象APIの仕様などが変更となったようなことは、ございますでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@koobex 
ご報告ありがとうございます。別途弊社CS担当者とやり取り頂いているかと思いますが、
curlの実コマンドをお送り頂ければより詳しい検証が出来るかと思います。
そちらについては、アクセストークンだったりもあるので、CS経由とやり取りをさせて頂ければと考えております。
よろしくおねがいします。

**Comment by nkuroda** [comment]
@koobex 
頂いたcurlの実コマンドを元に検証しました。

```
kuroda.naoki (黒田 直樹 at 福岡拠点):入力中アイコン:  5分前
❯ curl https://expense.moneyforward.com/api/external/v1/offices/xxxxx/ex_transactions -H "Authorization: Bearer xxxxx"
{"messages":["日付絞り込みのための条件をいずれか指定してください。"]}%
```

上記レスポンスBodyにエラーメッセージがありますが、日付絞り込みに関する条件が何らか入っておりませんと、
エラーになっております。よろしくおねがい致します。

**Comment by koobex** [comment]
早速のご連絡ありがとうございます。
教えていただいた情報を開発元と共有し、確認を依頼します。
また、結果が確認できしだい、ご連絡させていただきます。
以上、宜しくお願い致します。

**Comment by koobex** [comment]
開発元に確認をしたところ、ご回答いただだいた件について問題がないことが確認でしました。
ただ、発生している問題はまだ解決しておらずで、別のAPIについて仕様を確認させていただきたと思いますが
その確認は、このまま、この場で質問をさせていただいてよいのか、別のissueとして登録するのがよいのか、ご指示を願います。
