### ISSUE TITLE
「経費明細に対応する仕訳を返す」APIにつきまして

### ISSUE THREAD

**Issue by koobex** [moneyforward/expense-api-doc#103]
### 内容
「/api/external/v1/offices/{office_id}/ex_transactions/{ex_transaction_id}/ex_journal」というAPIの返却値の中にある「memo」の値が以前までは「#ex_transaction_」+仕訳画面上に表示されている「番号」+画面上に表示されている「メモ」となっておりましたが、現在APIの返却値にございます「memo」を確認したしますと画面上に表示されている「メモ」のみとなっております。弊社のシステムでは仕訳画面上に表示されている「番号」を明細番号としてデータベースに登録する仕様ですが返却値の値が変更になったことはございますでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@koobex 
お問い合わせのけんですが、結論からお伝えしますと以下のリリースに合わせて修正が入っております。
ご迷惑をおかけして申し訳ございません。
以下のリリースのタイトルはクラウド会計・確定申告への連携となっておりますが、実態は内部的に持っている仕訳のデータのメモフィールドについて修正が入っておりました。
https://support.biz.moneyforward.com/expense/news/new-feature/20201208.html

なお、従来と同じように `#ex_transaction_xxx` という値を設定することもメモフォーマットの活用にて可能です。
  以下を設定されますと、それ以後のものについては、以前と同じ値がメモフィールドに設定されます。

![image](https://user-images.githubusercontent.com/1215551/102948395-459ef680-4509-11eb-89d5-c501b027b81e.png)

しかしながら、既に保存されてしまった仕訳データについては有効ではありません。
過去分について修正をご希望でございましたら、データパッチを承りたいと思いますので、
このgithubのURLを付けて、お手数ですが、CSにお問い合わせ頂ければと思います。

よろしくおねがい致します。

**Comment by koobex** [comment]
昨日（12/24）、上記画像のようにフォーマットを変更/保存後、新規に経費精算を行い、対象APIを12/24の日付指定で実行したところ返り値は空でした。日付指定を前日の12/23にすると23日のデータは正常に返ってきました。
経費精算の決裁日がAPI実行日と同じだった場合、同日のデータを取ってこないなどの変更がありましたでしょうか。

**Comment by koobex** [comment]
ご返信いただきました内容で仕訳連携機能に設定し「/api/external/v1/offices/{office_id}/ex_transactions/{ex_transaction_id}/ex_journal」を実行いたしましたところ「memo」に#ex_transaction_xxxという値が返却されることを確認いたしました。
ですが、仕訳連携機能の設定後に申請/承認したデータが「/api/external/v1/offices/{office_id}/ex_transactions」にて取得ができなくなっておりました。
「/api/external/v1/offices/{office_id}/ex_transactions/{ex_transaction_id}/ex_journal」のデータの取得はできました。
2020/12/24に設定をしたところ2020/12/23までのデータは取得ができましたが2020/12/24以降のデータの取得できなくなっております。何か他に必要な設定はございますでしょうか。

**Comment by MurakiSari** [comment]
- 12/8にリリースなので、12/8以降で(実質12/9)実際に設定変更した12/24までのデータパッチ当てる。

**Comment by nkuroda** [comment]
@koobex 
返信おそくなってしまって申し訳ございません。

> ですが、仕訳連携機能の設定後に申請/承認したデータが「/api/external/v1/offices/{office_id}/ex_transactions」にて取得ができなくなっておりました。

こちらの経費明細の取得についてはリリース前後で変更は入っていません。特に必要な設定等もありません。
おそらく、パラメーターによる絞り込み条件が設定されており、それにマッチしないので表示がされていないものと思います（申請がまだ未了など）。よろしくご確認頂ければと思います。

**Comment by koobex** [comment]
指定している条件としては期間のForm Toだけで、やはりプログラムの実行結果は対象データなしの状態です。
開発元からは実際にプログラム側で値を調べるにはデバッグ用のコード追加が必要になり、時間も費用もかかると言われており非常に困っています。

最優先は12月度の締処理を1/12までに行うことで、原因特定やプログラムの改修では到底間に合いませんので、並行して何かしらの手段で12月分の経費明細と仕訳データを提供してもらえれば、手でデータ加工して処理ができないかを試してみたいと考えています。弊社側で両データを抜き出す手段がありましたら、その方法を教えてください。
対象は12/8から1/6までに承認済みとなった経費申請です。
それ以外で、何か弊社から提供する情報がありましたら、ご連絡ください。

弊社としては、APIを使ったプログラムは12/7まで正常に動作しており、APIの呼出し元のプログラムも一切触っておらず
指示のありましたメモフォーマットに「#ex_transaction_${番号}」を追加しても解消しないのは、これ以外にも変更すべきところがあるのではと思っています。

以上、早急に対応、解決をしたいので、再度、ご確認していただきご連絡ください。
宜しくお願い致します。

**Comment by koobex** [comment]
開発元より下記の連絡がありましたので、追加で投稿します。
--------------------------------------------------------------------------------------------------------------
MF社側で、今回仕様変更前の状態にメモ欄をパッチあてをしていただいたかと思いますが、そちらのパッチが失敗しているため、メモ欄の明細番号が取れずに空振りしています。

具体的には、メモは
　　「#ex_transaction_XXXXXXX」　　※XXXXXXX：明細番号
とのかたちになっています。
仕様変更前は、
　　「#ex_transaction_XXXXXXX メモ」　　※XXXXXXX：明細番号
のフォーマットで作成しています。
明細番号と「#ex_transaction」の間は「_」があって、明細番号とメモの間は必ず半角スペースが存在していないといけません。
メモ内容がない場合も「半角スペース」が必要になります。
　　「#ex_transaction_XXXXXXX 」→こうしないといけません。仕様変更前はこのようになっていました。
この半角空白で、「明細番号」と「メモ内容」の判別をしています。
半角空白がないため、「明細番号」の終わりが判別できずに、明細番号が取得できていません。

やはり、MF側に再パッチをしていただかないとうまくいかないと思われます。
このメモ欄には、MFの「明細番号」と「メモ」の2つの情報が入っています。
12/23のデータを見ると、明細番号のみパッチあてされていて、メモがすべて入っていません。
「メモ」も取得項目ですので、このままですと、すべて空白で取り込んでしまいます。

仕様変更前の仕様のとおり、「明細番号」と「メモ」を半角空白でつないでパッチをしていただく必要があります。
「#ex_transaction_XXXXXXX メモ」の形です。
--------------------------------------------------------------------------------------------------------------
とのことです。
現状は上記のようなプログラムの仕様になっていますので、データパッチを上記フォーマットで早急に実施していただけますでしょうか。
恒久的な対応は、12月度の締め処理が完了してから、その方法について教えていただければと思います。

**Comment by koobex** [comment]
データパッチの状況はいかがでしょうか?
状況をご連絡いただけると助かります。

**Comment by MurakiSari** [comment]
@koobex 
横から失礼します🙏
こちら急ぎ確認します。

ただ、メンションをつけてコメントしていただかないと、開発メンバーはこちらのコメントに気づくことができません😭💧
連絡される場合は必ず、＠でメンションをつけていただきますようお願いいたします🙇‍♀️

**Comment by koobex** [comment]
@MurakiSari 
ご連絡ありがとうございます。
次回からメンションを付けて投稿します。
至急ご対応いただきたいので、進捗がございましたらご連絡ください。

**Comment by nkuroda** [comment]
@koobex 
本件ご迷惑をおかけして申し訳ございません。
まずメモが含まれていない件については、メモフォーマットについて 
`ex_transaction_${番号}` を設定してくださいとお伝えしたのですが、メモも必要ということでしたら、以下のように設定すべきでした。
`ex_transaction_${番号} ${メモ}` 
上記についてまず設定をお願いできますでしょうか？
また、データパッチについては改めて、メモテンプレートリリース以後全てのものについて改めて実施させて頂きます。

**Comment by koobex** [comment]
@nkuroda 
メモを追加した設定を行いましたので、メモテンプレートリリース以降全てのものについてデータパッチの実施を至急お願いします。大体、実施作業がいつ完了するかを、ご連絡いただけますでしょうか。

**Comment by nkuroda** [comment]
@koobex 
ご連絡ありがとうございます。
現在準備を進めておりますので、本日の夕方前には遅くとも終わるかと思います。
よろしくおねがい致します。

**Comment by koobex** [comment]
@nkuroda 
ご連絡ありがとうございます。
それでは、ご連絡をお待ちしております。

**Comment by MurakiSari** [comment]
@koobex
たびたびすみません。念のため確認させてください。
今からのデータパッチの修正で、
`#ex_transaction_${番号} ${メモ}`　　(例：`#ex_transaction_83 メモだよん`)
と言うような表記でメモが表示されるようになります。

先ほど、新たに設定していただいたメモのフォーマットだと、
`ex_transaction_${番号} ${メモ}`　(例：`ex_transaction_83 メモだよん`)　←最初に#がない
状態で今後メモが表示されるようになりますが、先頭の#は不要でしょうか？

**Comment by nkuroda** [comment]
あー、私が #抜きを書いてしまっていたのが原因ですね。申し訳ございません。
@koobex お手数ですが、修正お願いできますでしょうか？

**Comment by koobex** [comment]
@nkuroda @MurakiSari 
#を付けて設定し直しましたのでご確認ください。
#ex_transaction_${番号} ${メモ}

**Comment by MurakiSari** [comment]
@koobex 
`#ex_transaction_${番号} ${メモ}`
確認できました！
ありがとうございます！

**Comment by shinpei-noda** [comment]
@koobex このたびはご迷惑をお掛けしました。開発チームの野田と申します。

さきほど明細単位の仕訳データのメモ欄を `#ex_transaction_${番号} ${メモ}` の形式するデータパッチを実行いたしました。ご確認をお願いいたします。

**Comment by koobex** [comment]
@shinpei-noda 
ご連絡ありがとうございます。
確認し、結果は改めてご連絡します。

**Comment by koobex** [comment]
@nkuroda @shinpei-noda @MurakiSari 
弊社側の取込みプログラムで実施しました結果をお伝えします。
MF経費の決裁日が 12/7～12/15分 までを取込みを実施しましたところ、一部の明細が取り込めませんでした。
取り込めない明細は、ある特定の申請者でメモが空欄の明細で、データパッチで${番号}の後ろにスペースを付けなかったのではと思われます。
そこで、下記の明細番号に対して、スペースを付けるデータバッチの実施をお願いします。

申請書番号：
27140
明細番号：13明細
120857
120860
121282
121286
121637
121638
121639
121641
122485
122489
122490
122491
122502

申請書番号：
27142
明細番号：6明細
121284
121285
121288
121289
121635
121640

また、再度、12/16以降のデータでメモが空欄の明細にスペースが付いているか全て確認をお願いします。
もう時間がありませんので至急の対応をお願いします。

**Comment by nkuroda** [comment]
@koobex 
ご連絡の件承知致しました。データ確認をまずは進めます。

**Comment by nkuroda** [comment]
@koobex 
データパッチ作業に入ります。あと20分ほどで完了すると思います。
よろしくおねがいします。

**Comment by nkuroda** [comment]
@koobex 
大変おまたせ致しました。データパッチ完了致しました。
なお、全件チェックを行い、全て `#ex_transaction_xxxx ` のフォーマットになっていることを確認しております。
よろしくおねがい致します。

**Comment by koobex** [comment]
@nkuroda 
ご連絡ありがとうございます。
念のために確認させてください。フォーマットは #ex_transaction_${番号} ${メモ} の形式になっているで間違いないでしょうか。

**Comment by nkuroda** [comment]
@koobex 
はい、`#ex_transaction_${番号} ${メモ}` こちらのフォーマットとなっております。
よろしくおねがい致します。

**Comment by koobex** [comment]
@shinpei-noda @nkuroda 
無事になんとか締め処理が完了しました。色々とありがとうございました。
しかしながら、ユーザとして意見を言わせていただくと、急にAPIの仕様を変更するのは止めていただきたいです。
仕様変更するなら、事前の詳細情報公開とユーザ側が対応する猶予期間がないと本当に困ります。
ユーザからの声として御社内で共有していただきますようお願い致します。

**Comment by nkuroda** [comment]
@koobex 
ご意見につきましては厳粛に受け止めさせていただきます。
チーム内についても共有を致します。
今後このような事がないように再発防止を図ります。
今後ともご愛顧のほどよろしくおねがい致します。
