### ISSUE TITLE
各サービスとAPIに関して（全般的な質問です）

### ISSUE THREAD

**Issue by tomoyo-taskel** [moneyforward/expense-api-doc#106]
### 内容
APIを介して各サービスのユーザー管理をできないかと思っているのですが、以下確認させてください。

１、ユーザー管理系のAPIがあるのは、クラウド経費APIだけなのでしょうか？
２、各システムのユーザーは共通アカウントなどで共通化されていないのでしょうか？その場合ユーザー管理系のAPIがある、クラウド経費以外は、管理者の画面からのユーザー追加や削除が必ず必要になるのでしょうか？

### 開発通知用
@nkuroda

**Comment by tomoyo-taskel** [comment]
@nkuroda お世話になります。こちらご確認のほどいかがでしょうか？

**Comment by nkuroda** [comment]
@tomoyo-taskel 

返信が遅くなりまして大変失礼致しました。

> １、ユーザー管理系のAPIがあるのは、クラウド経費APIだけなのでしょうか？

現状ではおそらくクラウド経費だけですが、今後は他サービスでも出てくると思います。

> ２、各システムのユーザーは共通アカウントなどで共通化されていないのでしょうか？その場合ユーザー管理系のAPIがある、クラウド経費以外は、管理者の画面からのユーザー追加や削除が必ず必要になるのでしょうか？

共通化は進んできている状況です。
クラウド管理コンソール
https://biz-admin.moneyforward.com/session/new

の画面上で、従業員の追加や削除をすることができます。（ここで削除すると各サービスからも抜けるということができます）
また、アカウント統制オプションを利用すると、SAML連携によるSSO連携や、従業員のアカウントの場合はメアド変更や自分でサービスから抜けるというものの抑止が可能などできます。
ただし、こちらに現在外部公開のAPIはない状況です。

**Comment by tomoyo-taskel** [comment]
承知いたしました。ご回答ありがとうございます！
