### ISSUE TITLE
申請リストの対象期間について

### ISSUE THREAD

**Issue by Monsieur999** [moneyforward/expense-api-doc#107]
### 内容
/api/external/v1/offices/{office_id}/ex_reports(事業者全体の申請リストを返す)で、3ヶ月前から現在までのデータした取得できないのではないかと思われます。例えば、昨日(6/27)に実行した際は、4/1からのデータしか取得できませんでした。
特定の期間のデータを取得するにはどうしたら良いでしょうか？
(以前に、API関係でサポートに問い合わせたらこちらに聞けとのことでしたので、ここで質問させていただきます)。

### 開発通知用
@shinpei-noda

**Comment by shinpei-noda** [comment]
@Monsieur999 お問い合わせありがとうございます。

`/api/external/v1/offices/{office_id}/ex_reports` につきましてはご指摘の通り 3 ヶ月前から現在までのデータしか取得できないようになっています。事業者さまによっては大量の申請データが存在するためデータ量を制限するためです。
しかしこの API では日付による絞り込みなどの条件がありません。つきましては恐れ入りますが

- GET /api/external/v1/offices/{office_id}/expense_reports
  - 事業者全体の経費申請リストを返す

<img width="941" alt="スクリーンショット 2021-06-28 15 55 33" src="https://user-images.githubusercontent.com/57242093/123593479-86195d00-d829-11eb-983b-f664e5b05b16.png">

など、パラメータによる絞り込みが可能な別の API の利用をご検討いただけますでしょうか。

**Comment by Monsieur999** [comment]
@shinpei-noda
何はともあれ、現在「3 ヶ月前から現在までのデータしか取得できないようになっています」ということであれば、それをマニュアル/ドキュメントに明記しておいていただきたい。
次に、「大量の申請データが存在するためデータ量を制限するためです」は分かります。しかし、それならば、取得範囲を指定できるようにしてほしいと思います。それができないので、私どもの現在の用途では、一部のデータが欲しい場合でも、全部取得して、それから抽出しています。
最後に、 expense_reports では経費申請しか取得できないのではないでしょうか？(試してみましたがそう見えます)。私どもの現在の用途では、欲しいのは事前・各種申請のリストなのですが、 expense_reports で取得できるのでしょうか？

**Comment by shinpei-noda** [comment]
@Monsieur999 

> 何はともあれ、現在「3 ヶ月前から現在までのデータしか取得できないようになっています」ということであれば、それをマニュアル/ドキュメントに明記しておいていただきたい。
> 次に、「大量の申請データが存在するためデータ量を制限するためです」は分かります。しかし、それならば、取得範囲を指定できるようにしてほしいと思います。それができないので、私どもの現在の用途では、一部のデータが欲しい場合でも、全部取得して、それから抽出しています。

ご意見ありがとうございます。ご指摘の通り (経費申請リストと同様) 取得範囲を指定できるのが理想的な仕様だと思いますので、改善のご要望としてドキュメント改善とともに製品の改善リストに載せておきます。

※ 温度感が高い事項と存じますが、改善リストについては順次対応していく必要があるため「いつまでに対応できます」という明確はお約束はしかねますが、あしからずご了承ください。

> 最後に、 expense_reports では経費申請しか取得できないのではないでしょうか？(試してみましたがそう見えます)。私どもの現在の用途では、欲しいのは事前・各種申請のリストなのですが、 expense_reports で取得できるのでしょうか？

失礼いたしました。こちら経費申請限定ですので事前・各種申請につきましては取得できません。

**Comment by Monsieur999** [comment]
@shinpei-noda
下記、承知いたしました。よろしくお願いいたします。
> ご意見ありがとうございます。ご指摘の通り (経費申請リストと同様) 取得範囲を指定できるのが理想的な仕様だと思いますので、改善のご要望として製品の改善リストに載せておきます。
> 
> ※ 温度感が高い事項と存じますが、改善リストについては順次対応していく必要があるため「いつまでに対応できます」という明確はお約束はしかねますが、あしからずご了承ください。

**Comment by nkuroda** [comment]
@Monsieur999 
cc @shinpei-noda 

> 何はともあれ、現在「3 ヶ月前から現在までのデータしか取得できないようになっています」ということであれば、それをマニュアル/ドキュメントに明記しておいていただきたい。

横から失礼致します。こちら少し背景を補足させていただきますと、 `ex_reports` は経費精算も事前・各種申請も取得できるAPIになっているのですが、経費精算と事前・各種申請でデータの構造がかなり変わってくるため、現在は共通部分のデータしか返せておらず、そのためAPI連携で必要なデータが取得できないという声を頂いております。
そういった経緯もあり、現在は経費精算専用の `expense_reports` APIを作らせて頂いたのですが、今後は事前・各種申請のAPIも別途用意したうえで、 `ex_reports` 自体は一定の廃止猶予期間を置いたうえで、将来は廃止できればと考えております。
そのため、`ex_reports` のAPIについては、取得期間をパラメーターで指定できるなどの対応をストップしているという背景がございます。
よろしくおねがい致します。

**Comment by Monsieur999** [comment]
@nkuroda (@shinpei-noda)

> そのため、`ex_reports` のAPIについては、取得期間をパラメーターで指定できるなどの対応をストップしているという背景がございます。
ご事情は理解しましたが、現状の仕様(何ができて何ができないのか)は明記しておいていただきたく存じます。

> 今後は事前・各種申請のAPIも別途用意したうえで、
新たに API を作成される予定とのことなので、せっかくですので要望をいくつか挙げさせていたきます。
・現行の ex_reports だと、申請に関連するユーザーの詳細情報、例えば、口座情報等まで一緒に返ってきますが、複数の申請に同じデータが付いてきて無駄ですし、また、口座情報等まで返ってくると扱いに困る場合も多く(現在、取得後にわざわざ削除しています)、ユーザーの詳細情報はなしとするか(必要であれば別途取得すれば済むので)、取得する/しないと制御できるようにしてほしい。
・現行、申請IDをキーにしてデータは取得できますが、申請番号をキーにしたAPIはないように思います。申請IDをキーにして(も)取得できるようにしてほしい。

**Comment by koyo-miyamura** [comment]
こちら時間が経過しており当時と状況も大きく変わっておりますので一旦クローズさせていただきたいと思います。
