### ISSUE TITLE
/api/external/v1/offices/{office_id}/ex_transactions での経費明細リストの取得について

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#108]
### 内容
経費明細リストを連携先システムで利用する際に、定期的に一定期間での全件取得を行ておりますが、以前御社から指摘もあり、期間を短縮して取得しております。
しかしながら、毎回期間内の全件取得ＡＰＩを発行しており、ロジック的にも負荷としても無駄なことだと理解しております。
この対策については、その後対応はないのでしょうか？

『仕訳出力済みかどうかでフィルタ』とありますが、この仕訳出力済　というのは、どういう基準になりますか？
出力済をＡＰＩ経由でセットできるのでしょうか？
それであれば、データを取得すれば、フラグをセットし、次回の取得時にパスすることが出来ますね。

### 開発通知用
@shinpei-noda

**Comment by shinpei-noda** [comment]
@skier0922 クラウド経費開発部の野田と申します。この度はお問い合わせありがとうございます。

> 経費明細リストを連携先システムで利用する際に、定期的に一定期間での全件取得を行ておりますが、以前御社から指摘もあり、期間を短縮して取得しております。
> しかしながら、毎回期間内の全件取得ＡＰＩを発行しており、ロジック的にも負荷としても無駄なことだと理解しております。
> この対策については、その後対応はないのでしょうか？

こちら「経費明細一覧取得 API ですでに取得済みの経費明細は再取得しない手段はないか？」という旨の内容と理解しました。齟齬があればご指摘ください。
恐れ入りますが、現在もそのような機能は実装されておりません。しかし何度かお問い合わせ頂いている事項だと存じますので、温度感の高い要望として部内で挙げるように致します。

> 『仕訳出力済みかどうかでフィルタ』とありますが、この仕訳出力済　というのは、どういう基準になりますか？

こちらのパラメータは「仕訳エクスポートという機能で該当の明細をエクスポートしたことがある」場合に「仕訳出力済み」と判断され、そのフラグをもとにフィルタする機能です。そのため、今回のご希望の用途としては利用できないパラメータです。

以上、よろしくお願い致します。

**Comment by skier0922** [comment]
@shinpei-noda 

ご対応ありがとうございます。

番号での取得は、承認済だけを取得したいので、時間差で届いたものが対象外になってしまいます。
明細番号は１か月前に入力したものが届きますので・・・

時間は、タイムスタンプが厄介ですね。ジャストタイムの前後の保証が難しいかと。
結果的には前後の時間差を取って複数回取得せざるを得ないのが厄介かなと思っています。

**Comment by nkuroda** [comment]
@skier0922 
ご要望ありがとうございます。
確認させて頂きたいのですが、こちら現在検索パラメーターにないのですが、経費明細の最終更新時間で絞り込みができれば解決できるのではないかと思っているのですがいかがでしょうか？
データベースのindexの兼ね合いもあるため、最終更新時刻だけでの絞り込みは難しいのですが、最終承認時刻（approved_at_from) などの他の日付での絞り込みとセットであれば、最終更新時刻で絞り込みができるように出来るのではないかと思っています。

**Comment by skier0922** [comment]
@nkuroda 
返事が遅れて申し訳ありません。
APIの仕様がわかってないのですが、前回取得時刻の時分秒ミリ秒の同期って完全に信頼できる時刻で取得可能なのでしょうか？
結果的に前回取得時刻の数秒前、数十秒前から取得する必要がありますよね。

**Comment by nkuroda** [comment]
@skier0922 

> APIの仕様がわかってないのですが、前回取得時刻の時分秒ミリ秒の同期って完全に信頼できる時刻で取得可能なのでしょうか？ 結果的に前回取得時刻の数秒前、数十秒前から取得する必要がありますよね。

現状、APIのリクエストでDBの更新時刻（updated_at）を更新しているということはありませんので、前回のAPIリクエスト時刻からという絞り込みは不要かと思っています（多少重複しても抽出レコードを大幅に絞り込むことが目的だと思いますので）。
例えば、日次でデータを取り込むという場合、
条件: 最終承認時刻が3ヶ月前以降、データ更新時刻が前日の0時0分0秒以降。
といった形で絞り込みすると良いのかなと思います。
今日であれば、 「 approved_at_from >= '2021-04-26 00:00:00' and updated_at_from >= '2021-07-25 00:00:00'」といった形の条件式ですね。こちらでいかがでございましょうか？

**Comment by skier0922** [comment]
@nkuroda 
ありがとうございます。最終承認済を取り込む対象ですので、最終承認時刻が前回取得時の１０分程度のレンジで取り込む仕様で調整をしたいと思います。
３ヶ月とすると、取得するのに、２０分～かかってしまうため、１０分サイクルで取得する場合にＡＰＩの発行回数も多くなりすぎますので、出来るだけＡＰＩの発行を減らすように考えています。
以前、ＡＰＩの発行回数数が多すぎと指摘されたようですので。
データの取得は１日回とかではなく、５分～１０分で取り込みが出来るようにしたいのが本音です。

**Comment by nkuroda** [comment]
@skier0922 
> ありがとうございます。最終承認済を取り込む対象ですので、最終承認時刻が前回取得時の１０分程度のレンジで取り込む仕様で調整をしたいと思います。

承知しました。
最終承認済み後の更新は無い前提に立てば問題ないでしょうし、処理も早くなるかと思います。
一点気になるのは、最終承認済み後に更新がある事を考慮するかどうかで、設定によって最終承認後も編集は可能だったりしますので、その場合は最終承認時刻だけ見ている場合は取得漏れが出るのではないかと思っています。
なので、最終承認済み時刻は月締めなどが完了するまでは、1ヶ月強など広めで取っておき、 AND で`updated_at` の方を10分程度の短いレンジとする案が良いかもしれません。

以上ご検討頂ければと思います。よろしくおねがいします。

**Comment by skier0922** [comment]
@nkuroda 
ありがとうございます。
当社の運用では、最終承認されたデータは、会計システム側で取り込まれてしまい、仮にその後に変更したものは取り込まない（２重計上される）ため、最終承認者のみの判定で問題ないという理解です。

ご指摘ありがとうございました。
