### ISSUE TITLE
オンプレ会計への連携をAPIにて実施するユースケースにて

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#11]
いつもお世話になっております。

GUI上にて整った（経理スタッフが承認した）申請を、自動的にオンプレの会計システムへ連携するユースケースを考えています。

## ご質問
1.本APIは、このユースケースを考慮して設計されていますか?
2.1=yesの場合、どのような流れを想定されているでしょうか?

ちなみに、私が検討しているのは、以下の流れなのですが、

```
まず、

get /api/external/v1/offices/{office_id}/ex_transactions 

ですべてのトランザクションを取り、
それぞれの仕訳を

get /api/external/v1/offices/{office_id}/ex_transactions /{#上でとれたID}/journals

で取得した結果を加工して、
オンプレ会計システムのAPIに渡す
```
ex_transactionsの時にフィルタをかけられないと、
稼働時からのすべてのトランザクションを取得することになってしまいますので、
お互いに負荷が心配な感じです。(以前も似たご質問をしました)

例えば、
https://gyazo.com/1efbd57a7a62875ede9578063118c3d9
こうなっているものを除外するとか、
日付でフィルタをかけてex_transactionsをgetできるならば、
この流れで進められると考えております。

もし、他に想定されている流れがありましたら、教えていただけると大変参考になります。

**Comment by nkuroda** [comment]
@mikomokaru 
ご指摘ありがとうございます。以前ご指摘頂いた件もそうですが、対応が追いついておらずすみません。
参照系のAPIでは、検索・絞込のクエリを受け取れるように諸々改善していく予定です。
（ちょっと大規模開発で工数がAPIに回せずという状況で申し訳ございません）
時期のお約束が難しいのですが、対応完了したら、issue上でご連絡いたします。よろしくお願いします。

**Comment by mikomokaru** [comment]
ご回答ありがとうございます。
ユーザーがそう多くないと思うので、工数が回せない状況は理解できます。

私が気になっている点としては、
API改善スケジュールにかかわらず、もうそろそろ運用を走らせなければいけない、という
状況についてです。
そこで、その段階で、弊社ではどう作ればよいかについて、よろしければアドバイスをいただきたいです。

※想定していたのは、
10-20分ごとに、ex_transactionフル取得のバッチを走らせ、弊社会計のDBをUPSERTする、
というけっこうな荒業で、近々に破綻することは目にみえています。

**Comment by mikomokaru** [comment]
@nkuroda 
ご回答ありがとうございます。
ユーザーがそう多くないと思うので、工数が回せない状況は理解できます。

私が気になっている点としては、
API改善スケジュールにかかわらず、もうそろそろ運用を走らせなければいけない、という
状況についてです。
そこでこの段階において、弊社ではどう作ればよいかについて、よろしければアドバイスをいただきたいです。

※想定していたのは、
10-20分ごとに、ex_transactionフル取得のバッチを走らせ、弊社会計のDBをUPSERTする、
というけっこうな荒業なのですが、近々に破綻しそうなので。

**Comment by nkuroda** [comment]
@mikomokaru 
ご返信が遅れてしまいまして申し訳ございません。
御社側のスケジュール等の都合があること理解はできますし、心苦しいところなのですが、
現在のところは、ウェブでは検索機能と共にCSVエクスポート機能を提供しておりますので、
ひとまずそちらをお使い頂き、我々側の準備が出来たらAPI化されるのが良いのではないかと感じています。

個人的には、いきなりAPI連携の実装を進めるよりも、最初はCSV等で運用を回してからAPI化するのが、ステップとしても良いのではないかと思っている点もあります。

大変申し訳ないのですが、ご理解を頂ければと感じております。
よろしくお願い致します。

**Comment by mikomokaru** [comment]
@nkuroda 
ご対応ありがとうございます。
実は、昨日から
```
/api/external/v1/offices/{office_id}/ex_transactions /{#上でとれたID}/journals
```
が404を返すようになったので、「なんかやってるな」とは思っていました。また、

```
/api/external/v1/offices/{office_id}/ex_transactions 
```
のフィルタは、結構前から使えてましたよね。便利に使わせていたいだいておりました。
総合的に、これで充分実用的に使えると思います。ありがとうございます。

最後にリクエストさせていただきます。
ex_transactionsのgetで、ex_journalsが最初から含まれていてくれるモードなんかがあると、
さらに使いやすいです。
こうしていただけると、現状APIの呼び出しが2段階になっているのが、1発でとれるので。
