### ISSUE TITLE
 /api/external/v2/offices/{office_id}/office_members　APIでは取得できるものと画面からＣＳＶ出力したものとの差異について

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#110]
### 内容

 /api/external/v2/offices/{office_id}/office_members　を使用して、全件取得したデータと、管理画面からＣＳＶ出力した際に、差異が発生します（ＡＰＩのほうが多い）
退職社員をＣＳＶ取込で削除を行っておりますが、削除してもＡＰＩで取得されるデータは残っているようです。
ＡＰＩで取得したデータでＣＳＶで削除をしても、該当社員はいないとエラーになります。

【教えてほしいこと】
　①管理画面ではみれずに、ＡＰＩでの参照が可能なデータがあるのはなぜか？　
　②どのＡＰＩデータをみれば、この判定ができるのか？
　③/api/external/v2/offices/{office_id}/office_members/{id}　これを使うことで完全に削除できるのか？
　　削除できない場合は、どうすればいいのか？
　④ＣＳＶで削除されてしまったものを元に戻すことができるのか？　②の設定を変えればできるのか？
　　ＣＳＶアップロードで　権限＝『権限なし』という設定もあるため、ＣＳＶとＡＰＩの差異が出ないようできる。

　よろしくお願いします。

### 開発通知用

@shinpei-noda @moneyforward/ex-guardian

**Comment by skier0922** [comment]
@nkuroda 

この件、いかがでしょうか？そろそろ１ヶ月経ちますので。

**Comment by shinpei-noda** [comment]
@skier0922 長い間返答をせずに大変申し訳ございません。
(今後このようなことが起きないように、当 GitHub リポジトリでご質問を頂いた場合の弊社開発者への通知を強化いたします。)

> ①管理画面ではみれずに、ＡＰＩでの参照が可能なデータがあるのはなぜか？　

内部的には削除済従業員のデータを持っており (関連データとの紐付け保持のため) 、
API の仕様として削除済従業員も取得するようにしています。
すいません、削除済を含める歴史的な経緯までは私が認識できていないのですが、削除済の従業員情報を利用している事業者様も存在するためこの仕様を保持している状態です。

> ②どのＡＰＩデータをみれば、この判定ができるのか？

is_active という属性が true であれば経費を利用可能な従業員だと判別できます。

![image](https://user-images.githubusercontent.com/57242093/131789859-e41ae6f8-1fe1-47e9-9505-86e8063aa47c.png)

また GET リクエストのパラメータで経費を利用可能な従業員のみに絞り込むことも可能です。

![image](https://user-images.githubusercontent.com/57242093/131789996-14722804-db5f-4012-95a5-179eb51418d1.png)

> 　③/api/external/v2/offices/{office_id}/office_members/{id}　これを使うことで完全に削除できるのか？
　　削除できない場合は、どうすればいいのか？

従業員データを完全に削除することはできません。(2) の方法で経費を利用可能でない従業員を含めないように取得していただくようにお願いします。

> 　④ＣＳＶで削除されてしまったものを元に戻すことができるのか？　②の設定を変えればできるのか？
　　ＣＳＶアップロードで　権限＝『権限なし』という設定もあるため、ＣＳＶとＡＰＩの差異が出ないようできる。

こちらも不可ですので、(2) の方法で CSV と API の差異がでないように API で取得していただければと思います。

**Comment by skier0922** [comment]
@nkuroda 
すいません。回答ありがとうございます。
そのように対応したします。
