### ISSUE TITLE
ex_transaction　についての質問

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#111]
### 内容
/api/external/v1/offices/{office_id}/me/ex_transactions　において、

ex_transactions - ex_report_unit - payment_date 　：支払日

というのがありますが、この値は何がセットされるのでしょうか？
経費登録、伝票登録では入力するためのそのような枠もなく、リターン値もＮＵＬＬが戻ってきているようです。
以前（２年前）はなんらかの値が入っていたようですが（当時のベンダーには確認中です）
他のＭＦ製品向け（債務支払）に仕様変更されていますか？

### 開発通知用

@shinpei-noda @moneyforward/ex-guardian

**Comment by shinpei-noda** [comment]
@skier0922 ご質問ありがとうございます。

集計 (ex_report_unit) の支払日 (payment_date) には、支払依頼を集計したデータである支払集計の支払日が設定されます。

支払依頼や支払集計はクラウド債務支払の機能です。弊社は 2021/01/19 (火) にクラウド債務支払をリリースいたしましたが、それ以前はクラウド経費に支払依頼の機能があり、その名残で残っております。そのため支払依頼申請ではなく経費申請の場合、経費集計は支払日 (payment_date) と関連のないデータですので必ず空 (NULL) が設定されます。

**Comment by shinpei-noda** [comment]
@skier0922 先日の回答内容に誤りがございました。申し訳ございません。
クラウド経費の経費集計に関しても下図の通り支払日を設定することが可能で、API の payment_date にはその日時が設定されます。

![スクリーンショット_2021-08-11_15_51_04](https://user-images.githubusercontent.com/57242093/128982968-30752372-876e-4a6d-95d7-fd9b59d25dbb.png)
