### ISSUE TITLE
認可コードの承認条件

### ISSUE THREAD

**Issue by dv-syouji** [moneyforward/expense-api-doc#112]
### 内容

認可コードの承認状態について質問があります。

認可コードを再生成しようと「認証」ボタンを押すと承認画面をパスしてすぐに新しい認可コードを取れることがありました。
しかし別タイミングで行ったところ、毎回ボタン押下による承認を求められました。10分と空けずにやっても同様です。
この差異はどこにあるのでしょうか？

何か特定の条件が揃えば認可コードの取得をある程度自動化できるのでしょうか？

### 開発通知用

@shinpei-noda @MurakiSari @m-shichida @nisimotoryoga

**Comment by shinpei-noda** [comment]
@dv-syouji お問い合わせありがとうございます。

> 認可コードを再生成しようと「認証」ボタンを押すと承認画面をパスしてすぐに新しい認可コードを取れることがありました。

承認画面が表示される場合とパスされる場合がある理由については現在調査中です 🙇 

なお、認可コードの有効期限は 10 分であり、認可コードの有効期限内にアクセストークンとリフレッシュトークンを取得していただければ、認可コードの再発行は必要ないという想定です。そして、発行したアクセストークンの有効期限は 90 日であり、その間はずっと同じアクセストークンを利用できます。90 日後は対応するリフレッシュトークンでアクセストークンを再発行していただくイメージです。

**Comment by shinpei-noda** [comment]
## 関連 issue

- https://github.com/moneyforward/expense-api-doc/issues/112

**Comment by dv-syouji** [comment]
@shinpei-noda ご回答ありがとうございます。

認可コードの承認について理解しました。
理由なくいきなり承認されるという訳ではないようなので安心しました。

こちらの件に付きましてクローズとさせていただきます。
