### ISSUE TITLE
リフレッシュトークンが無効化する条件について

### ISSUE THREAD

**Issue by dv-syouji** [moneyforward/expense-api-doc#113]
### 内容

リフレッシュトークンが無効化する条件についてご教示ください。

下記の条件以外になにかありますでしょうか？
・管理画面でAPI連携設定の編集画面を出し、「登録」ボタンを押す。
・管理画面でAPI連携設定のアプリケーションIDなどが表示されている画面を出し、「認証」ボタンを押す。
　→承認ボタンが出る時もその時点で無効化されますか？

例えば「特定のURLを引数に関わらずcurlなどでアクセスする」「管理画面の特定の機能をブラウザで開く」などありましたらご教示ください。

### 開発通知用

@shinpei-noda @MurakiSari @m-shichida @nisimotoryoga

**Comment by shinpei-noda** [comment]
@dv-syouji お問い合わせありがとうございます！

前提としてリフレッシュトークンの有効期限はありません。そして無効化される条件は以下のとおりです。

- リフレッシュトークンを使用して新しいアクセストークンとリフレッシュトークンを再発行した場合。この場合旧リフレッシュトークンは無効となります。
- `POST https://expense.moneyforward.com/oauth/revoke` でアクセストークンを無効化した場合、対応するリフレッシュトークンも無効となります。

**Comment by shinpei-noda** [comment]
## 関連 issue

- https://github.com/moneyforward/expense-api-doc/issues/112

**Comment by dv-syouji** [comment]
@shinpei-noda ご回答ありがとうございます。

条件についてご教示ありがとうございます。
無効化条件について承知しました。

リフレッシュトークンによるアクセストークンとリフレッシュトークンの再発行ですが、こちらは実施間隔に制限などはありますか？
例えば毎日再発行しても問題はないでしょうか？

**Comment by shinpei-noda** [comment]
@dv-syouji

> リフレッシュトークンによるアクセストークンとリフレッシュトークンの再発行ですが、こちらは実施間隔に制限などはありますか？

特に再発行の間隔に制限はございません。

> リフレッシュトークンを使用して新しいアクセストークンとリフレッシュトークンを再発行した場合。この場合旧リフレッシュトークンは無効となります。

こちらの点にさえご注意いただければ、毎日再発行しても問題ない想定です。

**Comment by dv-syouji** [comment]
@shinpei-noda

再発行間隔に制限がない点、承知しました。
リフレッシュトークンの再確保も織り込み済みです。

ご回答ありがとうございました。
