### ISSUE TITLE
事前・各種申請 API の 返却内容が0件で原因がわからず困っています

### ISSUE THREAD

**Issue by samiii-xyz** [moneyforward/expense-api-doc#114]
### 内容

こちら（https://expense.moneyforward.com/api/index.html#/ex_transaction_reserve/find_office_ex_transaction_reserves ）を参考に、APIを利用して「事前・各種申請」の一覧取得を試みているのですが、404 NotFound で下記の内容が返却されて困っております。

{
"messages": [
"処理対象のレコードが存在しません"
]
}

MF経費にログインし、経費業務 > 事前・各種申請 を選択した時（https://expense.moneyforward.com/admin_general_reports にアクセスした時）と同じ一覧が返却される認識で利用しておりますが、異なりますでしょうか？
API利用時にトークンを取得したユーザと、ページからアクセスして一覧を表示しているユーザは同一です。

どのようにすれば一覧を取得できるか、お教えいただけると幸いです。

### 開発通知用

@shinpei-noda @MurakiSari @m-shichida @nisimotoryoga

**Comment by shinpei-noda** [comment]
@samiii-xyz issue の起票にてお問い合わせを頂いたにも関わらず反応が遅れ、大変申し訳ございませんでした。

本件、お問い合わせとして承ります。
お急ぎのところ恐縮ですが、調査の完了まで数日お時間を頂けますでしょうか？
遅くとも今週中に回答できればと存じます。よろしくお願いいたします。

**Comment by samiii-xyz** [comment]
現状は、report:write transaction:write のscopeを付与済みです。

**Comment by samiii-xyz** [comment]
試してみたところ、200 okで返却されるようになりましたが、中身がありませんでした。
何が足りていなさそうでしょうか？

{
    "ex_transaction_reserves": [],
    "next": "/api/external/v1/offices/{office_id}/ex_transaction_reserves?office_id={office_id}&page=2",
    "prev": "/api/external/v1/offices/{office_id}/ex_transaction_reserves?office_id={office_id}&page=0"
}

**Comment by samiii-xyz** [comment]
@shinpei-noda 
上記の通りなのですが、何か足りていない権限等ございましたらご教授いただけると助かります。
実行している事業者番号、ユーザーは昨日メールでお送りした通りです。

MF経費にログインし、経費業務 > 事前・各種申請 を選択した時（https://expense.moneyforward.com/admin_general_reports にアクセスした時）は、一覧が表示されます。
こちらの一覧が取得される認識ですが、何が（設定？パラメータ？権限？）不足していそうでしょうか。

**Comment by shinpei-noda** [comment]
> 試してみたところ、200 okで返却されるようになりましたが、中身がありませんでした。
> 何が足りていなさそうでしょうか？

@samiii-xyz なるほど。すいません、本番データの調査を伴いますので数営業日お時間をいただきます。

**Comment by samiii-xyz** [comment]
@shinpei-noda 

なんと、存在しないのですね。
customitem123 などの項目名で良いので、API経由で取得できるようになると有難いです。

現状は取得できないということがわかりましたので、質問終了させていただきます。
詳細に迅速にご対応くださりありがとうございました！

**Comment by shinpei-noda** [comment]
> customitem123 などの項目名で良いので、API経由で取得できるようになると有難いです。

@samiii-xyz ご意見ありがとうございます。すぐに対応できるとお答えはできませんが、ご要望として承ります。

> 現状は取得できないということがわかりましたので、質問終了させていただきます。
> 詳細に迅速にご対応くださりありがとうございました！

こちらこそお問い合わせ頂きありがとうございました。
