### ISSUE TITLE
/api/external/v2/offices/{office_id}/office_membersのAPIの返却値について

### ISSUE THREAD

**Issue by nakanowax** [moneyforward/expense-api-doc#115]
### 内容

以下のAPIより登録されているメンバーのe-mailアドレスを取得したいのですが、返却値に含まれておりません。
こちらは仕様になりますでしょうか。または取得する方法がございますでしょうか。

* [/api/external/v2/offices/{office_id}/office_members](https://expense.moneyforward.com/api/index.html#/office_member/find_office_members_v2)

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@nakanowax 
開発チームの宮村と申します。

> 以下のAPIより登録されているメンバーのe-mailアドレスを取得したいのですが、返却値に含まれておりません。
こちらは仕様になりますでしょうか。

こちら仕様となります。 email 情報をAPIで取得する方法は提供しておりません。

**Comment by nakanowax** [comment]
@koyo-miyamura 
ご回答頂きありがとうございます。承知致しました。
もし追加する予定等ございましたら教えて頂ければと思います。
取り急ぎこちらはクローズさせて頂きます。
