### ISSUE TITLE
債務支払のinvoice_reports内の画像を取得したい

### ISSUE THREAD

**Issue by Matsuhashi-k** [moneyforward/expense-api-doc#117]
### 内容

債務支払のinvoice_reportsのjson内に、
report_form_inputs
というパラメータが存在し、
その中に画像データのurlも含まれているのですが、
債務支払APIの中に支払依頼の画像取得の為のAPIが存在しない為、
画像データの取得が出来ません。

画像取得の方法は何か存在しているでしょうか。

https://payable.moneyforward.com/api/index.html

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@Matsuhashi-k 
開発チームの宮村と申します。

> 画像取得の方法は何か存在しているでしょうか。

現在、画像を外部API経由で取得する方法は提供しておりません。

**Comment by Matsuhashi-k** [comment]
取得出来るように対応してもらうことは可能でしょうか。

**Comment by koyo-miyamura** [comment]
@Matsuhashi-k 

> 取得出来るように対応してもらうことは可能でしょうか。

ご意見ありがとうございます。
開発チームにて要望として承りますが、申し訳ありませんが対応時期のお約束はできません。
ご理解いただければ幸いです。
