### ISSUE TITLE
MF Payable - 「有料プランに未加入のため、ご利用が制限されております」のエラー

### ISSUE THREAD

**Issue by facundito90** [moneyforward/expense-api-doc#118]
**内容**
APIを有効にし、接続を確立し、「/api/external/v1/offices」のPayable APIにはアクセスできますが、それ以外のPayable APIを入力しようとすると、このエラーが発生します：

「有料プランに未加入のため、ご利用が制限されております。ご利用には、マネーフォワード クラウドの有料プランへの加入が必要となります。」

例
/api/external/v1/offices/{office_id}/invoice_transactions
/api/external/v1/offices/{office_id}/invoice_reports

•	契約プランは「コーポレート」ですが、「無料トライアル中」と表示されていますが、これはアクセスを制限しているのでしょうか？ 

**開発通知用**
@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@facundito90 
開発チームの @koyo-miyamura と申します。
問題が発生している office_id をいただいてもよろしいでしょうか？下記メールアドレス宛にお願いします。

ex-guardian@moneyforward.co.jp

**Comment by koyo-miyamura** [comment]
@facundito90 
office_id 送信ありがとうございます。確認いたしました。

一点確認したいことがあります。
`/api/external/v1/offices/{office_id}/invoice_transactions` に入力する office_id ですが、こちらはメールアドレスでいただいた id ではなく、 `/api/external/v1/offices` のレスポンスで返る id を入力する必要があります。
こちらはお間違えでないという認識で問題ないでしょうか？

![image](https://user-images.githubusercontent.com/18478417/142793279-e195addc-a191-4736-86bb-e9d0169fbdc0.png)

**Comment by facundito90** [comment]
@koyo-miyamura 
ご回答ありがとうございました。

価を間違えました。先ほどメールでidを送りました。
まだその問題があるかどうか、DEVチームに確認してみます。

Thanks!

**Comment by koyo-miyamura** [comment]
@facundito90 
承知いたしました。メール確認いたしました。
一旦そちらで試していただき、それでも問題ありましたら、ご連絡いただければと思います:pray:

**Comment by facundito90** [comment]
@koyo-miyamura
お世話になっております。
オフィスIDを間違えていたようです。今は問題なく動作しています。

Thanks!
