### ISSUE TITLE
領収書ファイルをアップロードできない

### ISSUE THREAD

**Issue by MasayasuAoyagi** [moneyforward/expense-api-doc#119]
### 内容
マネーフォワード クラウド経費APIの「領収書をアップロードして経費登録する(/api/external/v1/offices/{office_id}/office_members/{office_member_id}/upload_receipt)」を利用して
領収書をアップロードしたいのですが、アップロード自体は出来るもののWebよりファイルを確認すると
文字化けしたPDFファイルとして添付されております。
こちらファイルの送信方法や送信するファイルのフォーマット等、特別な処理は必要でしょうか？

以下の環境でAPIを使用しております。
【使用言語】 java（Spring boot）
【Webアプリケーションサーバー】AWS-EC2上でTomcat（Jar）を起動
【添付するファイル】Jpegファイル（保管先：AWS-S3）
【アップロードファイルのテキスト生成方法】
1. ResourceLoaderを使用してAWS-S3よりファイル（InputStream）を取得。
2. 上記、ファイル（InputStream）よりreadAllBytesにてバイナリを取得。
3. 取得したバイナリをjava.util.Base64にて文字列に変換。

尚、POSTしているbodyは以下となります。
{"filename":"IMG_0001_4.jpg","content_type":"image/jpeg","process_type":"1","content":<上記で取得したファイルテキスト>}

また、アップロードに使用しましたファイルを添付いたします。
アップロード前の元ファイル：IMG_0001_4.jpg（iPhoneで撮影した画像をWindowsのペイントで30%程に縮小）
アップロードされたファイル：IMG_0001_4_20211118193109.pdf

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga 
[IMG_0001_4_20211118193109.pdf](https://github.com/moneyforward/expense-api-doc/files/7570833/IMG_0001_4_20211118193109.pdf)
![IMG_0001_4](https://user-images.githubusercontent.com/39332673/142638527-2de783ce-6404-4c73-b1d8-96a193e3f05e.jpg)

**Comment by MasayasuAoyagi** [comment]
申し訳ございません。自己解決いたしました。
こちらcontext_typeを取得するためにTikaを使用しているのですが、
TikaInputSteramを取得する際に元のInputStreamを渡しており、これがオブジェクト参照により
InputStreamの中身が変更されていたことが原因でした。

よってこちらはCloseさせていただきます。

**Comment by shinpei-noda** [comment]
@MasayasuAoyagi お問い合わせありがとうございます。解決されたとのことで何よりです。また不明点などあればご連絡ください。
