### ISSUE TITLE
所属事業所取得（offices）で403エラー

### ISSUE THREAD

**Issue by hisano66** [moneyforward/expense-api-doc#12]
事業所一覧を取得するAPIを実行すると、
ステータスコード403（権限エラー）が返されます。
事業所の管理者（オーナー）でAPIアプリケーションを登録し、トークンを取得したのですが、
権限が不足しているのでしょうか？

また、403エラーのレスポンスには、jsonコードでのmessageなどがありませんが
不具合でしょうか？仕様でしょうか？

**Comment by AyakaHARA** [comment]
403ということなので、 scopeが足りていない可能性がございます。
アプリケーションの登録で scope を入れ、かつ 認可処理の際にもscopeの指定が必要です。

https://expense.moneyforward.com/oauth/authorize?client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_URL]&response_type=code&scope=[SCOPE]

上記の [SCOPE] パラメータが指定されているかご確認ください。

**Comment by nkuroda** [comment]
> また、403エラーのレスポンスには、jsonコードでのmessageなどがありませんが
不具合でしょうか？仕様でしょうか？

403エラーのレスポンスについては、bodyで messages が入る場合と入らない場合があります（定義の通り `optional` です）
403エラーが発生する箇所によって異なってまいります。よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/1215551/34975743-9280a1cc-fad6-11e7-844b-6f535b3e9c94.png)

**Comment by hisano66** [comment]
user_setting:write　の scopeを利用し、
事業所IDを取得することができました。

「office_setting:write」が最高位の権限で全てのAPIが実行可能かと思っておりました。
事業所ID取得以外に「office_setting:write」で実行できないAPIはありますでしょうか？
もし、APIの有効な実行権限が記載箇所がありましたらご教示いただきたいです。

もしくは、連携処理などでシステムがAPIを実行する場合は、
scopeの設定で全ての権限をスペース区切りで設定しておくことが望ましいでしょうか？


403エラーのレスポンス仕様については、理解いたしました。
200のステータスの場合のみbodyが返される想定で実装いたします。
