### ISSUE TITLE
APIのレスポンスについて

### ISSUE THREAD

**Issue by mitsuhiro-yamada** [moneyforward/expense-api-doc#121]
### 内容
マネーフォワード クラウド経費のAPI「事業者全体の経費明細リストを返す」APIのURL：/api/external/v1/offices/{office_id}/ex_transactions　を使用してます。
12/3　22:00ころに3分経ってもレスポンスがない事象がありました。
サーバーへのアクセス多かったり負荷が高かったりしたのでしょうか。
原因が何だったのか教えてください。
因みにスケジュール起動で23:00の実行では問題ありませんでした。
よろしくお願いいたします。

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
いつもお世話になっております、マネーフォワードの西本と申します。
この度はご不便をお掛けして申し訳ございません。
お問い合わせにつきましては順次対応させていただきますので、1,2営業日ほどお時間いただけますと幸いです。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
> 12/3　22:00ころに3分経ってもレスポンスがない事象がありました。
> サーバーへのアクセス多かったり負荷が高かったりしたのでしょうか。

この時間帯にWAF(Web Application Firewall)が一時的に不安定であったためかと思われます。

クラウド経費・債務支払のアプリケーション以外の外部要因 (AWS や WAF など) により、リクエストが一時的に失敗する可能性は恒常的に存在します。しかしながら、稼働率が SLA 基準を割った事例はサービス開始時から一度も無いため、本事情のご理解をいただけますと幸いです。

**Comment by mitsuhiro-yamada** [comment]
ご回答ありがとうございます。
因みに10/18 午前7時30分ころはどうでしょうか。
こちらは3分以上のレスポンス遅延やエラーではなく、一連の処理時間が通常13分程度だったのが35分かかった事象になります。
次のスケジュール起動では通常の13分程度の処理時間に戻りました。
よろしくお願いいたします。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
確認にお時間を要してしまい申し訳ございません。

>10/18 午前7時30分ころはどうでしょうか。

以前お問い合わせいただきました、APIでのプロジェクトの登録と表示プロジェクトの更新処理の件でしょうか？

その場合、以前弊社別の担当や辻からお伝えいたしました通り、
サーバー混雑状況による一時的なものであり、改善のためには表示プロジェクトのデータ構造を変更する必要があると認識しております。
こちらの開発案件については優先度上位で認識していますが、現時点で時期のお伝えは難しく、ご迷惑をおかけしており申し訳ございませんが、こちらの開発着手まで今しばらくお待ちいただけますようお願い申し上げます。

**Comment by mitsuhiro-yamada** [comment]
ご返答ありがとうございます。
表示プロジェクトのデータ構造は仕方ない事なのでここで問題にするつもりはなく、月中の午前7時頃にサーバー混雑していることの詳細がわかるのかなと思い問合せさせて頂きました。
過去に「お問い合わせフォーム」のご回答でサーバー設備の強化対応の予定を教えて頂いたので、その対応で溜まった処理消化に時間が掛かったのか、通常運用で発生したのか、を知りたかったです。
通常運用となると月末月初以外に月中も注意監視が必要になるため想定される業務も教えて頂きたいです。
よろしくお願いいたします。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
>月中の午前7時頃にサーバー混雑していることの詳細がわかるのかなと思い問合せさせて頂きました。

以前、弊社辻からもお伝えさせていただいた通りではございますが、
サーバーの混雑状況の詳細までは明確にお答えできかねます。

大変恐縮ですが、こちらの件に関しましては開発側からこれ以上お伝えできません。
以上、ご理解いただけますと幸いです。

**Comment by mitsuhiro-yamada** [comment]
残念ですが分かりました。
また何かあればよろしくお願い致します。
