### ISSUE TITLE
クラウド債務支払APIを利用した、各種申請の取得

### ISSUE THREAD

**Issue by marrond76111** [moneyforward/expense-api-doc#122]
### 内容

クラウド債務支払APIを利用し、事前申請の内容を取得する事を試みております。
こちらのドキュメント（https://payable.moneyforward.com/api/index#/invoice_report/find_office_invoice_reports ）
を見る限り、「支払依頼」を取得するAPIはあるのですが、「事前申請」の内容を取得するAPIが見つかりませんでした。
クラウド債務支払におきまして、事前申請のデータをどの様にして取得したら良いのか、お手数ではございますがご教示願えればと思います。

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@marrond76111 
ご質問ありがとうございます。

恐れ入りますが、クラウド債務支払APIにおいて事前・各種申請の申請内容を公開 API で取得する手段は現在ありません。
対応時期のお約束はできませんが、開発チームに要望を起票させていただきます。
ご理解いただけると幸いです。

**Comment by marrond76111** [comment]
@koyo-miyamura 
ご回答ありがとうございます。本件必要な機能ですので、何卒対応願いたいです。
