### ISSUE TITLE
422エラーについて

### ISSUE THREAD

**Issue by shpmf** [moneyforward/expense-api-doc#123]
### 内容

お問い合わせの内容を箇条書き等で簡潔にご記載ください。

プロジェクトコードの作成
/api/external/v1/offices/{office_id}/project_codes

の処理で、

リモート サーバーがエラーを返しました: (422) Unprocessable Entity

というエラーが出るようになりました。

エラーの原因を調査する方法はありますでしょうか？

ログ等閲覧可能な方法はありましたら教えて下さい。

### 開発通知用

@shinpei-noda @MurakiSari @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@shpmf 

> エラーの原因を調査する方法はありますでしょうか？

422 エラーということはバリデーションエラーが発生しているかと思います。
エラーの内容はレスポンスのjsonに書いてあるので、そちらをご参照ください。

なおAPIの仕様はこちらのドキュメントご参照ください。
https://expense.moneyforward.com/api/index.html#/project_code/create_project_code
