### ISSUE TITLE
事前・各種申請の明細が取得できない

### ISSUE THREAD

**Issue by TSadh** [moneyforward/expense-api-doc#124]
### 内容

/api/external/v1/offices/{office_id}/ex_transaction_reserves
・上記エンドポイントを使用し、事前・各種申請の明細を取得しようと試みた。
・返ってきたのはデータ自体は空の状態で「next」「prev」に値が入ったデータだった。
・クラウド経費上で見ると、申請は1件あり承認もされている。
・絞り込みの条件をいくつか変えてみましたが、データは空のままでした。
・なお経費明細等は取得できている。

データを取得するための方法をご教示いただきたい。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@TSadh 

`/api/external/v1/offices/{office_id}/ex_transaction_reserves`

> クラウド経費上で見ると、申請は1件あり承認もされている。

こちらのAPIですが、事前申請を取得するAPIではなく、事前申請に紐付けた明細を取得するAPIとなります。
例えば以下の設定などで事前申請に経費明細の添付が可能で、こちらを設定後に事前申請に紐付けた明細のことを指しています。

![image](https://user-images.githubusercontent.com/18478417/152716515-8f216df0-c0d9-4e20-9519-a9be0a8bd419.png)

では事前・各種申請はどのように取得可能かという疑問があるかと思いますが下記APIにて可能です。
ただし、この API の結果には経費申請も含まれ、なおかつ事前・各種申請のみを取得する API はございません。

`GET /api/external/v1/offices/{office_id}/ex_reports`

以下の類似issueを参考に記載いたします。

- https://github.com/moneyforward/expense-api-doc/issues/114#issuecomment-941974150

**Comment by koyo-miyamura** [comment]
@TSadh 
以前も同様の質問があったのですが、現在、事前・各種申請の申請内容を公開 API で取得する手段は現在ありません。
事前・各種申請は申請フォームの形式によって項目が可変しますが、API はその情報の取得に未対応という状況です。

- https://github.com/moneyforward/expense-api-doc/issues/114#issuecomment-942257398

**Comment by TSadh** [comment]
@koyo-miyamura 
ご回答いただきありがとうございます。
なんと、取得できないのですね…。
ぜひ今後API実装をご検討いただけますと大変助かります。

引き続き、よろしくお願いいたします。

**Comment by koyo-miyamura** [comment]
@TSadh 
ありがとうございます。
ご要望いただき、API実装の検討中ですので、もし取得が可能になりましたらこちらでご連絡させていただきます。

引き続き、よろしくお願いいたします。

**Comment by shinpei-noda** [comment]
@TSadh 平素よりお世話になります。クラウド経費・債務支払の開発をしております野田と申します。

昨日、クラウド経費の公開 API で申請を返す API に申請フォーム項目のラベルと値の情報が含まれる対応を行いました。
以下の赤枠の部分が今回増えた情報です。

https://expense.moneyforward.com/api/index.html#/ex_report/find_office_ex_reports

<img width="1000" alt="スクリーンショット_2022-02-16_13_18_17" src="https://user-images.githubusercontent.com/57242093/154195460-44637035-52f9-473a-976a-c0b5cd634327.png">

例えば、以下の事前・各種申請の場合

<img width="500" alt="スクリーンショット_2022-02-16_13_24_09" src="https://user-images.githubusercontent.com/57242093/154195910-ac97d4b2-a281-48dc-884c-1598d9f63197.png">

外部 API のレスポンス (JSON) には申請フォーム項目 (申請内容) のラベルと値のペアが以下のように含まれます。

<img width="1000" alt="スクリーンショット_2022-02-16_13_22_41" src="https://user-images.githubusercontent.com/57242093/154195829-f85ef897-471c-4489-a404-e675c8f4611a.png">

**Comment by TSadh** [comment]
@koyo-miyamura 
タイムリーな変更、誠にありがとうございます！
今まさにこちらのアプリ開発中でしたので、早速取得し、活用させていただきます！
お早いご対応ありがとうございました。
引き続き、よろしくお願いいたします。

**Comment by TSadh** [comment]
@koyo-miyamura 
クローズした後の質問となり大変恐縮なのですが、1点ご教示いただけませんでしょうか。

`/api/external/v1/offices/{office_id}/ex_reports`

いただいた上記のエンドポイントにて、申請の一覧を取得したのですが、
過去の「事前・各種申請」のリストが取得できず困っております。
直近の申請は取得できているようなのですが、過去分（範囲指定等できますか？）の取得方法について教えていただけませんでしょうか。

お手数ですが、よろしくお願いいたします。

**Comment by koyo-miyamura** [comment]
@TSadh 
こちらはページングされているのですが、それを利用しても過去分が取得できないということでしょうか？

**Comment by TSadh** [comment]
@koyo-miyamura 
はい、ページングのnextがnullになるまで取得しましたが、取得できた申請は経費申請も合わせて75件でした。
現状少なくとも150件以上の申請が提出されておりますので、半分以下の結果のみとなっております。
なにか条件を指定する必要があるのかと思いドキュメントも確認しましたが、見つけられれずの状況です。

**Comment by koyo-miyamura** [comment]
@TSadh 
調査したところ、 `/api/external/v1/offices/{office_id}/ex_reports` については、2ヶ月前の月の1日から今月末までの申請しか取得できない仕様となっております。これはページングしても同様でした。

ex_reports についてはレスポンスに経費申請と事前各種申請が混在しているため、それぞれを取得できるAPIに分離し今後廃止を検討しているという状況です。

経費申請のみ取得する場合は
`GET /api/external/v1/offices/{office_id}/expense_reports`
により検索条件を指定して検索できます。
今後、事前各種申請のみを返すAPIの作成を検討しておりますが、現状は経費申請のAPIのみという状況です。

ex_reports のAPIについては、今後廃止を検討しているという事情もあり、取得期間をパラメーターで指定できるなどの対応をストップしているという背景があります。
詳細については同様のお問い合わせを過去いただいており、そちらご参照いただけると幸いです。
- https://github.com/moneyforward/expense-api-doc/issues/107#issuecomment-869532437

**Comment by TSadh** [comment]
@koyo-miyamura 
なるほど、そうしますと現時点で事前各種申請の2ヶ月以上前を取得する手立ては無いということでしょうか…？

**Comment by koyo-miyamura** [comment]
@TSadh 
申し訳ありませんが現状は `GET /api/external/v1/offices/{office_id}/me/ex_transactions` など、検索可能でかつ事前申請が紐づくAPIで間接的に取得することは可能ですが、直接的に取得する方法は存在しないかと思います。
