### ISSUE TITLE
Swagger UIの一部が想定しない動作を起こす。

### ISSUE THREAD

**Issue by kuroki-ew** [moneyforward/expense-api-doc#125]
### 内容
API調査のために、Swaggerをいつも利用させて頂いております。

その際、UIの挙動で一部困った挙動が起きているので報告いたします。
https://expense.moneyforward.com/api/index.html#/
「事業者全体の申請リストを返す」APIを試そうとアコーディオンをクリックすると、
「自分の申請リストを返す」APIまで同時に開いてしまい、フォーカスが間違ったAPIに当たってしまいます。

手前の操作ミスでしょうか、どう操作すれば意図通りに開けるでしょう？
### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga

**Comment by koyo-miyamura** [comment]
@kuroki-ew 

ご報告ありがとうございます。
こちら調査したところ、指摘いただいた事象が発生することを確認しました。
修正が必要なため、リリース後に再度報告させていただきますので、お待ちいただけると幸いです。
