### ISSUE TITLE
APIのレスポンスについて

### ISSUE THREAD

**Issue by mitsuhiro-yamada** [moneyforward/expense-api-doc#126]
### 内容

APIのレスポンスについて #121　で以前問い合わせた内容と類似した事象になります。

本日15:45頃に表示プロジェクトの更新処理、一連の処理時間が通常13分程度だったのが30分以上かかった事象になります。
APIのレスポンスについて #121　の問合せ以降、本日まで再発してませんでした。
こちらの原因はわかりますか。
よろしくお願いいたします。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada
いつもお世話になっております、マネーフォワードの西本と申します。
この度はご不便をお掛けして申し訳ございません。

お問い合わせいただいた件に関しましては、
月末でアクセスが集中し、一時的にサーバーが混雑していた状況だったことが影響していると考えられます。

なお、以前からお伝えしております表示プロジェクトのデータ構造改善についてですが、
現在開発着手中ですので、今しばらくお待ちいただけますようお願い申し上げます。

以上、ご確認のほどよろしくお願いいたします。

**Comment by mitsuhiro-yamada** [comment]
ご返答ありがとうございます。
月末に於けるアクセス集中。了解しました。
データ構造改善、ありがとうございます。
今後ともよろしくお願いいたします。
