### ISSUE TITLE
APIのタイムアウトについて

### ISSUE THREAD

**Issue by mitsuhiro-yamada** [moneyforward/expense-api-doc#127]
### 内容
2/28　10:20:38　に「Read timed out」が発生しました。
表示プロジェクトの一覧を更新するAPI　になります。
従業員コード：2014058に対してプロジェクトコード：76001069を非表示にする更新を行おうとし、
約4分程度処理を待機し、エラー「Read timed out」となってます。
（10時16分35秒に更新処理を開始／通常１秒程度で処理されています）
こちらの原因を教えて頂けますか。

因みに次回のスケジュール処理（およそ30分後）で上記更新は成功してます。
よろしくお願いいたします。
### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga

**Comment by mitsuhiro-yamada** [comment]
ご返答ありがとうございます。
今までに経験してない初めてのエラーだったので相当ハードなサーバー負荷だったのでしょうか。
今後も発生しうるとありますがなにか条件などはあるのでしょうか。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
ご返信いただきありがとうございます。
別途チャットサポートにお問い合わせいただいていますCSVインポートがうまくいかなかった件と関連があるかどうか調査の余地がありそうでしたのでこちら調査させていただきます。
2,3営業日調査のお時間をいただけますと幸いです。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
こちらの件ですが、CSVインポート中に外部APIの処理と競合してエラーが出たのではないかと考えられます。
ご迷惑をおかけしまして大変恐縮ですが、外部APIを定期実行されている場合、
同処理のCSVインポートは避けていただけますと幸いです。

以上、ご確認のほど何卒よろしくお願いいたします。

**Comment by mitsuhiro-yamada** [comment]
ご連絡ありがとうございます。
こちらは一時的なことでしょうか。それとも恒久的にエラーになりますか。
よろしくお願いいたします。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
>こちらは一時的なことでしょうか。それとも恒久的にエラーになりますか。

CSVインポート中に外部APIの処理と競合してエラーがでるのは恒久的なものですが、
処理に時間がかかっていることで処理が競合する可能性が高まっているという意味では一時的なものだと考えています。
後者は表示プロジェクトのデータ構造の改善を行うことで一定改善がされると思われます。

データ構造改善につきましてはリリースされ次第改めてご連絡をさせていただければと思いますので、
今しばらくお待ちいただけますようお願い申し上げます。

**Comment by mitsuhiro-yamada** [comment]
ご返答ありがとうございます。
競合エラーは恒久的なもの　とのことですが、以前からでしょうか。
今回特別に処理量が多かったり、意図的に処理時間をずらしたり、などの配慮はしておらず、
テスト期間にわざと競合させたこともありましたがエラーとなったことはありません。

**Comment by nishimoto-ryoga** [comment]
@mitsuhiro-yamada 
こちら確認したところ、表示プロジェクトのデータ構造の改善の一環で約1ヶ月ほど前からこの様な仕様となっております。
以上、ご確認のほどよろしくお願いいたします。

**Comment by mitsuhiro-yamada** [comment]
ご返答ありがとうございます。
競合エラーは恒久的に続き、改善されないことが分かりました。
表示プロジェクトのデータ構造の改善で処理時間が短くなり、エラーとならないことを望みます。
