### ISSUE TITLE
403エラーについて

### ISSUE THREAD

**Issue by kengo-soga** [moneyforward/expense-api-doc#128]
### 内容

APIを初めて操作してみました
”自分が所属する事業者一覧を返す”のAPIで403エラーが発生します。
原因に心当たりがないのですが、どんな原因が考えられますか？

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@kengo-soga 

お問合せありがとうございます。

HTTPステータスコード 403 は「権限エラー」となりますので、作成されたアプリケーションに正しくスコープが付与されているかどうかご確認いただけますと幸いです。
