### ISSUE TITLE
「事業者全体の申請リストを返す」の権限について

### ISSUE THREAD

**Issue by AkitoTsukahara** [moneyforward/expense-api-doc#129]
### 内容

`/api/external/v1/offices/{office_id}/ex_reports`（事業者全体の申請リストを返す）を以下の条件でリクエストすると、403エラーが返ってきます。

- 認証アカウントはクラウド経費の管理アカウント
- スコープは `office_setting:write`

認証アカウント、スコープで不備がありますでしょうか？
検査すべきポイントがありましたら、ご教示お願いいたします。

補足
`/api/external/v1/offices/{office_id}/me/ex_reports`（自分の申請リストを返す）のリクエストは正常に動作しておりますので、実行コードには問題がないだろうと考えております。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@AkitoTsukahara 

お問合せありがとうございます。

GET /api/external/v1/offices/{office_id}/ex_reports（事業者全体の申請リストを返す）は、このリクエストを行う従業員に「管理」権限が付与されることが必要になります。

そのため、権限が適切に設定されているかどうかご確認のほどお願いいたします。

**Comment by AkitoTsukahara** [comment]
@SHinGo-Koba 
ご返信いただきありがとうございます。

> GET /api/external/v1/offices/{office_id}/ex_reports（事業者全体の申請リストを返す）は、このリクエストを行う従業員に「管理」権限が付与されることが必要になります。
そのため、権限が適切に設定されているかどうかご確認のほどお願いいたします。

メンバー設定からご確認させていただきましたが権限は「管理」となっておりました。
他にも確認すべきポイントはございますでしょうか？

参考記事
https://biz.moneyforward.com/support/expense/news/new-feature/separation_of_authority.html

![authority_check](https://user-images.githubusercontent.com/10906919/162710498-40c0c3c2-84f8-4160-b406-37fe2fc4af8b.png)

**Comment by SHinGo-Koba** [comment]
@AkitoTsukahara 

こちら検証環境にて再度動作確認を行ってみたのですが、同条件において 403 が発生する事象を確認することはできませんでした(データを取得したい対象の事業者において、リクエストする従業員の権限が「管理」、スコープ：office_setting:write で 200 を確認)。

お手数をおかけしますが、アプリケーション設定、スコープおよび従業員の権限周りを再度お確かめいただけますと幸いです。

**Comment by AkitoTsukahara** [comment]
@SHinGo-Koba

ご確認いただきましてありがとうございます。

> (データを取得したい対象の事業者において、リクエストする従業員の権限が「管理」、スコープ：office_setting:write で

同じ条件で実行してみましたが、変わらず403となってしまいました。。
例えば、Google App ScriptからAPIリクエストしていることもエラーの原因になることはあり得ますでしょうか？

また、従業員の権限が「管理」ではないアカウントでリクエストした時とエラーメッセージに差異がございました。解決の糸口になるかもしれませんので、ご共有させていただきます。

リクエストする従業員の権限が「管理」の場合
![001](https://user-images.githubusercontent.com/10906919/164166761-484a23f1-c6e1-4408-a2fb-dfd4a2f4c2b0.png)


リクエストする従業員の権限が「管理」ではない場合
<img width="1077" alt="002" src="https://user-images.githubusercontent.com/10906919/164166771-5fb21e85-5649-43ac-a3cd-f9eb34857417.png">

お手数ですが、ご確認いただけますと幸いです。

**Comment by SHinGo-Koba** [comment]
@AkitoTsukahara 

現時点で Google App Script など他サービスでの動作保証はしておりませんので、恐れ入りますがそちらのサポートは致しかねます。

一度 API リファレンスでお試しいただけますと幸いです。

API リファレンスで成功しない場合はお問い合わせくださいませ。
https://expense.moneyforward.com/api/index.html#/ex_report/find_office_ex_reports

改めてにはなりますが、/api/external/v1/offices/{office_id}/ex_reports を実行するには下記が必要です。

* token を作成する従業員の権限が「管理」であること
* scope が下記であること
  * office_setting:write

以上、ご確認のほどよろしくお願いいたします。

**Comment by AkitoTsukahara** [comment]
@SHinGo-Koba

私のscope設定が誤っておりました。修正したところ、無事にAPIからレスポンスを受け取ることができました。
何度もご回答いただきまして、誠にありがとうございました。

**Comment by SHinGo-Koba** [comment]
@AkitoTsukahara 

いえいえ、無事にAPIを利用することができたのであればなによりです。

こちらの issue につきましてはクローズいたします。今後ともよろしくお願いいたします。
