### ISSUE TITLE
外貨設定のAPIが欲しい

### ISSUE THREAD

**Issue by SatoshiMatsuoka** [moneyforward/expense-api-doc#13]
事業所設定の外貨設定をメインバンクの為替データと連動させて自動投入したいと考えています。
APIの新設が出来ないでしょうか？

**Comment by nkuroda** [comment]
@SatoshiMatsuoka 
将来は開発を予定していますが、直近はAPI開発のリソースが確保できていない状況です。
（時期の見通しも現状は難しいです
申し訳ございませんが、お待ち頂ければと思います。よろしくお願いいたします。
