### ISSUE TITLE
[MF債務支払] 追加書類ファイルのダウンロード

### ISSUE THREAD

**Issue by facundito90** [moneyforward/expense-api-doc#130]
### 内容
いつもお世話になっております。
追加書類をAPIでダウンロードする方法はありますか？

このAPIコールはe-Docモジュールを使用しているため、請求書文書にのみ限定されます。
/api/external/v1/offices/{office_id}/e_docs/{e_doc_id}/mf_file

また、/api/external/v1/office/{office_id}/invoice_reports にあるファイルの URLを使ってダウンロードを試みました。しかし、ブラウザではないので、ログインエラーが発生しています。

よろしくお願いします。
Thanks!

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@facundito90 

お問合せありがとうございます。

ご確認いただきましたように現時点でAPI経由による追加書類のダウンロード方法はございません。

お手数をおかけしますが、ブラウザ経由でダウンロードするなど別の方法でのご検討いただけますと幸いです。

何卒よろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
@facundito90 

お問合せありがとうございました。こちらの件につきましてはクローズさせていただきます。

また何かございましたらご連絡いただけますと幸いです。
