### ISSUE TITLE
マネーフォワードクラウド経費のＡＰＩの仕様に関して

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#131]
### 内容
「従業員一覧」の所属部門数を拡張いたしました
https://biz.moneyforward.com/support/expense/news/new-feature/20220208.html

とありますが、これにあわせてＡＰＩも変更されているのでしょうか？
https://expense.moneyforward.com/api/index.html#/office_member/find_office_member_v2

外にも新機能がリリースされておりますが、変更などはありませんでしょうか？

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by skier0922** [comment]
その後、いかがでしょうか？
連携プログラムを改修中なのですが、ＸＭＬのフォーマットが仕様書と実際にＡＰＩたたいて取得した内容が違う部分があり、どっちを信用すればよいか困っています。APIたたくと取得できないものがあるため、仕様で確定したいと思っています。

**Comment by skier0922** [comment]
@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@skier0922 

お問合せありがとうございます。またご返信が遅くなり申し訳ありません。

> 「従業員一覧」の所属部門数を拡張いたしました
https://biz.moneyforward.com/support/expense/news/new-feature/20220208.html
>
> とありますが、これにあわせてＡＰＩも変更されているのでしょうか？

こちらに関してですが、APIに変更はございません。

またご利用可能なAPIにつきましては、すでにご参照いただいております [APIドキュメント](https://expense.moneyforward.com/api/index.html#/) に記載されておりますので、合わせてご確認のほどよろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
こちらクローズいたします。何かご不明点ございましたら再度ご連絡ください。

引き続きよろしくお願いいたします。
