### ISSUE TITLE
Tableauとの連携で発生したエラーについて

### ISSUE THREAD

**Issue by hok20625** [moneyforward/expense-api-doc#132]
### 内容

クラウド経費とtableauを連携させたいのですが、tableau側で以下のエラーが発生しました。
対応方法をお教えください。よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/103727526/164165894-1c1e2a1e-2512-476f-9adb-92478a7ca062.png)

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@hok20625 

お問合せありがとうございます。

現時点におきまして、他サービスとの個別のAPI連携サポートは実施しておりません。

[README](https://github.com/moneyforward/expense-api-doc#readme) と [APIリファレンス](https://expense.moneyforward.com/api/index.html) にAPIの利用方法を記載しておりますのでご確認いただけますと幸いです。

何卒よろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
こちらの issue としてはクローズいたします。

何かご不明点ございましたら、お手数ながら再度ご連絡いただけますと幸いです。
