### ISSUE TITLE
APIが利用できない件について

### ISSUE THREAD

**Issue by mitsuhiro-yamada** [moneyforward/expense-api-doc#133]
### 内容
5/9　本日11:40頃からAPIが利用できない状況が頻発してます。
まったく利用できないのではなくて繰り返し処理の中で数回～数十回利用できません。
規則性も分からない状況です。
何が原因でいつ解消されますか。
よろしくお願いいたします。
### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@mitsuhiro-yamada 

いつもお世話になっております。
お問い合せいただきましてありがとうございます。

お問い合せいただいた件についてお調べしたところ、大型連休明けの月初のためにアクセスが集中し、一時的にサーバーが混雑していたことによる影響が考えられます。

ご確認のほどよろしくお願いいたします。

**Comment by mitsuhiro-yamada** [comment]
ご連絡ありがとうございます。
「一時的にサーバーが混雑」了解しました。
5/9　19時以降は何も発生していない状況です。
