### ISSUE TITLE
httpでのAPIトリガーの呼び出しについて

### ISSUE THREAD

**Issue by HideroJingu** [moneyforward/expense-api-doc#135]
### 内容

表題の件について確認させてください。

MFAPIを使用するにあたりGitHubの情報を基にアクセストークンの発行を行っております。

認証コードつきURLの発行までは行う事ができたのですが、その後の手順を進めることが出来ておりません。

手順では$ curlを使用しアクセストークンの発行を行っておりますが、
こちらの対応としてはhttpリクエストで行いたいことから以下の様なリクエストを投げてみたところ、
「必須パラメーターが不足しています:grant_type」というエラーが返ってきてしまいアクセストークンの発行が出来ない状況です。

リクエスト内容
https://expense.moneyforward.com/oauth/token?client_id=[取得したid]&client_secret=[取得したsecret]&redirect_uri=https://expense.moneyforward.com/api/oauth2-redirect.html&grant_type=authorization_code&code=[認証コード]

こちらどのように対応すればアクセストークンの発行が可能かご教示いただけますでしょうか。

お忙しいところ恐れ入りますが、ご確認の程よろしくお願い致します。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by yucyo** [comment]
@HideroJingu 
外部からコメント失礼します。
Webアプリケーションからtoken発行する際に同様の事象にあったのですが、
[認証コード発行後のtoken発行時](https://github.com/moneyforward/expense-api-doc#%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AE%E7%99%BA%E8%A1%8C
)について、リクエストヘッダを`Content-Type : application/x-www-form-urlencoded`とするように記載がある部分で、`application/json`でセットするとtoken発行リクエスト通りましたので、
(本件も同様に解決するか不明ですが)よろしければ一度試してみてください 🙏 
既知でしたら申し訳ありません。

**Comment by SHinGo-Koba** [comment]
@HideroJingu 

いつもお世話になっております。

こちら内容確認させていただいたのですが、content-type は `application/x-www-form-urlencoded` でリクエストを送れてますでしょうか。

お手数ながら、一度ご確認のほどよろしくお願いいたします。

**Comment by HideroJingu** [comment]
@SHinGo-Koba 

お世話になっております。

送信時の情報を確認したところ、下記の様になっておりましたので、そちらは問題ないかと考えております。
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

お忙しいところ恐れ入りますが、ご確認の程よろしくお願い致します。

**Comment by SHinGo-Koba** [comment]
@HideroJingu 

お世話になっております。

ご回答ありがとうございます。

問題の切り分けというところでお伺いしたいのですが、こちらドキュメントに記載の curl ではアクセストークン発行できますでしょうか。

```
# curl を使用したアクセストークン取得

$ curl -d client_id=[CLIENT_ID] -d client_secret=[CLIENT_SECRET] -d redirect_uri=[REDIRECT_URL] -d grant_type=authorization_code -d code=[認証コード] -X POST https://expense.moneyforward.com/oauth/token
```

上記をまず確認していただきたいのですが、もう一つ気になっていることとしては、作成したURlを見ると redirect_uri の値がエンコードされていないようですので、そのためにリクエストpathが意図しないものになってるのではないかと思いました(`/` などはそのままだとクエリパラメータとして送れません)。

ご確認のほどよろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
本件一度クローズさせていただきます。

またご不明点ありましたら、お問合せください。
