### ISSUE TITLE
申請リスト取得APIで代理申請者を取得できますか？

### ISSUE THREAD

**Issue by kuroki-ew** [moneyforward/expense-api-doc#136]
### 内容
いつもAPIを使わせていただいております。

下記の申請取得APIで質問させてください。
[/api/external/v1/offices/{office_id}/ex_reports](https://expense.moneyforward.com/api/index.html#/operations/ex_report/find_office_ex_reports)
事業者全体の申請リストを返す

代理申請者のも取得したいのですが、APIはご用意はありますでしょうか？
もしくはAPIの組み合わせで解決できましたらご教示いただければ幸いです。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@kuroki-ew 

お問い合わせありがとうございます。

内容確認し改めてご連絡いたしますので、今しばらくお待ちいただけますと幸いです。

引き続きよろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
@kuroki-ew 

いつもお世話になっております。

こちら確認しておりましたが、現時点において代理申請者を取得できるAPIはございません(APIの組み合わせも考えてみましたが、取得できるものはなさそうです)。

ご期待に添えず恐縮ながら、何卒よろしくお願いいたします。

**Comment by kuroki-ew** [comment]
@SHinGo-Koba 
ご連絡いただきありがとうございました。

代理申請者も取得できるようになると助かるのでご検討いただければ幸いです。

**Comment by SHinGo-Koba** [comment]
@kuroki-ew 

貴重なご意見いただきましてありがとうございます。今後の改善要望として検討いたします。

このissueはクローズいたしますが、また何かご不明点ありましたらご連絡ください。

今後ともよろしくお願いいたします。
