### ISSUE TITLE
スクリプトでファイルをダウンロードする

### ISSUE THREAD

**Issue by facundito90** [moneyforward/expense-api-doc#137]
### 内容
Hi Dev Team,

APIがe_docのみに限定されているため、ログインして添付ファイルをダウンロードするスクリプトを作成しようとしています。

どのようにユーザーを認証することができますか？

string url = String.Format(https://payable.moneyforward.com/mf_files/xxxxxxxxxxxxxx); 
                                        HttpWebRequest requestObj = (HttpWebRequest)WebRequest.Create(url);
                                        requestObj.AllowWriteStreamBuffering = true;
                                        requestObj.Method = "Get";
                                        requestObj.ContentType = "application/json";
                                        requestObj.Accept = "application/json";
                                        requestObj.Headers["Authorization"] = "Basic " + Convert.ToBase64String(Encoding.Default.GetBytes(user@domain.com:Password));                                       
                                        var resp = requestObj.GetResponse();
                                        MemoryStream ms = new MemoryStream();
                                        resp.GetResponseStream().CopyTo(ms);
                                        File.WriteAllBytes(@"C:\Folder" + "\\" + "Attachment", ms.ToArray());

Thanks!
Best regards,
Nicolas

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@facundito90 

お問い合せありがとうございます。

内容を確認いたしますので、今しばらくお待ちいただけますと幸いです。

引き続きよろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
@facundito90 

いつもお世話になっております。

こちら内容確認させていただきましたが、大変恐縮ながら、個々のサービスとの連携サポートを行っておりません。
またご認識にありますように、現時点で電帳法書類データ以外に紐づく画像ファイルの取得ができるAPIはご提供しておりません。

ご期待に添えず申し訳ありませんが、何卒よろしくお願いいたします。

**Comment by facundito90** [comment]
@SHinGo-Koba 
いつもお世話になっております。
この機能をウィッシュリストに追加することは可能でしょうか？

Thanks!
Best regards,
Nicolas

**Comment by SHinGo-Koba** [comment]
@facundito90 

いつもお世話になっております。

いただきました「電帳法書類データ以外に紐づく画像ファイルの取得API」に関して、実施可否も含めて機能追加の検討させていただきます。ご連絡いただきありがとうございます。

このissueにつきましてはクローズいたしますが、何かご不明点ございましたら再度ご連絡いただきますようお願いいたします。

引き続きよろしくお願いいたします。
