### ISSUE TITLE
原票->電帳法書類の特定・参照について

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#138]
### 内容
こんにちは、お世話になっております。
電帳法オプションをONにしたばかりの状況で、気づいた|困惑したことがあります。
[/api/external/v1/offices/{office_id}/e_docs](https://expense.moneyforward.com/api/index.html#/operations/e_doc/find_e_docs)
が取得できるようになり、こちらから原票(ex_transactionable_number)を参照することは可能だと思います。

ですが、逆方向、原票から電帳法書類
[/api/external/v1/offices/{office_id}/ex_transactions](https://expense.moneyforward.com/api/index.html#/operations/ex_transaction/find_office_ex_transactions)

を探しに行くのが結構困難であるように感じています。
電帳法書類の検索の容易性を担保するという意味でも、ちょっと弱点になると感じました。
※私の見落としだったらすいません

[/api/external/v1/offices/{office_id}/e_docs](https://expense.moneyforward.com/api/index.html#/operations/e_doc/find_e_docs)
こちらに、原票関係の検索パラメータが用意されていれば良いと思っています。

是非ご検討ください。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@mikomokaru 

お問い合わせありがとうございます。

内容確認いたしました。おっしゃるように電帳法書類から紐づく明細を取得するもののみに留まっております。
いただきましたご要望を参考に、実施可否も含めまして追加機能として検討させていただきます。

このissueとしてはクローズいたしますが、またご不明点ございましたらご連絡ください。

引き続きどうぞよろしくお願いいたします。
