### ISSUE TITLE
従業員POST時のResponseCode500について

### ISSUE THREAD

**Issue by nori5** [moneyforward/expense-api-doc#139]
### 内容

GASでスプシから従業員をPostすると、{"status":500,"error":"Internal Server Error"}が返ってきます。
（GetやPutは成功します）
考えられる原因をご教示いただけると幸いです。
以前のIssue（#51）にもあったParameterがおかしいのでしょうか。
（ただ、古いバージョンかもですが、すでに解決済みとなっているはずだと思うのですが、、）

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@nori5 

お問い合わせありがとうございます。

ご不便をおかけし申し訳ありません。500エラーにつきましては、ご提示されている過去のissueとはまた別の箇所で発生しておりまして、改修を進めて参ります。今しばらくお待ちいただければと思います。

またエラーの発生原因をお調べしたところ、リクエストパラメータのフォーマットが正しく設定されていないことによるものです。

こちらの [swagger](https://expense.moneyforward.com/api/index.html#/office_member/create_office_member_v2) でお試しいただくことが可能ですので、一度ご確認のほどよろしくお願いいたします(swagger上にcurl コマンドも発行されますので、そちらも合わせてご参考ください)。

**Comment by nori5** [comment]
ご回答ありがとうございます。承知しました。

Postはうまくいったのですが、do_not_send_mailをtrueにしてもメールが送付されているようなのですが、
何か原因わかりますでしょうか？
ダミーメールアドレスでテストしているので、実際に送付されていることは確認できていないのですが、
MF経費の操作画面でGASで作成された従業員の「招待状況」をみると「送信済」のステータスになっています。

**Comment by SHinGo-Koba** [comment]
@nori5 

いつもお世話になっております。

まずご報告いただきました500エラーにつきましては、昨日修正対応終了いたしました。
お手数をおかけしますが、ご確認のほどよろしくお願いいたします。

> do_not_send_mailをtrueにしても招待メールが送付されているようなのですが、
何か原因わかりますでしょうか？

こちらについて確認いたしましたが、パラメータ `do_not_send_mail` を `true` として正しくリクエストできている場合には、招待メールは送信されず招待状況としては「未送信」になります。

swaggerでお試しいただけますので、今一度リクエスト内容をご確認いただけますようお願いいたします。

**Comment by SHinGo-Koba** [comment]
このissueとしてはクローズさせていただきます。

その他ご不明点ございましたら、改めてご連絡のほどよろしくお願いいたします。
