### ISSUE TITLE
office_members メンバー更新で役職を変更できない

### ISSUE THREAD

**Issue by hisano66** [moneyforward/expense-api-doc#14]
以下のようなパラメータで、メンバー更新APIを実行したのですが、
名前は変更されるが、役職（position_attributes）が更新されませんでした。
{
"name":"テスト　花子",
"position_attributes":{
"id":"XXXXXXXXXXXXX"
}

役職を更新するには、どのようなパラメータを設定すればよろしいのでしょうか？
また、役職が登録されていない場合に、役職を付与（更新）することができるのでしょうか？

**Comment by nkuroda** [comment]
@hisano66 
ご返信遅くなり申し訳ございません。役職一覧はこちらで取得でき、こちらで、役職のidが取れます。
https://expense.moneyforward.com/api/index.html#!/position/find_positions

その役職のid（position_id)を利用して、以下のようなパラメータを設定して、APIをリクエストすれば良いです。（名前とか部門等も同時に更新できます）

```
{
  "office_member": { 
    "position_attributes": {
      "id": "position_id"
    }
  }
}
```

> また、役職が登録されていない場合に、役職を付与（更新）することができるのでしょうか？

可能です。

以上よろしくお願いいたします。

**Comment by hisano66** [comment]
登録できることを確認いたしました。ありがとうございました。

**Comment by hisano66** [comment]
役職を「なし」に更新することは可能でしょうか？
「なし」とする場合のパラメータの設定方法を教えていただきたいです。

**Comment by nkuroda** [comment]
@hisano66 
こちらreopenされたのは以下の件かと思いますので、closeさせて頂きます。
https://github.com/moneyforward/expense-api-doc/issues/19

よろしくお願いします。
