### ISSUE TITLE
ExReportとワークフロー設定の承認ルートを特定する方法、データについて

### ISSUE THREAD

**Issue by tohru-ike-exwzd** [moneyforward/expense-api-doc#142]
### 内容

下記APIで得られるExReportが、ワークフロー設定のどの承認ルートか特定したいです。
背景としては、承認待ちリストのExReportのうち、特定のワークフローの承認ルートの特定ステップの承認者を除いた承認者一覧を取得したいためです。

> GET
> [/api/external/v1/offices/{office_id}/approving_ex_reports](https://expense.moneyforward.com/api/index.html#/operations/ex_report/find_office_approving_ex_reports)
> 事業者全体の承認待ちリストを返す
> 

1. ExReportが、ワークフロー設定のどの承認ルートかを特定する方法があれば教えてください。
2. また、1についてない場合には、以下をご検討いただけますか？
    2-1. 次の情報をExReportに付与。ワークフロー設定の承認ルートを特定できる情報。
    2-2. ワークフロー設定の承認ルートを取得できるAPIの提供。特に承認ステップの承認グループの情報が必要。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by SHinGo-Koba** [comment]
@tohru-ike-exwzd 

お問い合わせありがとうございます。

内容確認し改めてご連絡させていただきます。

引き続きどうぞよろしくお願いいたします。

**Comment by SHinGo-Koba** [comment]
@tohru-ike-exwzd 

いつもお世話になっております。

内容拝見させていただきましたが、ご指摘のように現状どの承認ルートかを特定するAPIをご提供しておりません。
いただきましたご要望につきましては、実施可否も含めまして追加機能として検討させていただきます。

改めまして貴重なご意見をいただきありがとうございました。
こちらのissueとしてはクローズさせていただきますが、またご不明点などございましたらご連絡のほどよろしくお願いいたします。

今後ともどうぞよろしくお願いいたします。
