### ISSUE TITLE
本番データに影響を与えないサンドボックス環境のようなものはありますか？

### ISSUE THREAD

**Issue by ns-katsura** [moneyforward/expense-api-doc#143]
### 内容

現在本番運用しているのですが、今回APIからプロジェクトを追加・更新するプログラムを作成することになりました。
開発するにあたって本番データに影響を与えたくないのですが、サンドボックスといった環境はありますでしょうか？
それとも追加で契約してテスト事業者を用意するといったかたちになるのでしょうか。
ご確認よろしくお願いします。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by koyo-miyamura** [comment]
@ns-katsura 
お問い合わせありがとうございます。
現状APIの開発用環境は用意しておりませんので、テスト用事業者を用意するという形になります。

ご期待に添えず申し訳ありませんが、何卒よろしくお願いいたします。

**Comment by ns-katsura** [comment]
@koyo-miyamura 
承知いたしました。そのように社内調整いたします。
回答ありがとうございました。
