### ISSUE TITLE
「この申請の変更はできません」について

### ISSUE THREAD

**Issue by matintokyo** [moneyforward/expense-api-doc#145]
### 内容

APIである経費明細の「部門」を更新しようとすると、「この申請の変更はできません。」というレスポンスがきます。
・変更できる経費明細／変更できない経費明細の条件が何かを教えて頂けますか。
・申請ではなく、経費明細の更新なので、「この経費明細の変更はできません。」とした方が分かりやすいと思います。

よろしくお願いいたします。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by nobeyuki** [comment]
@matintokyo 
お問い合わせありがとうございます。
ご連絡が遅くなり、大変申し訳ございません。

今回更新しようとしている明細を web で更新していただき、同様のエラーがでるか確認いただけますでしょうか。
web で更新できたら token 作成したユーザーの権限をご確認いただき、ご対応のほどお願いいたします。
web でも更新できなければ お手数ですがチャットサポートにお問い合わせいただきますようお願いいたします。

> 申請ではなく、経費明細の更新なので、「この経費明細の変更はできません。」とした方が分かりやすいと思います。

貴重なご意見ありがとうございます。今後の改善要望として検討いたします。

何卒よろしくお願いいたします。

**Comment by matintokyo** [comment]
@nobeyuki 
ご返信ありがとうございます。
Swagger UIでテストしておりましたが、
権限の問題ではなく、経費明細のパラメータ（ex_transaction）のjsonフィールドに間違いがあったため、失敗していたようです。SwaggerUIの例に沿ってフィールドを埋めた所、無事更新できました。

お手数をお掛け致しました。

**Comment by matintokyo** [comment]
こちらの使い方の問題だったためクローズします。
