### ISSUE TITLE
仕訳エクスポートで出力した情報とAPIで出力した情報の紐付けについて

### ISSUE THREAD

**Issue by t-hoshin** [moneyforward/expense-api-doc#146]
### 内容

①．「仕訳エクスポート」で出力される情報
②．申請フォームに設置した任意項目の内容
を組み合わせて外部のシステムに連携したいと考えています。

過去Issue等を拝見したところ、①でしか出力されない情報がある一方、
②はAPI利用でしか出力できない（「仕訳エクスポート」からは出力されない）　と理解しました。

その上で、①と②を紐づける方法はありますでしょうか…？
　⇒　①と②で共通する一意キーが双方から出力されれば紐付けられるとは思いますが、そういうキー項目はありますでしょうか？

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by nishimoto-ryoga** [comment]
@t-hoshin 
いつもお世話になっております。
お問い合せいただきましてありがとうございます。

>①と②で共通する一意キーが双方から出力されれば紐付けられるとは思いますが、そういうキー項目はありますでしょうか？

仕訳については ex_journal、申請フォーム項目については report_form_inputs で値を取得いただけます。
こちらは項目を自由に設定できる機能になりますので、API ドキュメントご参照の上、ご希望の値をご活用いただければと思います。
https://expense.moneyforward.com/api/index.html

なお、こちらはパブリックな外部 API の仕様に関する問い合わせ窓口ですので、お客様の設定に基づいた回答は致しかねます。
恐れ入りますが、ご理解いただけますと幸いです。

**Comment by nishimoto-ryoga** [comment]
本件一度クローズさせていただきます。

またご不明点ありましたら、お問合せください。
