### ISSUE TITLE
マネーフォワード クラウド経費APIについてご質問

### ISSUE THREAD

**Issue by JunpeiTakada** [moneyforward/expense-api-doc#148]
### 内容

お世話になります。
今後APIにて経費明細を取得したいと考えております。
そこで、APIについてご質問があります。

【ご質問内容】
①「/api/external/v1/offices/{office_id}/me/ex_transactions」のAPIにて経費明細リストを取得した際に、
　仕訳出力回数はレスポンス時に更新されるのでしょうか。
　また、更新される場合、仕訳出力回数を変更せずに経費明細リストを取得する方法はありますでしょうか。
②例としてインボイス対応などで、今後レスポンス内容に変更が生じることはありますでしょうか。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by nobeyuki** [comment]
@JunpeiTakada 
いつもお世話になっております。

①について
「/api/external/v1/offices/{office_id}/me/ex_transactions」のAPIにて経費明細リストを取得した際、仕訳出力回数は更新されません。

②について
レスポンス内容の変更はなるべく避ける方針であります。
どうしても変更する場合は事前にお知らせを出しますので、そちらをご確認いただければと思います。

**Comment by JunpeiTakada** [comment]
@nobeyuki 
ご回答ありがとうございます。

②について承知いたしました。
①でご質問があります。

【ご質問内容】
2-1. 仕訳出力回数は更新されないとのことですが、
　　仕訳出力回数の更新はどのように更新されるのでしょうか。

2-2. 「/api/external/v1/offices/{office_id}/me/ex_transactions」のパラメータにて
　　「仕訳出力済みかどうかでフィルタ(is_exported)」が存在します。
　　こちらの条件は、どの項目でのフィルタなのでしょうか。

**Comment by nobeyuki** [comment]
本件一度クローズさせていただきます。

またご不明点ありましたら、お問合せください。
