### ISSUE TITLE
従業員氏名の文字数（20文字）制限について

### ISSUE THREAD

**Issue by nori5** [moneyforward/expense-api-doc#149]
MF経費の従業員氏名について２０文字の制限がありますが、増やしていただけないでしょうか？
海外の方でミドルネームあり、しかも長い方だとゆうに２０文字を超えてしまいます。
ご検討いただけると幸いです。

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by koyo-miyamura** [comment]
@nori5 
ご要望いただきありがとうございます。

今後の改善要望として検討させていただきます。

今後ともよろしくお願いいたします。

**Comment by nori5** [comment]
ありがとうございます！
いつ頃、やるやらないなどの検討完了しますでしょうか？

**Comment by koyo-miyamura** [comment]
@nori5 

ご返信ありがとうございます。
対応の有無、また対応時期についてはお約束できるものではないため、心苦しいですがお答えすることができません。
ご理解いただけると幸いです。

今後ともよろしくお願いいたします。

**Comment by koyo-miyamura** [comment]
本件一度クローズさせていただきます。

またご不明点ありましたら、お問合せください。
