### ISSUE TITLE
WebAPIの取得するデータについて

### ISSUE THREAD

**Issue by matsu-nsk** [moneyforward/expense-api-doc#150]
### 内容

お世話になります。
WebAPIの取得するデータについて確認させてください。

クラウド債務支払を画面から更新した場合に、
WebAPIを利用して取得するデータは、即時反映されているものでしょうか？
それとも、5分とか一定時間杉田状態のデータが取得されますでしょうか？

お手数ですが、ご回答お願いいたします。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by koyo-miyamura** [comment]
@matsu-nsk 

ご利用ありがとうございます。

> クラウド債務支払を画面から更新した場合に、
WebAPIを利用して取得するデータは、即時反映されているものでしょうか？
それとも、5分とか一定時間杉田状態のデータが取得されますでしょうか？

こちらは即時反映となります。

今後ともよろしくお願いいたします。

**Comment by matsu-nsk** [comment]
@koyo-miyamura 

ご回答ありがとうございます。

当件、事の発端はWebAPIでデータが取得できなかったであろう
事象が発生しまして、タイミングの問題かとも思ったのですが。

例えば、WebAPI側でデータが取れない場合とかありますでしょうか？
・WebAPI側で処理がひっ迫している
・上記以外のタイミングの問題など

再現できる条件や、今のところ安定してデータが取れていますので、
問題ないかとは思っておりますが、何かあればご教授ください。

**Comment by koyo-miyamura** [comment]
@matsu-nsk 

> 例えば、WebAPI側でデータが取れない場合とかありますでしょうか？
> ・WebAPI側で処理がひっ迫している
> ・上記以外のタイミングの問題など

WebAPI 側でデータ取得できない場合は、基本的に Web の画面側でも反映されてないと思いますので、API側の問題ではなくサーバ負荷が高いなどで処理に時間がかかっているケースが考えられます。

サービスの性質上、上記の現象が発生することはありうるため、ご了承いただけると幸いです。

**Comment by matsu-nsk** [comment]
@koyo-miyamura 

承知しました。
ご回答ありがとうございます。

**Comment by koyo-miyamura** [comment]
ご了承いただきありがとうございます。こちらクローズさせていただきます。

引き続きよろしくお願いいたします。
