### ISSUE TITLE
仕分けエクスポート機能のAPIの仕様について

### ISSUE THREAD

**Issue by kuroki-ew** [moneyforward/expense-api-doc#151]
いつもAPIを利用させていただいています。
マネーフォワード　クラウド経費・債務支払いのAPIについて質問です。

### 内容
クラウド経費・債務支払いのサービス画面から利用できる経理業務>仕訳エクスポート機能で、
（具体的には月と出力履歴を指定して）APIからエクスポートできないか調査しております。

それらしいAPIはいくつか見つかりましたが、
出力履歴オプションに相当するもの見付けられないでおります。
認識としては間違いないでしょうか？

APIで実現する方法があればご教示いただければ幸いです。
### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by nobeyuki** [comment]
@kuroki-ew 
いつもお世話になっております。

出力履歴については、`is_exported`というパラメータでフィルタすることが可能です。

|is_exported の値|出力される明細|
|-|-|
|未指定|すべての明細|
|true|仕訳出力回数が1回以上の明細|
|false|仕訳出力回数が0回の明細|

`is_exported`を使用できるAPIは以下のとおりです。

`/api/external/v1/offices/{office_id}/me/ex_transactions`
`/api/external/v1/offices/{office_id}/ex_transactions`
`/api/external/v1/offices/{office_id}/ex_reports/{ex_report_id}/ex_transactions`
`/api/external/v1/offices/{office_id}/ex_report_units/{ex_report_unit_id}/ex_transactions`
`/api/external/v1/offices/{office_id}/ex_transaction_reserves`

**Comment by kuroki-ew** [comment]
@nobeyuki 
ありがとうございます、見つけられずにおりました。
頂いたAPIリストを調査して要件に見合うか検討させていただきます。
