### ISSUE TITLE
APIの取得状況に関して

### ISSUE THREAD

**Issue by ryota1111** [moneyforward/expense-api-doc#154]
### 内容

最終承認された申請内容をAPIを利用し、別のシステムに内容を取り込んでおります。しかし、ごくまれに取得できない申請分があり、過去質問したところ混雑？具合によって取得できない時があるとの回答をいただきました。
そこで、取得できなかった場合、その申請の内容は時間をおけば再度取得できるものなのでしょうか。
数時間に一度、MF側の申請番号と別のシステムの申請番号を照合し、浮いた申請番号を取り込むといった作業を考えております。
よろしくお願いいたします。

### 開発通知用

@shinpei-noda @koyo-miyamura @nishimoto-ryoga @SHinGo-Koba

**Comment by kuro0993** [comment]
@ryota1111 

お問い合わせありがとうございます。

> そこで、取得できなかった場合、その申請の内容は時間をおけば再度取得できるものなのでしょうか。
数時間に一度、MF側の申請番号と別のシステムの申請番号を照合し、浮いた申請番号を取り込むといった作業を考えております。

取得できなかった原因が混雑によるものであれば、時間をおいていただければ再取得可能です。
その他のエラーケースについては [API リファレンス](https://expense.moneyforward.com/api/index.html#/ex_report)を参考にしていただければ幸いです。

**Comment by kuro0993** [comment]
お問合せありがとうございました。こちらの件につきましてはクローズさせていただきます。

また何かございましたらご連絡いただけますと幸いです。
