### ISSUE TITLE
Office_memberのdefault_dept_idのPOSTについて

### ISSUE THREAD

**Issue by nori5** [moneyforward/expense-api-doc#156]
Office_memberのex_office_member_setting_attributes、default_dept_idがPOSTされません。response内容を確認するとnullになってしまいます
一方で全く同じ内容をPUTするとうまく登録されます（responseもnullにはなってません）。
障害など起こっていないでしょうか？

**Comment by nishimoto-ryoga** [comment]
@nori5 
お問い合わせいただきありがとうございます。
お問い合わせ窓口が変更になりましたので、
恐れ入りますが、下記を参考にメールにてお問い合わせいただくようお願いいたします。
```
# 必ずご確認ください
ご要望や不具合はメールにてご連絡ください。
詳しいお問い合わせ方法については下記サポートサイトをご覧ください。
経費: https://biz.moneyforward.com/support/expense/guide/support/sup01.html
債務支払: https://biz.moneyforward.com/support/payable/guide/support/sup01.html

※ チャットサポートでは対応できかねますので、メールでお問い合わせいただくようお願いいたします。
※ 回答にはお時間いただきますので、あらかじめご了承ください。
```

なお、来週中を目処にこのプロジェクトにおける issue 機能をクローズ予定なので、予めご了承いただけますと幸いです。

**Comment by nori5** [comment]
@nishimoto-ryoga 
ご連絡ありがとうございます。
ご指示いただいたURL先の方法で問い合わせいたします。
