### ISSUE TITLE
経費明細から画像を取得する方法について。

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#16]
https://github.com/moneyforward/expense-api-doc/issues/9
この件と逆に、
今現在、経費明細から画像のURLを引く方法はありますか？

GUIから画像を取得してみたところ、
https://expense.moneyforward.com/transactions/<<なんらかのID>>/mf_file
というURLで取れたのですが、この<<なんらかのID>>はおそらく画像アップロード時に発行されるIDですよね？

アップロード時以外に、このIDを取る方法ありますでしょうか？

**Comment by nkuroda** [comment]
> 今現在、経費明細から画像のURLを引く方法はありますか？

現在ご用意が出来ていないですが、引けた方が良いと思いますので、経費明細のAPIにて画像のidを返そうと思います。
なお、画像自体を返すAPI自体が今はないので、そちらも検討します。

> GUIから画像を取得してみたところ、
> https://expense.moneyforward.com/transactions/<<なんらかのID>>/mf_file
> というURLで取れたのですが、この<<なんらかのID>>はおそらく画像アップロード時に発行されるIDですよね？

上記は、`<<なんらかのID>>` は 経費明細のid `:transaction_id` となります。
mf_fileのidは上述のとおり、経費明細のAPIで返すようにしようと思います。

**Comment by nkuroda** [comment]
@mikomokaru 
本件ですが、その後のご連絡滞っておりました。
以下で経費明細に紐づく画像を取得できます。よろしくおねがいします。
https://expense.moneyforward.com/api/index.html#/mf_file/find_office_ex_transaction_mf_file
