### ISSUE TITLE
事業所全体の経費明細取得APIのソートについて

### ISSUE THREAD

**Issue by hisano66** [moneyforward/expense-api-doc#17]
事業所全体の経費明細を取得するAPIですが、
GET /api/external/v1/offices/{office_id}/ex_transactions/{id}
どのような順番で取得されますか？
（経費明細IDの順番でしょうか？）

期間の絞込みパラメータがないので、明細No.の降順などの順番で最新の明細を順に取得できれば、
NEXTページの読み込みを減らすことができ、処理を軽減させられるのではないかという考えがあります。

**Comment by nkuroda** [comment]
@hisano66 
現在の順番については、 `日付降順`(ただし日付が空の場合は優先) > `番号降順`　で返しています。

> 期間の絞込みパラメータがないので、明細No.の降順などの順番で最新の明細を順に取得できれば、

期間の絞込やソートキーをパラメータで受け取れるように出来るだけ早く回収予定です。

**Comment by hisano66** [comment]
ご回答ありがとうございます。

日付降順は、明細作成日　（created_at）の降順
番号降順は、明細番号（number）の降順
　という認識でよろしいでしょうか。

**Comment by nkuroda** [comment]
@hisano66 
情報不足しておりまして失礼致しました。
日付降順は、支払日（recognized_at）の降順
番号降順は、明細番号（number）の降順
でございます。よろしくお願いします。
