### ISSUE TITLE
office_members 所属の表示順

### ISSUE THREAD

**Issue by hisano66** [moneyforward/expense-api-doc#18]
メンバー情報の参照、更新処理で所属の項目ですが、
表示順を取得すること、
登録更新処理で表示順を指定すること　
は、可能でしょうか？

disp_order というレスポンスが仕様書にはありますが、
実際のレスポンスデータで確認できませんでした。

**Comment by nkuroda** [comment]
@hisano66 
こちらですが確認ですが、所属というのは部門の事でよろしいでしょうか？
今回のお問い合わせですが、おそらく、メンバーの第一所属部門、第二所属部門、第三所属部門といった第n所属部門の`n` が欲しいということだと思いますが、部門レコード自体の `disp_order` は事業所に属する部門の表示優先順となり、該当の`n` にあたるものではありません。
（なお、部門レコード自体の `disp_order` はシステムで保有しているものの、現在はAPIで返していないため（キーの修正予定もあるため）、ドキュメントを修正しておきます。）

また、現在システム上では、`n` に対する値は現在もっていない状態で、APIで返すことは予定していません。なお、登録、更新処理では、現状は、配列で渡す際の順番により、第n部門が洗い替えされるようになっています。 具体的には、

```
{
    "depts_attributes": [
    {
      "id": "dept1_id"
    },
    {
      "id": "dept2_id"
    },
    {
      "id": "dept3_id"
    },
　]
}
```

と渡せば、 そのメンバーの 第1部門は dept1, 第2部門はdept2、第3部門はdept3 となります。

**Comment by nkuroda** [comment]
一点修正します。部門レコード自体の disp_orderはapiのレスポンスでも返すように致します。

**Comment by nkuroda** [comment]
> 一点修正します。部門レコード自体の disp_orderはapiのレスポンスでも返すように致します。

こちらの修正リリースは完了しています。
