### ISSUE TITLE
office_member 役職なしに更新する方法

### ISSUE THREAD

**Issue by hisano66** [moneyforward/expense-api-doc#19]
office_memberの更新APIで、役職 （position_attributes）をなしに更新することは可能でしょうか。
可能な場合、パラメータのセットの仕方をご教示いただきたいです。

**Comment by nkuroda** [comment]
@hisano66 
確認したところ現在のAPIではできないようになっておりましたので、修正を行います。
今日明日にでも修正しますので完了しましたらご連絡します。

仕様としては、以下の、`position_attributes` のところを、`id` を `null`　でリクエストが来れば、
役職をクリア致します。 

```
{
  "office_member": {
  "name": "string",
  "number": "string",
  "permission_role_id": "string",
  "depts_attributes": [
    {
      "id": "string"
    }
  ],
  "position_attributes": {
    "id": null
  }
}
}
```

**Comment by hisano66** [comment]
修正していただけるということで承知いたしました。
ご対応の程、よろしくお願いいたします。

**Comment by nkuroda** [comment]
@hisano66 こちら修正完了致しました。お試し頂けますでしょうか？よろしくお願い致します。
