### ISSUE TITLE
APIの試し打ちについて

### ISSUE THREAD

**Issue by chira-okumura** [moneyforward/expense-api-doc#2]
お世話になります。

下記のURLに「APIの試し打ちについてはテストサイトで可能となっていますのでご利用の際は下記よりご連絡ください。」とありましたのでお問合せさせて頂きました。
https://expense.moneyforward.com/api/index.html#/

どのようにしたらよろしいでしょうか。
よろしくお願い致します。

**Comment by nkuroda** [comment]
@chira-okumura 
お問い合わせ頂きありがとうございます。
MFクラウド経費のAPIですが、本番環境でもMFクラウド経費利用開始から30日間のトライアル期間中は、テスト利用して頂くことが可能です。以下のREADMEの通りお試し頂けますでしょうか？
https://github.com/moneyforward/expense-api-doc

上記のAPIの試し打ちの記載については、現状本番環境でテスト利用して頂けているので、古い記載となっているため記載の削除を行っておきます。
何か不明点ありましたが、こちらのissueにてご連絡ください。

**Comment by chira-okumura** [comment]
@nkuroda 
ご回答頂きありがとうございます。
早速READMEの通り試しました。

ご質問ですが、
https://expense.moneyforward.com/api/index.html#!/office/find_offices
上記の事業所「自分が所属する事業所一覧を返す」についてはcurlにて取得が行えましたが、その他、経費明細リスト取得、申請リスト取得等は全て「{"messages":["処理対象のレコードが存在しません"]}」とレスポンスが返ります。
テスト用のデータなどはMFクラウド経費の方に登録しましたが、どういったことが原因として考えられますでしょうか。

何か注意すべき点などございましたらお教え頂ければ幸いです。

**Comment by nkuroda** [comment]
@chira-okumura おそらくですが、 経費明細リストですと、
`GET /api/external/v1/offices/{office_id}/me/ex_transactions` となりますが、`office_id` の指定がされていない or 不一致なのではと思います。`自分が所属する事業所一覧` で取得した `office_id` を指定してお試し頂けますでしょうか？
