### ISSUE TITLE
事業所全体の経費明細

### ISSUE THREAD

**Issue by ishikawa-r** [moneyforward/expense-api-doc#20]
いつもありがとうございます。
質問です。

・/api/external/v1/offices/{office_id}/ex_transactions/{id}
事業所全体の経費明細を返す
を利用する想定ですが、返される項目がいただいたガイドでは出て来ないように見えます。
こちらの項目について、提供ましていただくことはできますでしょうか。
または、サンプルデータ等でも構いません。

恐れ入りますが、ご提供いただけますと助かります。
よろしくお願いいたします。

**Comment by nkuroda** [comment]
@ishikawa-r 
APIのご検討ありがとうございます。
レスポンスについてもAPIドキュメントサイト上に表示しておりますので、ご確認くださいませ。
https://expense.moneyforward.com/api/index.html#!/ex_transaction/find_office_ex_transactions

![image](https://user-images.githubusercontent.com/1215551/37439652-61b5568a-283c-11e8-8976-4395d8b56637.png)

![image](https://user-images.githubusercontent.com/1215551/37439671-79a549d0-283c-11e8-971f-cdfb46ac10e6.png)

**Comment by ishikawa-r** [comment]
担当者さま
ありがとうございます。
資料を確認しておりまして、改めて#21で質問をあげました。
恐れ入りますが、よろしくお願いします。

//bex業務システム部 石川
