### ISSUE TITLE
仕訳系APIについて

### ISSUE THREAD

**Issue by t-sueyoshi** [moneyforward/expense-api-doc#23]
ホームページ等で情報が探せなかったので質問です。

以前のドキュメントでは仕訳(/journals)APIが提供されていたと思いますが、
現在 https://expense.moneyforward.com/api/index.html に載っていません。

廃止となったのでしょうか。

**Comment by nkuroda** [comment]
@t-sueyoshi 
ご返信遅くなりまして失礼致しました。
仕訳APIについては、一旦落とさせて頂いているのですが、現在修正をしており、再度ご提供予定です。
よろしくお願い致します。

**Comment by t-sueyoshi** [comment]
@nkuroda かしこまりました。
再リリースされた際はお知らせいただけると助かります。
よろしくお願いします。

**Comment by nkuroda** [comment]
@t-sueyoshi 
大変遅くなってすみません。
仕訳のAPIについてリリースを行っております。
ご確認ください！
https://support.biz.moneyforward.com/expense/news/new-feature/journal_api.html
