### ISSUE TITLE
office_member（事業所メンバー）の追加

### ISSUE THREAD

**Issue by kuwazzy** [moneyforward/expense-api-doc#24]
メンバーの追加のPOSTメソッドで下記のエラーレスポンスが発生します。
　ステータスコード：422:Unprocessable Entity
　レスポンスボディー　{ "messages": ["メールアドレスを入力してください。"]}
リクエストボディーには下記のとおり、emailを含めています。
{
  "email": "***@***.com",
  "name": "test",
  "number": "1",
  "permission_role_id": 201
}

また、emailが必須項目の場合、事業所に所属するメンバー一覧を返すGETメソッドのレスポンスにもemailを含めていただけると幸いです。

**Comment by nkuroda** [comment]
@kuwazzy 
リクエストボディーのフォーマットが違うようです。
`office_member` キーの中にそれらのパラメータを入れてください。


```
{
  "office_member": {
     "email": "***@***.com"
   }
} 
```

**Comment by kuwazzy** [comment]
ご返信ありがとうございます。更新できました。

**Comment by kuwazzy** [comment]
こちらはリクエストとなりますが、事業所に所属するメンバー一覧を返すGETメソッドのレスポンスにもemailを含めていただけると幸いです。別Issueでリクエストした方が宜しければ仰ってください。

**Comment by kuwazzy** [comment]
@nkuroda 
ご返信ありがとうございます。レスポンスに含まれない理由について理解いたしました。
