### ISSUE TITLE
RedirectURL先のHTTP対応

### ISSUE THREAD

**Issue by kuwazzy** [moneyforward/expense-api-doc#25]
弊社で開発しているデスクトップアプリケーションからOAuthの認証プロセスを実行しようとすると、WindowsマシンでデフォルトブラウザがChromeだと問題なくAccessTokenが取得出来るのですが、EdgeとIE11だと、RedirectURLに飛ばない事象が発生しています。この現象は、RedirectURLが「 https://localhost:33333 」など証明書エラーが発生するHTTPSの場合のみ発生しています。

Edgeの信頼済みサイトはIEの信頼済みサイトを読み込んでいるらしいのですが、IEの信頼済みサイトにRedirectURLの「 https://localhost 」を追加しても変わりませんでした。
https://answers.microsoft.com/en-us/edge/forum/edge_other-edge_win10/how-to-add-certificate-exceptions-in-edge-browser/19726853-d730-4957-abd9-220a70c082c0

現在、MF経費のAPI仕様書を確認すると、RedirectURLはHTTPSのみと限定しておりおらずHTTPもご利用できますが、現時点での今後の方針として、HTTPSのみに限定する変更を入れる予定はございませんでしょうか？なお、MF請求書はHTTPSのみの仕様となっているようでしたので気にしております。

**Comment by nkuroda** [comment]
@kuwazzy 
お問い合わせありがとうございます。
MFクラウド経費もMFクラウド請求書とおなじく、redirect_url はhttpsのみに限定しておりました。。
ドキュメントの方、アップデートを行わせていただきます。
よろしくお願いいたします

**Comment by kuwazzy** [comment]
明確にして頂きありがとうございます。
