### ISSUE TITLE
statelessな環境(ex.aws lambda)からのAPI利用について

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#3]
一般的な話題かもしれませんが…

awsからの利用を想定しています。
s3に画像がアップされたことをトリガーに動作するlambdaを使って
POST /api/external/v1/offices/{office_id}/office_members/{office_member_id}/upload_receipt
を行おうともくろんでおります。

lambdaは基本statelessですが、MFのAPI利用に関しては、認証周り、tokenやrefresh_tokenの状態保持が要求されるかと思います。
とはいえ、できれば楽したいので、statelessに書かせてもらうわけには行かないでしょうか？
というご質問です。

つまり：
- tokenやrefresh_tokenを保持せずに、最初に得たcodeから毎回tokenを生成する

というフローです。
この方式、サービス提供側として、いかがでしょうか？
1. 別に構わない
2. 辞めてほしい
3. 正常に動作しない(※やってみてないので未確認)

以上のどれかに当てはまるのではないかと思いますが、ご見解をおきかせいただけるとありがたいです。

**Comment by mikomokaru** [comment]
上記に関して、
自分の持っている知識の範囲ではありますがさらに調査したところ、
こういう場合cognito+OpenId Connectでスマートに解決可能ではないか？という望みを持っています。

で、cognitoにおいて、OpenIDプロバイダは、
ex. https://moneyforward.com/.well-known/openid-configuration
というURLにてメタ情報を提供することを要求されているようなのですが、
現在上記URLはHTTP 500が返ります。

この現状は、過渡的なものでしょうか？

**Comment by nkuroda** [comment]
@mikomokaru 
ご質問ありがとうございます。
oAuth2の認可フローを全てAWS lambdaでやりきるのはなかなか大変かなと思いますので、今回の件で一番簡単なのは、application_id, secret, refresh_tokenをAWS lambdaの環境変数に保持しておき、毎回、最新のaccess_tokenを取得しなおしてから、取得した`access_token` を Authorization Headerにセットして、
`POST /api/external/v1/offices/{office_id}/office_members/{office_member_id}/upload_receipt`
のリクエストを行うことだと思います。
そして、access_tokenは使い捨て(次のaccess_tokenが取れなくなるのでrevokeはしない）。新しく取得したrefresh_tokenは環境変数に書き戻しておくと良さそうだなと。　

なお、OpenID Connectについては、現在様々な認証基盤と連携するために、開発を進めておりますが、いずれにせよOAuth2の認可フローでは、Authorization Codeを取得するために、認可画面が挟まったりしますので(メアド PWを入力する認証を省略するくらいにはなりますが）、それほど変わらないのではと思います。

**Comment by mikomokaru** [comment]
ご回答ありがとうございます。
環境変数を使った場合、私の認識ですと、lambdaが多重起動した場合破綻しそう(コンテナによって値が違う状況になる)な気がしましたので、AWSへの問い合わせの結果、この場合
http://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html
これを使えば良いことが分かりました。まあ、似たようなものですね。。

OpenID Connectの件、承知しました。今回はパラメータストアを使う方針で進めてみます。
