### ISSUE TITLE
部門(depts)の部門名称(name)の更新が出来ない

### ISSUE THREAD

**Issue by kuwazzy** [moneyforward/expense-api-doc#31]
### 内容

部門(depts)の部門名称(name)と表示フラグ(is_active)の更新が出来ないようです。下記のリクエストボディーでは、memoとdesp_orderは更新されます。お手数ですが、ご確認と誤りがあればご指摘頂けますでしょうか。

{
  "name": "name_test",
  "memo": "memo_test",
  "disp_order": 1,
  "is_active": false
}

なお、下記のように"is_active"だと、400BadRequestで"param is missing or the value is empty: dept"エラーが発生します。

{
  "is_active": false
}

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@kuwazzy 
ご報告ありがとうございます。こちらバグでしたので先程修正リリースを致しました。
再度ご確認頂けましたらと思います。
よろしくおねがいします。この度はご報告ありがとうございまいした。

**Comment by kuwazzy** [comment]
@nkuroda 早速のご返信およびご対応ありがとうございます。部門名称は更新出来るようになりましたが、表示フラグ(is_active)については、"param is missing or the value is empty"エラーが出るようです。UIからは更新出来ることは確認していますので、PUT時にofficeidとidの他に何かパラメータが必要でしょうか？

**Comment by nkuroda** [comment]
@kuwazzy 
こちらですが、POST/PUTで送信するbodyのパラメータですが、"dept" キーを外殻にして、
以下のフォーマットで送っていただくとどうでしょうか。よろしくお願いします。

```
{
  "dept": {
     "is_active": false
   }
}
```

**Comment by kuwazzy** [comment]
@nkuroda 

ご返信ありがとうございます。deptを外殻につけるとtrueからfalseは一回のリクエストで変更出来るのですが、falseからtrueは、1回では変更出来ず、不思議なことにもう一回リクエストを発行すると変更出来ました。

なお、複数項目を更新する場合もdeptを外殻につける下記の形式で宜しいでしょうか？本方式で表示フラグ(is_active)以外は更新出来るようです。

{
  "dept": {
     "memo": "11",
     "name": "21",
     "is_active": true
   }
}

**Comment by nkuroda** [comment]
@kuwazzy 

> なお、複数項目を更新する場合もdeptを外殻につける下記の形式で宜しいでしょうか？

そうなりますね。
なるほど、外殻ついていない場合も、フレームワークがschemaに則ってある程度は補完をしてくれるようですね。。ただ  `is_active` は実はカラムとしては存在しておらず、別のテーブルを結合した結果を付けている状態で、そこまではフレームワークの補完は及ばないのが原因のようです。

> deptを外殻につけるとtrueからfalseは一回のリクエストで変更出来るのですが、falseからtrueは、1回では変更出来ず、不思議なことにもう一回リクエストを発行すると変更出来ました。

ちょっと、こちらは解せないですね。。手元でやった結果を貼り付けますが、問題なさそうな気がしているのですが。。。

**Comment by nkuroda** [comment]
`is_active` パラメータが `true` のパターン


## PUT /api/external/v1/offices/:office_id/depts/:id
Should eq 200.

### Example

#### Request
```
PUT /api/external/v1/offices/oxeX-TmXQCLHcuUt02dTww/depts/oxeX-TmXQCLHcuUt02dTww HTTP/1.1
Accept: application/json
Content-Length: 125
Content-Type: application/json
Host: www.example.com

{
  "dept": {
    "name": "部門名更新",
    "code": "dept_code_更新",
    "disp_order": 20000,
    "memo": "部門メモ更新",
    "is_active": true
  }
}
```

#### Response
```
HTTP/1.1 200
Cache-Control: max-age=0, private, must-revalidate
Content-Length: 198
Content-Type: application/json; charset=utf-8
ETag: W/"a190728fd5c6f9cfde98e3562703a532"
Set-Cookie: _ex_session=Ym5ZOU52WkdjWWp6bTFKZkhjdFdWa0ZNc0h0UGFtQnBBUWU5UGpNVUhNL3pwZGZkSmhkL215ZnZzY1VQaFZDUWJMNVhsZWVJVkFYSHBXS0pqajd6TEJtZkN0SlByM3hUV25hbkkyZlNiV2ZyYTRwUm44bi9nSktyT3phekk1NURrdm1pYnZjUjlqRUhXVXErZE1RaStRPT0tLUdDb3lhNlVvakNDbWFVL1piQ2Z2Znc9PQ%3D%3D--5c8e2092beea1c5fd0e97173a214883994d4b8d9; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 3deb50e1-d4b0-4c85-92c2-f532f66d15ab
X-Runtime: 0.734868
X-XSS-Protection: 1; mode=block

{
  "id": "oxeX-TmXQCLHcuUt02dTww",
  "memo": "部門メモ更新",
  "code": "dept_code_更新",
  "disp_order": 20000,
  "is_active": true,
  "name": "部門名更新",
  "parent_id": null,
  "root_id": "oxeX-TmXQCLHcuUt02dTww"
}
```

`is_active` パラメータが `false` のパターン

## PUT /api/external/v1/offices/:office_id/depts/:id
Should eq 200.

### Example

#### Request
```
PUT /api/external/v1/offices/l6JSE9dJNk0qfrQ4A6bRuA/depts/l6JSE9dJNk0qfrQ4A6bRuA HTTP/1.1
Accept: application/json
Content-Length: 126
Content-Type: application/json
Host: www.example.com

{
  "dept": {
    "name": "部門名更新",
    "code": "dept_code_更新",
    "disp_order": 20000,
    "memo": "部門メモ更新",
    "is_active": false
  }
}
```

#### Response
```
HTTP/1.1 200
Cache-Control: max-age=0, private, must-revalidate
Content-Length: 199
Content-Type: application/json; charset=utf-8
ETag: W/"3db3fdf0e2a6d961bc525f0f5f8effa0"
Set-Cookie: _ex_session=OSsyQVN0VlpGbWdiYTFiSVlPeXJ4UTBVcnJhanV6eG5jZHJicnpJTkE5RFdxVkk1T2IwM0g0UXNKZWQ1ZXNyRWlIYmI4SWQ5Q2I2WXo3UzVFYk4yZWtlNGFpSmEzNS84YmdQbk1sbkJSRkVaZ1NXejFzVUtkbzVNK2xlMjRkemJFR2ZOVkEreHQwVmNGeW0xZmxYeVR3PT0tLXlFeGRsS0dTMnAyWWpWTG00a3JYc2c9PQ%3D%3D--67638ef9408a9600b50f9d0a0ada4f649addd336; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: abfc6652-3003-469e-b4d3-67468a0aa094
X-Runtime: 0.755057
X-XSS-Protection: 1; mode=block

{
  "id": "l6JSE9dJNk0qfrQ4A6bRuA",
  "memo": "部門メモ更新",
  "code": "dept_code_更新",
  "disp_order": 20000,
  "is_active": false,
  "name": "部門名更新",
  "parent_id": null,
  "root_id": "l6JSE9dJNk0qfrQ4A6bRuA"
}
```

**Comment by kuwazzy** [comment]
お手数お掛けして恐縮ですが、"is_active"に一度、falseの値をセットしてからでも一発でtrueに変更されますか？

以下、CURLからの実行結果です。※Tokenはマスクしています
2回目のPUTメソッドでは、trueをセットしているのですが、falseになりませんが、何故かもう一回PUTメソッドを発行するとfalseに変更されます。CURLと別マシンのPostmanで実行して確認しています。原因を探るアプローチなどありましたらご教示頂けますでしょうか。


```
/ $ curl --header "Authorization: Bearer fca*****" -X PUT -H "Content-Type: application/json" -d '{"dept":{"is_active": false}}' "https://expense.moneyforward.com/api/external/v1/offices/kOdpv2tPqAYL-Ga-gvJKaw/depts/G-B-q8huKozxhO5zqZTfYQ"
{"id":"G-B-q8huKozxhO5zqZTfYQ","memo":"15","code":"EIGYO1","disp_order":1,"is_active":false,"name":"25","parent_id":null,"root_id":"G-B-q8huKozxhO5zqZTfYQ"}/ $ 
/ $ curl --header "Authorization: Bearer fca*****" -X PUT -H "Content-Type: application/json" -d '{"dept":{"is_active": **true**}}' "https://expense.moneyforward.com/api/external/v1/offices/kOdpv2tPqAYL-Ga-gvJKaw/depts/G-B-q8huKozxhO5zqZTfYQ"
{"id":"G-B-q8huKozxhO5zqZTfYQ","memo":"15","code":"EIGYO1","disp_order":1,"is_active":**false**,"name":"25","parent_id":null,"root_id":"G-B-q8huKozxhO5zqZTfYQ"}/ $ 
/ $ curl --header "Authorization: Bearer fca*****" -X PUT -H "Content-Type: application/json" -d '{"dept":{"is_active": true}}' "https://expense.moneyforward.com/api/external/v1/offices/kOdpv2tPqAYL-Ga-gvJKaw/depts/G-B-q8huKozxhO5zqZTfYQ"
{"id":"G-B-q8huKozxhO5zqZTfYQ","memo":"15","code":"EIGYO1","disp_order":1,"is_active":true,"name":"25","parent_id":null,"root_id":"G-B-q8huKozxhO5zqZTfYQ"}/ $
```

**Comment by nkuroda** [comment]
@kuwazzy 
こちらご連絡遅くなりすみません。
データのキャッシュ的なところで、実データは更新されているものの、レスポンスデータが `false` のままでした。
修正を行いましたのでご確認いただければと思います。
よろしくお願いいたします。

**Comment by kuwazzy** [comment]
@nkuroda 

レスポンスデータも更新される事を確認しました。ご対応ありがとうございました。

Bodyパラメータについて、もう一度確認させて頂けますでしょうか。下記の通り、"dept":の外殻をつけるとの事でしたが、

```
{
  "dept": {
     "is_active": false
   }
}
```

APIドキュメントのCurlコマンドサンプルは下記の通り外殻がないパラメータ構造となっています（個人的な感想ですがなんとなく外殻無しの方が自然な気がしました）。過去のIssue（#24:私、#6、#28）を見ると同じような外殻無しのボディーリクエストを投げている方もこれを参考にしたのかもしれません。仕様としては、外殻有り、が正という事で宜しいでしょうか？

```
Curl
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "name": "営業部", \ 
   "memo": "string", \ 
   "code": "string", \ 
   "disp_order": 0, \ 
   "is_active": true, \ 
   "parent_id": "string" \ 
 }' 'https://expense.moneyforward.com/api/external/v1/offices/kOdpv2tPqAYL-Ga-gvJKaw/depts/g20wMwMLdpQTEW9jJsdEAg'
```

お手数お掛けしますがご確認の程宜しくお願いします。

**Comment by nkuroda** [comment]
@kuwazzy 

> 仕様としては、外殻有り、が正という事で宜しいでしょうか？

はい、そうなりますね。。私も気づかなかったのですが、フレームワークがある程度吸収しているようで、外殻なしでも大抵のAPIは動いているようですが、上記APIの場合でいうと外殻なしですと `is_active` の更新が不能です。。。

> APIドキュメントのCurlコマンドサンプルは下記の通り外殻がないパラメータ構造

たしかに、swaggerのAPIドキュメントの方は、外殻なしになっているようですので、時間を見つけて一律外殻付きに変えようと思います。こちらいろいろとご指摘をありがとうございました。
ドキュメントの修正が完了しましたらご連絡致します。

**Comment by kuwazzy** [comment]
@nkuroda 

ご回答ありがとうございます。理解出来ました。
swaggerのAPIドキュメントの方は、仕様が分かりましたので、こちらとしては、お手すきの時で構いません。

丁寧なご説明ありがとうございました。このIssueはクローズとさせて頂きます。

**Comment by nkuroda** [comment]
@kuwazzy 
ご対応遅くなって申し訳ありません。
ドキュメントの方更新いたしました。ご指摘いただきましてありがとうございました。
https://expense.moneyforward.com/api/index.html#/dept/create_dept
