### ISSUE TITLE
【事業所メンバー追加API】office_memberのユーザー追加APIを実行したとき、役職が登録されない

### ISSUE THREAD

**Issue by r-oyama-0611** [moneyforward/expense-api-doc#32]
### 内容
下記APIを実行した時、API結果としては正常に完了した旨が返ってきますが、役職が登録されておりません。
こちら役職を登録するためにはどのように実行すればよろしいでしょうか？
```json
{
	"office_member": {
		"email": "stringa@test.com",
		"name": "テスト 次郎",
		"number": "string",
		"permission_role_id": 201,
		"depts_attributes": [
			{
				"id": "yKns2KGh3KPQ8xgVF*****"
			}
		],
		"position_attributes": [
			{
				"id": "a2angqIX4lmKzxWic*****"
			}
		]
	}
}
```

なお、レスポンスで関係のありそうな"position"項目はnullとして返却されております。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@r-oyama-0611 
お問い合わせありがとうございます。部門と違いまして、役職はひとつしか持てないため、
`position_attributes` は 配列で渡せません。bodyの形式は以下のようにお願い致します。

```
{
  "office_member": {
    "name": "update name",
    "number": "update number",
    "permission_role_id": 203,
    "depts_attributes": [
      {
        "id": "tcTcFjkHV1pJT80Bxyhjwg"
      }
    ],
    "position_attributes": {
      "id": "_TFmQwJF6n_moknLRvRpUw"
    }
  }
}
```

https://expense.moneyforward.com/api/index.html#!/office_member/update_office_member

**Comment by r-oyama-0611** [comment]
@nkuroda 
早々のご回答誠にありがとうございます。
上記のフォーマットに修正し、リクエストを送ったところ問題なく登録できたことを確認いたしました。

こちら解決したためクローズいたします。
