### ISSUE TITLE
【事業所メンバー追加API】追加登録時の承認者ランク設定方法について

### ISSUE THREAD

**Issue by r-oyama-0611** [moneyforward/expense-api-doc#33]
### 内容
度々恐れ入ります。

追加登録時の承認者ランク設定方法がドキュメントには記載されていないことを確認したのですが、管理画面で承認者ランクを設定して登録していることから、APIとしても対応できるのではないかと想定しました。
もしも対応可能でしたらフォーマットをご教示願えますでしょうか？
以下は試験的に試したものですが、固定値で100が設定されてしまいました。

```json
{
	"office_member": {
		"email": "string203@test.com",
		"name": "テスト 次郎",
		"number": "string",
		"permission_role_id": 203,
		"ex_office_member_setting": {
		  "approving_priority": 90
		},
		"depts_attributes": [
			{
				"id": "AcmXcZTf3SX7I_iY5*****"
			}
		],
		"position_attributes": 
		{
			"id": "0gIWRk4RusRIYN5PL*****"
		}
	}
}
```

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@r-oyama-0611
お問い合わせありがとうございます。
メンバー登録、更新APIでは現時点で承認者ランクを設定することは出来ない状態です。
変わりに以下のAPIで更新が可能です。
ですので、メンバー登録API -> 以下APIで更新という順序で対応いただければと思います。
よろしくお願い致します。
 
https://expense.moneyforward.com/api/index.html#!/ex_office_member_setting/update_ex_office_member_setting

**Comment by r-oyama-0611** [comment]
いつも迅速な回答誠にありがとうございます。
上記承知いたしました。

問題が解決いたしましたので、本件をクローズさせていただきます。
