### ISSUE TITLE
事業所一覧以外のAPI接続について

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#34]
### 内容
･https://github.com/moneyforward/expense-api-doc　
の頁を元に、CurlコマンドにてAPIリクエスト「事業所一覧を取得する」は値の取得が行えたのですが、それ以外のAPI(ex.事業所ユーザ一覧を取得するAPI)の場合に、{messeages":[”ログインしてください”]｝curl：(3)　Port number　ended with　’　’　というメッセージが出て、値の取得が行えません。
指定したコマンドは、下記の通りです。
curl https://expense.moneyforward.com/api/external/v1/offices/6410-1232/office
_members  -H "Authorization: Bearer d1d79ff3e8253d2bd776272a230ee19012bc5045e7
9f6712d95d60f8a4fdfdf6"
{"messages":["処理対象のレコードが存在しません"]}

curl https://expense.moneyforward.com/api/external/v1/offices/6410-1232/office
_members -G "Authorization: Bearer d1d79ff3e8253d2bd776272a230ee19012bc5045e79
f6712d95d60f8a4fdfdf6"
{"messages":["ログインしてください"]}curl: (3) Port number ended with ' '

curl https://expense.moneyforward.com/api/external/v1/offices/6410-1232/depts 
-G "Authorization: Bearer d1d79ff3e8253d2bd776272a230ee19012bc5045e79f6712d95d
60f8a4fdfdf6"
{"messages":["ログインしてください"]}curl: (3) Port number ended with ' '

問題点をご教示下さい。
### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
そのエラーが出るということは、`access_token` を `Authoriztion Header` にBearerスキームに設定していないのではないかと思われます。

http request のログ等ご提供頂けますでしょうか？

**Comment by mikinoshita** [comment]
ありがとうございます。
DataSpiderより接続を行って、上記設定を行う事により接続に成功しました。

**Comment by nkuroda** [comment]
@mikinoshita ではcloseさせていただきます！
