### ISSUE TITLE
承認済ﾃﾞｰﾀの取得方法について

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#35]
### 内容
申請データの取得APIにて、MF経費で承認済となったデータかどうか、申請データのstatusにて判断しようと考えています。Statusの区分を見ると、承認段階待ちのステータスの他に、Approved(承認済み)というステータスがあり、このステータスの場合、最終承認を経て、支払を行える段階と考えてよいでしょうか。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
はい、そのとおりです。`approved` が承認完了のステータスとなります。
現在は利用していないのですが、 `paid` （支払済み）というステータスも`approved` のステータスの次のステータスとして利用する可能性があります。

![image](https://user-images.githubusercontent.com/1215551/41461419-9c95d6cc-70ca-11e8-824e-513e4df96095.png)

**Comment by mikinoshita** [comment]
ご回答ありがとうございました。それでは上記にて判断致します。
