### ISSUE TITLE
電子帳簿保存法書類情報を返すAPIについて

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#37]
### 内容
電子帳簿保存法書類情報を返すAPIより取得できる項目に、申請または明細番号がありますが、申請者は登録者という事になるのでしょうか？どの申請者の明細に紐付く証憑か特定するためにどの項目を使用すればよいでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
そちらのAPIで返している申請者は登録者となります。
現状ですと、申請者のメンバー番号（従業員番号）をキーに経費明細を取得するということになるかと思います。

**Comment by mikinoshita** [comment]
ご回答ありがとうございます。
証憑をアップロードした人が申請者本人でない場合も、証憑の登録者は申請者となる、
という理解で宜しいでしょうか？
すみません、宜しくお願い致します。

**Comment by nkuroda** [comment]
@mikinoshita 

> 証憑をアップロードした人が申請者本人でない場合も、証憑の登録者は申請者となる、

いえ、証票をアップロードしたその人になります。（代理で添付したらその人）
なお、証票が紐づく明細については、 `ex_transactionable_type_text` と `ex_transactionable_number` から特定できます。
