### ISSUE TITLE
/api/external/v1/offices/{office_id}/ex_transactions/{id}/journals

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#38]
### 内容
いつもお世話になっております。

多分ドキュメント化されていないと思いますが、
/api/external/v1/offices/{office_id}/ex_transactions/{id}/journals
というリソースをさきほどたまたま見つけました。

該当の取引を仕訳化したものが取れるのですが、弊社にとっては非常にありがたい仕様です。
今後継続して提供していただけそうでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by mikomokaru** [comment]
追記です。
journalsリソース関連でいうと、
オブジェクトの名前が変更に(journal_branches-> ex_journal_branchesなど)なっていたり、
借方貸方の表現が[dr,cr]から[1,-1]に変わっているのを確認しました。

こちらに関しても、恒久的にこの仕様が維持されそうでしょうか？

**Comment by nkuroda** [comment]
@mikomokaru 
お世話になります。返信が遅くなってしまいまして大変申し訳ございません。
仕訳APIについて公開いたしました。以下ご確認ください。よろしくおねがいします。
https://support.biz.moneyforward.com/expense/news/new-feature/journal_api.html
