### ISSUE TITLE
申請データと明細データの更新日時について

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#40]
### 内容
①申請データ
申請データの承認が行われた場合、承認日時の他、更新日時も更新されるでしょうか？
また承認後(approved)、支払を行わない場合、更新日時が更新されるケースはあるでしょうか？

②経費明細データ
申請データに紐付く、経費明細データの更新日時は承認時に更新されるでしょうか？
また申請データの承認後に、紐付く経費明細データの更新日時が更新されるケースはあるでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 

> ①申請データ
> 申請データの承認が行われた場合、承認日時の他、更新日時も更新されるでしょうか？
更新されます。

> また承認後(approved)、支払を行わない場合、更新日時が更新されるケースはあるでしょうか？

現在のところは無いですが、支払済みステータスも考えているので、その場合更新日時が更新されることはあり得ると思います。

> ②経費明細データ
> 申請データに紐付く、経費明細データの更新日時は承認時に更新されるでしょうか？

そちらは更新されないです。

> また申請データの承認後に、紐付く経費明細データの更新日時が更新されるケースはあるでしょうか？

現在、管理者権限に限り、承認済み申請に紐付いていても明細の更新はできます。
（この辺りの仕様は変更する可能性があります）
