### ISSUE TITLE
経費明細について

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#41]
### 内容
経費明細について２点教えて下さい。
①経費明細で従業員宛に支払を行うものと、法人宛に支払を行うものとは、APIで取得可能なデータ上で
　判別可能でしょうか？
②経費明細で支払対象外の明細を登録する事は出来るでしょうか？
　 登録可能な場合、経費明細のAPIで取得可能なデータ上で判別可能でしょうか？
　(ex.経費発生するが従業員が立替していないもの、タクシーチケット等の利用、定期区間内の交通費等)

### 開発通知用
@nkuroda @dito

**Comment by mikinoshita** [comment]
ご回答ありがとうございます。
コーポレートカード等の場合、貸方科目等で判別する事で了解しました。
ちなみに貸方科目はコーポレートカード用のテンプレートで、設定されている、という事でしょうか？

また従業員が意識的に経費の一部を申請する場合（ホテル代の会社支給額を超える部分や定期区間内の交通費を除く場合等）の入力では、別明細で入力頂き、貸方科目を分けて頂く運用となるのでしょうか？

**Comment by nkuroda** [comment]
@mikinoshita 
返信が漏れておりました

> 貸方科目はコーポレートカード用のテンプレートで、設定されている、という事でしょうか？

利用明細が自動連携（コーポレートカード等）されるものについては、貸方科目の設定が出来るようになっています。自動連携用に設定がされていなければ、従業員に設定されたデフォルトの貸方科目が採用される形です。

> また従業員が意識的に経費の一部を申請する場合（ホテル代の会社支給額を超える部分や定期区間内の交通費を除く場合等）の入力

貸方科目でコントロールできるのは、会社が払ったものか、従業員が立替たものかという識別なので、
上記のケースはそもそも会社の経費として計上されてはならないものになると思います。
なので、領収書の金額が6000円だとしてそのうち、経費として認められる部分が5000円だとすると、5000円で経費登録して、メモに経費として認められる金額が5000円までといった補足をするのが実運用だと思います（通常は、お店に5000円と1000円に領収書を割ってもらうのが望ましいと思われます）。
以上よろしくお願いいたします。
