### ISSUE TITLE
新しいアクセストークンを作成するについて

### ISSUE THREAD

**Issue by khanhtc1202** [moneyforward/expense-api-doc#42]
### 内容
```
redirect_uri は https のみ許可しています。
```
問題はどうすれば `redirect_uri` をhttps形式で入手できるのでしょうか？
アプリケーション設定サイト(https://expense.moneyforward.com/oauth/applications/{id}/edit)
から取得されるredirect_uriの形はこれの通りです： `urn:ietf:wg:oauth:2.0:oob`

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@khanhtc1202 
おそらくウェブサービス間の連携でご利用ということではなく、自社の経理処理上でAPIを使いたいというニーズかと思われますので、 redirect_uri には `https://localhost/` など設定頂ければ、Authorization codeの取得はできます。ブラウザの url に
`https://localhost/?code=2713503127ac79xxxxxxxxxxxxxxxxxxxxxxxxx` といった形でcodeがついてきます。

**Comment by nkuroda** [comment]
@khanhtc1202 
自社利用のためにaccess_tokenを取りたいということでしたら、redirect_uriに以下を設定していただくのも良いです。よろしくおねがいします。
`urn://host/ietf/wg/oauth/2.0/oob`

**Comment by khanhtc1202** [comment]
ご回答ありがとうございます。
問題をはっきりと議論しなかったことをお詫びします
私はすでにこのURLに要求によって認証コードを持っていました。
```
https://expense.moneyforward.com/oauth/authorize?client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_URL]&response_type=code&scope=[SCOPE]
```
次のステップでは、このステップの後
```
curl -d client_id=[CLIENT_ID] -d client_secret=[CLIENT_SECRET] -d redirect_uri=[REDIRECT_URL] -d grant_type=authorization_code -d code=[認証コード] -X POST https://expense.moneyforward.com/oauth/token
```
下のエラーが出ました。
```
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```
僕が見つけたエラーは `redirect_uri` が原因でhttps formが原因ではないでしょうか？
私は `redirect_uri` を `https://localhost?code=[認証コード]` に変換して再要求しましたが、同じエラーが起きました。

**Comment by khanhtc1202** [comment]
@nkuroda 
遅く返事してすみません。問題解決でしました、ありがとうございます！
