### ISSUE TITLE
各項目の桁数について

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#43]
### 内容
各WebAPIで取得・登録等できる項目について、
最大桁数が何桁か公開して頂けないでしょうか。
値を引き渡す/受け取る際に、
特定のバイト数で切り捨てる処理が必要かどうか
判別するために利用します。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
![image](https://user-images.githubusercontent.com/1215551/43715822-c9033bc6-99bc-11e8-9252-77c668a6a75c.png)

@mikinoshita 
まずドキュメントをきちんと確認頂いておりますでしょうか？
https://expense.moneyforward.com/apidocs
そして、未整備なものがあった場合に、必要なものだけをリクエスト頂けますでしょうか？
そうでなければ、現実的に対応することは不可能です。

**Comment by mikinoshita** [comment]
お世話になっております。
必要なものだけとのことでしたので、差し当たり必要な項目・確認事項を取りまとめました。
添付させて頂きますので、ご確認頂けますでしょうか。
[桁数確認.xlsx](https://github.com/moneyforward/expense-api-doc/files/2269426/default.xlsx)

お手数ですが、宜しくお願い致します。

**Comment by nkuroda** [comment]
@mikinoshita 
ご指摘頂いたところで、長さ等の定義がないところは追加しましたので、ドキュメントサイトで確認ください。
https://expense.moneyforward.com/api/index.html

ただ、 `ExTransaction#automatic_status` や、`ExReport.status` はEnum型ですので、最大長についてはリストの中の最大を設定してください（種類が今後追加されるので、バッファを見たサイズにしておいた方が良いかもしれません）
なお、 `ExTransaction#error_message`, `ExTransaction#warning_message` は当社側では長さの指定はされていないので、DBに保存等されるのであれば、適当なサイズで摺り切りするように定義していただければと思います。現実的には1000文字長あれば収まると思われます。
