### ISSUE TITLE
ネットワークセキュリティのポリシーについて

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#44]
### 内容
お世話になっております。
ネットワークのセキュリティについて、1点確認させてください。

MFクラウド経費のWebAPIを呼び出すにあたり、
透過型プロキシを経由している場合は通信できないようにするなど、
通信経路によって遮断するようなセキュリティはありますでしょうか。

以上です。
宜しくお願い致します。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
Webアプリケーションフレームワークによるガードが入っております。
もし、通信がフィルタされたかどうかについてご確認されたいということですと、
ログ調査が必要となりますので、こちらでやり取りはできず、
営業経由でhttpリクエストのデータなどを渡してお問い合わせいただく形になるかと思います。
