### ISSUE TITLE
OAuth2認証設定におけるアクセストークン取得方法（iPaaS利用想定）

### ISSUE THREAD

**Issue by moai1213** [moneyforward/expense-api-doc#45]
### 内容
貴社サービスにiPaaSを使って接続しようと設定を試みています。

OAuth2.0について、理解が乏しいので以下サイトで学びました。
https://qiita.com/TakahikoKawasaki/items/e37caf50776e00e733be

貴社のAPIサービスは、認可サーバー、リソースサーバーの両方が貴社サーバーで運用されているという理解でよろしいでしょうか？
そうであるならば、認可サーバーに問い合わせるURIは
https://expense.moneyforward.com/oauth/authorize
で宜しいでしょうか？

https://github.com/moneyforward/expense-api-doc
「アクセストークンの発行」に記載されているリクエスト例は、クライアントアプリケーションがSaaS（iPaaS）なのでredirect_uriの値はSaaS（iPaaS）が指定するコールバックとしました。

そこで、認証を試みたところ、
OAuth authorization failed
となりました。

アクセストークン、リフレッシュトークンをSaaS（iPaaS）上で、どのように取得すれば宜しいでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@moai1213 

> 貴社のAPIサービスは、認可サーバー、リソースサーバーの両方が貴社サーバーで運用されているという理解でよろしいでしょうか？

はい、そうなります。

> OAuth authorization failed となりました。

認可コードの取得前に失敗しているということと思われますが、以下のようなアプリケーションの承認画面は出ていますでしょうか？

![test](https://user-images.githubusercontent.com/1215551/43952818-fd266aa0-9cd1-11e8-816a-31c66cb0a381.gif)

**Comment by moai1213** [comment]
早速のご回答ありがとうございます。

自身のブラウザ上で実行（callback_urlはSaaS）した場合、ご案内頂いた認証画面が表示され、承認ボタンを押すと先の投稿に記載した用に認証エラーとなります。
callback_uriをurn://host/ietf/wg/oauth/2.0/oobにすると認証コードを取得できます。
※：urn://host/ietf/wg/oauth/2.0/oobの意味を理解していませんが・・・

試しに、iPaaS側から直接以下の設定をして接続を試みましたが、 Connection failed: Can't create account. Name should be unique となるやはりダメでした。

- OAuth2 auth URL
https://expense.moneyforward.com/oauth/authorize?redirect_uri= https://www.workato.com/oauth/callback&response_type=code&scope=transaction:write:
- OAuth2 token URL
https://expense.moneyforward.com/oauth/token
OAuth2 client ID、OAuth2 client secretは指定の値

アクセストークンを取得すべきは、iPaaS側だと思うので、この設定に何か問題があるのだと思っています。
OAuth2 client ID、OAuth2 client secretをOAuth2 auh URLの引数に付加していないのがいけないのでしょうか？

**Comment by nkuroda** [comment]
@moai1213 
認証を押したあとに、iPaaS側の指定したパスにコールバックは戻ってきておりますでしょうか？？
コールバックが戻らずに認証エラーになりますでしょうか？

**Comment by nkuroda** [comment]
@moai1213 
いったん close させていただきます。
解消していらっしゃっらなければ、またご連絡ください。
