### ISSUE TITLE
事業所メンバーの追加処理

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#46]
お世話になっております。
事業所メンバーの追加処理につきまして、確認させて下さい。
（POSTの /api/external/v1/offices/{office_id}/office_members）

DataSpiderを使用して、上記情報を登録する際、
パラメータとして、MFクラウド経費API βの定義に記載の、
メンバーのパラメータを設定致しております。
{
  "email": "string",
  "name": "string",
  "number": "string",
  "permission_role_id": 201,
  "depts_attributes": [
    {
      "id": "string"
    }
  ],
  "position_attributes": {
    "id": "string"
  }
}

上記に対して、メールアドレスの情報も指定しているのですが、
実際に処理を実行してみますと、
「メールアドレスを入力してください。」のエラーが返って来ており、
POSTを実行出来ない状態となっております。

尚、調査として、メールアドレスの形式（xxxx@yyyy.com の様な形）で、
固定文字を設定する様にもしてみましたが、同様のエラーが返って来ております。

大変申し訳御座いませんが、当事象の原因、ないしは対策として、
何か情報をお持ちで無いでしょうか。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
`office_member` を外郭につけてお試しいただけますでしょうか？

```
{
  "office_member" : {
      email: '',
      ...
   }
}
```


それでもエラーが出る場合は、実際にエラーが出る http request について情報をいただけないでしょうか？
header や body の情報がわかるかたちで。

**Comment by nkuroda** [comment]
@mikinoshita 
リクエストbodyのフォーマットが問題に見えます。DataSpiderでのログの見方はよくわからないですが、
`office_member` キーの内側にemail等が設定されているようには見えないです。

```
{
    "email":"test@aaa-bbbzzz",
    "name":"テスト　メンバ２",
    "number":"TEST02",
    "permission_role_id":"201",
    "id":"1,2,3,4",
    "element":"1,2,3,4",
    "depts_attributes":"1,2,3,4",
    "id":"A101",
    "position_attributes":"A101",
    "office_member":"A101"
}
```

**Comment by mikinoshita** [comment]
@nkuroda
回答頂きまして、有り難う御座います。
また、毎々、お手数をお掛けして、申し訳御座いません。

＞以下のようなフォーマットでお願いします。
ログの情報を共有する以前より、最初に回答頂いた形式でjsonフォーマット（添付ファイル参照）を作成し、
DataSpiderのPOST処理のリクエスト設定で、スキーマを設定。
スキーマに対して値をセットする様にしている認識なのですが、処理を実行しますと、
ログに出力された様な内容となってしまいます。

jsonの定義がまずかったりしますでしょうか。
[JSONPOSTOFFICEMEMBER.txt](https://github.com/moneyforward/expense-api-doc/files/2302286/JSONPOSTOFFICEMEMBER.txt)

**Comment by mikinoshita** [comment]
@mikinoshita
回答頂きまして、有り難う御座います。
また、毎々、お手数をお掛けしまして、大変申し訳御座いません。

jsonのフォーマットですが、DataSpider上の定義ミスにより、
{
  "office_member": {
      "email": "test@aaa-bbbzzz"
   }
}
の様な形になっておりませんでした。
設定を見直しました所、メンバー情報の登録が出来る様になりました。

しかしながら、所属部門と役職情報の登録が出来ません。
（ＡＰＩからのステータスは、HTTP/1.1 200 OKで返って来ております。）

{
    "office_member":{
        "email":"t*s*@*a*-*b*z*z",
        "name":"テスト　メンバ２",
        "number":"TEST02",
        "permission_role_id":"201",
        "depts":[
            {
                "id":"7QQSaoZObcqa35n8gadLAQ"
            }
        ],
        "position":{
            "id":"6mCp2E7uKIzVxdsruOIJGQ"
        }
    }
}

所属部門と役職情報の設定が間違っていたりしますでしょうか。

**Comment by mikinoshita** [comment]
@nkuroda
回答頂きまして、有り難う御座います。
また、毎々、お手数をお掛けしまして、大変申し訳御座いません。

jsonのフォーマットですが、DataSpider上の定義ミスにより、
{
　 "office_member": {
　 　"email": "test@aaa-bbbzzz"
 　}
 }
の様な形になっておりませんでした。
 設定を見直しました所、メンバー情報の登録が出来る様になりました。

しかしながら、所属部門と役職情報の登録が出来ません。
 （ＡＰＩからのステータスは、HTTP/1.1 200 OKで返って来ております。）

{
　 "office_member":{
　　 "email":"ts@a-bz*z",
　　 "name":"テスト　メンバ２",
　　 "number":"TEST02",
　　 "permission_role_id":"201",
　　 "depts":[
　　 {
　　　　 "id":"7QQSaoZObcqa35n8gadLAQ"
　　 }
　　 ],
　　 "position":{
　　　　 "id":"6mCp2E7uKIzVxdsruOIJGQ"
　　 }
　 }
 }
設定が間違っていたりしますでしょうか。
[ログ.txt](https://github.com/moneyforward/expense-api-doc/files/2304909/default.txt)

**Comment by nkuroda** [comment]
@mikinoshita 
パラメータが違います。
`depts_attributes` と `position_attributes` にしなければいけないです。
ドキュメントをよく見ていただければと思います。
https://expense.moneyforward.com/api/index.html#/office_member/create_office_member

**Comment by mikinoshita** [comment]
@nkuroda
回答頂きまして、有り難う御座います。

＞depts_attributes と position_attributes にしなければいけないです。
大変申し訳御座いませんでした。
ただ、先週試した時は、上記の状態でエラーとなっておりましたので、
「_attributes」を外した状態で試しておりました。
（DataSpider側の設定ミスかも知れませんね。）

回答頂いた内容で再度確認しました所、所属部門と役職が登録された様ですので、
クローズとして頂いて結構です。
