### ISSUE TITLE
事業所全体の経費明細リストを返すについて

### ISSUE THREAD

**Issue by mikinoshita** [moneyforward/expense-api-doc#47]
いつもお世話になっております。
掲題のＡＰＩにつきまして、仕様を確認させて下さい。
（GETの/api/external/v1/offices/{office_id}/ex_transactions）

経費明細データを作成後、本日（2018年8月23日）に上記ＡＰＩを使用し、データを取得しようとしますと、支払日が2018年8月20日のデータが取得されない様に見受けられました。（8月21日以降のデータなら取得可能。）

ちなみに、昨日（2018年8月22日）に動作させた際は、2018年8月20日のデータが取得出来ていた様に見受けられます。

当該ＡＰＩにつきまして、「システム日付の何日前まで取得する」様な仕様があると考えて宜しいでしょうか。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikinoshita 
おそらくページングされているからだと思われます。 `next` に次のページのパスがあると思うので、そちらのパスにアクセスすると2ページ目のデータが取得できます。
