### ISSUE TITLE
事業所全体の経費明細リストを返すAPIのソートについて

### ISSUE THREAD

**Issue by yu3ikeda** [moneyforward/expense-api-doc#48]
いつもお世話になっております。

事業所全体の経費明細リストを返すAPIのソートについて確認させてください。
/api/external/v1/offices/{office_id}/ex_transactions

過去同様の質問があったのですが、APIが少し異なるので、念のため確認させて頂きたく存じます。
以下の並び順という認識でよろしいでしょうか？
①支払日（recognized_at）の降順（日付が空の場合は優先）
②明細番号（number）の降順

宜しくお願い致します。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@yu3ikeda 
ご指摘の通りです。よろしくお願いいたします。

なお、今後ソートキーをリクエストパラメータで設定できるようにする予定です。
