### ISSUE TITLE
API連係によるデータ取得について

### ISSUE THREAD

**Issue by ishikawa-r** [moneyforward/expense-api-doc#49]
### 内容
APIの申請で、過去登録日（2018/8/30以前）のデータが抽出できなくなりました。
まだ8月2日時点では、未承認だったため、10月で取り込みしたいのですが、なにか
抽出条件で対象外になってしまっていますでしょうか？
抽出対象とする手段がありましたらご享受ください。

　　（例）申請番号3498
　　　　作成日　2018/8/2
　　　　申請日　2018/10/2
　　　　承認日　2018/10/3     

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@ishikawa-r 
お問い合わせありがとうございます。
上記ですが、現在該当APIですが、直近2ヶ月、本日ですと10月と9月分のみ返しておりました。
ご迷惑をおかけし申し訳ございません。こちら本日中に修正いたします。
よろしくおねがいいたします。作業完了しましたら、こちらでご報告いたします。

**Comment by ishikawa-r** [comment]
了解しました。案件はクローズしていただいたようですが、完了ということでよろしいでしょうか。
よろしくお願いします。

**Comment by nkuroda** [comment]
@ishikawa-r すみません。リリースは先程完了しました。ご確認いただけますでしょうか？
(githubの機能でパッチがmasterに取り込まれたタイミングで自動でcloseされていました）
