### ISSUE TITLE
office_membersにフィルタをかけて取得する方法

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#5]
たびたびの質問すいません。
office_membersのgetで返されるリストが下記のような結果だったとします。
```
[
     { id: 'aaa', //MFさんが振ったID
       number: 'DEPT1102' //当社で管理しているID
     },
     { id: 'bbb',
       number: 'DEPT1105'
     }
//以下200件ぐらい登録されているとします。
]
```
numberには、当社管理の社員コード的なものが入っているとします。
当社側はnumberは知っているのですが、idは管理対象外なので、わかりません。

今、DEPT1105のid(上記例だとbbb)を知る必要があります。
といったとき、現状だとやはり、全件取得して、当社側で一致するオブジェクトを探す必要がありますか？

GET /api/external/v1/offices/{office_id}/office_members?code=DEPT1105
みたいなインターフェイスがあるといいのですが。

**Comment by nkuroda** [comment]
@mikomokaru 
ご質問ありがとうございます。
現状のところこのAPIは検索のパラメーターを取っていない状態です。
（他のAPIはある程度検索パラメーターは受け取れて、ただドキュメントに書き漏れしているというのが多いのですが。。）
掲示頂いたユースケースは良く発生するケースだと思いますので、検索パラメータを受け取れるようにAPIを修正しようと思います。

修正が完了したらご連絡致します。

**Comment by mikomokaru** [comment]
@nkuroda 
早速のご回答、ありがとうございます。
また、API修正までの意思決定がお早くて、いつも感銘をうけております。

では、期待してお待ちしております。

**Comment by nkuroda** [comment]
office_member系APIはv2エンドポイントに以降したので以下に検索機能をつける
https://expense.moneyforward.com/api/index.html#/office_member/find_office_members_v2

**Comment by benedict-lim** [comment]
開発メモ：

`app/controllers/api/external/v2/offices/office_members_controller.rb`
クエリーパラメーターは`params`に入っている。`code`というクエリーパラメーターを許可すると良い。（データ的には`number`という属性だけど）
Q: `office_id`はどこで参照している？ログイン中のユーザーの`current_office`を操作しているので、`office_id`の指定が必要がないと思った

`app/controllers/concerns/api/external/v2/offices/office_members/swagger_controller_concern.rb`
APIドキュメントを更新する

**Comment by benedict-lim** [comment]
@nkuroda 
`number`カラムですが、クエリーパラメーターも`number`でもよろしいですか？（なぜstring型のカラムがnumberというネーミングになったか気になります 🤔）

**Comment by benedict-lim** [comment]
@nkuroda 

内部の開発・動作確認は完了しましたので、やりとりの引き続きをお願いしてもよろしいでしょうか？
問題がなければ、このIssueをクローズしていただけたらと思います！

**Comment by nkuroda** [comment]
@mikomokaru 
検索の対応しております。内容ご確認頂ければと思います！よろしくおねがいいたします。
https://expense.moneyforward.com/api/index.html#/office_member/find_office_members_v2

**Comment by mikomokaru** [comment]
@nkuroda ありがとうございます！
