### ISSUE TITLE
MF経費へPOSTでつなげたときのエラーについて

### ISSUE THREAD

**Issue by InoueFunai** [moneyforward/expense-api-doc#51]
### 内容
度々のご質問申し訳ありません。

現在、ZohoCRM→MF経費の流れでAPI接続を行っております。
MF経費が指定するAPIリファレンスより、
「GET」についてはリターンコード200で取得ができるのですが、
「POST」した場合、{"status":500,"error":"Internal Server Error"}
が返ってくる状況です。

こちらのエラーコードはMF経費が発行しているものでしょうか？
もしそうでしたら、考えられる原因がありましたらお知らせいただけると幸いです。

以上。宜しくお願い致します。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@InoueFunai 
サーバー側で検知しておりまして、適切なエラーメッセージが返せておらずすみません。
原因としてはパラメーターのフォーマットに問題があるようです。
ご確認のほどよろしくおねがいします。

**Comment by nkuroda** [comment]
@InoueFunai 
> サーバー側で検知しておりまして、適切なエラーメッセージが返せておらずすみません。
>（エラーメッセージは今夜のリリースで status 400 で、 error は parameter is wrong というのを返すようになります）

上記対応完了しています。パラメータの問題ということでこちらclose致します。
よろしくおねがいします。
