### ISSUE TITLE
アクセストークンの破棄方法について

### ISSUE THREAD

**Issue by YusukeKinoshita** [moneyforward/expense-api-doc#53]
### 内容

- access_tokenの破棄方法がドキュメントに記載されていないので、ご教示いただきたい

- oauthの仕様的には、認証時に得たaccess_tokenまたはrefresh_tokenを使って、token=access_tokenまたはtoken=refresh_tokenで/oauth/revokeにアクセスすることで破棄できると思うのですが、仕様通りでしょうか

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@YusukeKinoshita 

ご指摘の通り、access_tokenの無効化処理についてドキュメントに記載がなく失礼致しました。
連休明けにドキュメントをupdate致します。
なお、取得したアクセストークン等を利用して以下リクエストにてアクセストークンの無効化可能です。

```
curl -d client_id=[CLIENT_ID] -d client_secret=[CLIENT_SECRET] -d token=[アクセストークン] -X POST https://expense.moneyforward.com/oauth/revoke
```

**Comment by YusukeKinoshita** [comment]
迅速にご対応いただきありがとうございます。
