### ISSUE TITLE
支払依頼の明細の取得について

### ISSUE THREAD

**Issue by InoueFunai** [moneyforward/expense-api-doc#55]
### 内容
ご担当者様

掲題の件について、確認したくご質問させて頂きます。

APIで支払依頼の明細を取得したいのですが、手法はありますでしょうか？
可能でしたら、経費明細のように承認時刻を条件にできればと考えております
私のAPIドキュメントの見落としでしたら申し訳ありません。

お手数ですが、ご確認お願いいたします。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@InoueFunai 
お問い合わせ頂きありがとうございます。開発を予定しておりますが、具体的なスケジュールは予定していないです。
なお、支払明細については、経費明細と違い、申請や集計に紐づく形でしか存在できず、
経費明細とは違って `GET /reports/:report_id/invoice_transactions` や `GET /report_units/:report_unit_id/invoice_transactions`
といったパスでAPIを提供するかと思います。

対応したらまたこちらでご案内します。お待たせして申し訳ございませんがよろしくおねがいします。

**Comment by InoueFunai** [comment]
@nkuroda

ご連絡ありがとうございます。承知いたしました。
対応頂きましたら、またご連絡お願いいたします。

**Comment by nkuroda** [comment]
@InoueFunai 
はい承知いたしました。

なおですが、APIではないのですが、本日管理・分析で支払依頼の分析機能が出ておりこちらから集計したデータのDLもできるようになっています。
https://support.biz.moneyforward.com/expense/news/new-feature/invoice_analysis.html

また、申請単位や集計単位では支払明細のCSVダウンロードは可能となっておりますので、
APIでなくてももしかすると良いのではと感じております。

一度ご確認のほどよろしくお願いいたします。

**Comment by InoueFunai** [comment]
@nkuroda

データダウンロードで対応できるのでしたら、ひとまずそちらで対応させて頂きます。

APIでつなぎたいと思ったところとしては、
別のサービスにプロジェクト・科目ごとに承認されたものから金額を連携して、
リアルタイムに粗利算出を行えないかと考えていたためです。

お手数おかけしました、ありがとうございます。

**Comment by nkuroda** [comment]
@InoueFunai 
支払明細APIを本日リリースしました。
https://expense.moneyforward.com/api/index.html#/ex_invoice_transaction/find_office_ex_invoice_transactions
時間がたっており恐縮ですが、こちらでご希望にそえるかもしれません。
よろしくおねがいします。
