### ISSUE TITLE
支払依頼の追加

### ISSUE THREAD

**Issue by shokodama** [moneyforward/expense-api-doc#57]
### 内容
支払依頼の追加（画像登録など含め）を行いたいが可能でしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@shokodama 
返信遅くなりまして申し訳ございません。
現在、支払依頼の登録APIはご準備がございません。
将来的には準備ができればと考えておりますが、具体的な予定は立っておりません。

残念な回答となり恐縮ですがよろしくおねがいします。

**Comment by shokodama** [comment]
@nkuroda 
ありがとうございます、そうなのですね、承知しました。

**Comment by nkuroda** [comment]
@shokodama 
一点お伝え漏れましたが、APIよりも、まずはウェブの方でCSVインポートを検討・対応していく予定です。よろしくおねがいします。

**Comment by shokodama** [comment]
@nkuroda 
ありがとうございます。
経費もそうですが、証憑ファイルも一括でアップロード・ダウンロードできる方法もあると助かります。
（CSVというファイルでそれは無理というものでしょうが希望です笑）
