### ISSUE TITLE
アクセストークンの有効期間について

### ISSUE THREAD

**Issue by denkohana** [moneyforward/expense-api-doc#58]
### 内容
発行したアクセス・トークン[access_token]の有効期間（何日程度有効か）の仕様を教えて下さい。
　※１回発行して２週間経過しますが同じアクセス・トークンの値でAPI（β版）にアクセスできます

**Comment by denkohana** [comment]
### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@denkohana 
現在は90日です。
今後仕様変更もありえますので、アクセストークンを返すレスポンスに有効期限を含めておりますので、そちらをご確認ください。
なお、即時にrevokeすることも可能となっています。

https://github.com/moneyforward/expense-api-doc#%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AE%E7%84%A1%E5%8A%B9%E5%8C%96

**Comment by denkohana** [comment]
ご回答ありがとうございました。「expires_in:7776000」の値（秒数）で確認できました。
