### ISSUE TITLE
「事業所全体の経費明細リストを返す」APIの情報欠落

### ISSUE THREAD

**Issue by yu3ikeda** [moneyforward/expense-api-doc#59]
お世話になります。

当APIを承認時刻FROMを条件指定して利用しております。

Pageを指定してデータを取得する仕様ですが、
1ページ目、2ページ目、3ページ目・・・と繰り返し情報取得している最中に、1ページ目に取得できるデータが登録（承認）された場合、情報が欠落します。
情報欠落を防ぐ方法はありますでしょうか？
また、現在はソート順が明細番号降順である認識で合っていますでしょうか？過去に問合せした際は日付（降順）、明細番号（降順）と回答頂いたのですが、情報欠落の動作確認を行っている際にソート順が異なるように思いまして、お手数ですが念のためご確認頂きたく存じます。

情報欠落を防ぐ方法として承認時刻TOを指定する方法も考えらえるのですが、
MF経費の承認時刻は、承認ボタンを押した時刻でしょうか？それとも承認が完了した時刻でしょうか？前者の場合、登録完了までタイムラグがあるため、承認時刻TOに設定する時間を調整（現在時刻の少し前）する必要があると考えております。
また、承認ボタン押下でN経費明細を更新すると思いますが、全て同じタイミングで更新されますでしょうか？承認時刻がN明細順次設定されるのであれば、承認時刻TOを指定しても厳密には情報欠落してしまうと考えており、確認させて頂きたく存じます。

宜しくお願い致します。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@yu3ikeda 
お問い合わせ頂きありがとうございます。

> 情報欠落を防ぐ方法として承認時刻TOを指定する方法も考えらえるのですが、

はい、こちらTOを指定し、FROM, TO でサンドイッチしていただければと思います。
（別の会社様で同様の連携ではそうされています）

> MF経費の承認時刻は、承認ボタンを押した時刻でしょうか？それとも承認が完了した時刻でしょうか？前者の場合、登録完了までタイムラグがあるため、承認時刻TOに設定する時間を調整（現在時刻の少し前）する必要があると考えております。MF経費の承認時刻は、承認ボタンを押した時刻でしょうか？それとも承認が完了した時刻でしょうか？前者の場合、登録完了までタイムラグがあるため、承認時刻TOに設定する時間を調整（現在時刻の少し前）する必要があると考えております。
また、承認ボタン押下でN経費明細を更新すると思いますが、全て同じタイミングで更新されますでしょうか？承認時刻がN明細順次設定されるのであれば、承認時刻TOを指定しても厳密には情報欠落してしまうと考えており、確認させて頂きたく存じます。

承認時刻は経費明細自体には持っておらず、申請の承認時刻を参照している形となります。
全て申請の承認時刻基準で実装されれば良いと思います。

> 承認ボタンを押した時刻でしょうか？それとも承認が完了した時刻でしょうか？

承認完了の時刻です。

> 現在はソート順が明細番号降順である認識で合っていますでしょうか？過去に問合せした際は日付（降順）、明細番号（降順）と回答頂いたのですが、

Order句は以下です。日付が空かどうかが第1キー（日付空優先）、第２キーが日付の降順、第３キーが番号です。

"ORDER BY ISNULL(recognized_at) DESC,  recognized_at DESC, number DESC'

以上よろしくおねがいします。
