### ISSUE TITLE
APIでメンバー登録＆削除（POST＆DELETE）した場合の挙動について

### ISSUE THREAD

**Issue by denkohana** [moneyforward/expense-api-doc#60]
### 内容
お世話になります。APIの仕様(メンバ削除後の挙動等)について以下２点確認させて下さい。

(1)MFクラウド経費API(β版)でメンバー登録（POST送信）してから、
  MFクラウド経費の招待メール(パスワード付き)を受信し、１度ログイン＆ログアウト後に
  APIでメンバーを削除（DELETE送信）して削除が成功(メンバー管理画面で消去を確認済)したのですが、
  MFクラウド経費のアカウント（メールアドレス＆パスワード）は残りつづけて再度ログインできます。
  （メンバ削除後にログインした場合、所属事業所がない状態で経費申請できない状態となる）

  上記の仕様（APIでメンバー削除してもアカウントは残りログインを許可する）で認識は合っていますでしょうか？
    ※アカウントを残す理由として、月々のサービス利用料(アクティブユーザ)の請求等で必要な気はしております
    ※（削除後のログインで、新規の事業所登録が自由に行えるようですが避けたい）

(2)今の時点で、MFクラウド経費のアカウント削除用のAPIは提供されていますでしょうか。

### 開発通知用
@nkuroda @dito

**Comment by denkohana** [comment]
＜参考追記＞
※アカウントのロック機能（有効化・無効化：ロック日時を内部保持）の有用性について

**Comment by nkuroda** [comment]
@denkohana 
お問い合わせありがとうございます。
ご認識のとおりです。

マネーフォワードのログインアカウント等の対象となるのはUser（メアド、PWを持つ）で、実はOfficeMemberは別概念となっております。Userは複数の事業所にOfficeMemberとして所属できるという関係となります。
そのため、OfficeMemberを削除APIでUserまで消すことができない（Userは他の事業所にも属しうるため消すとまずい）という形です。

今後Userのサービス退会APIというのは検討してまいります。
現在UserはMFのサービス全体で共通となっており、経費利用だけをしているUserの場合はこの利用停止で削除まで至らせることができますが、ほかサービスを使っている場合は経費のAPIだけで削除まで至らせるのはやってはまずいと考えております。

以上よろしくおねがいします。
