### ISSUE TITLE
Swaggerのタイポを発見しました

### ISSUE THREAD

**Issue by kabanyasu** [moneyforward/expense-api-doc#61]
### 内容
お問い合わせの内容を箇条書き等で簡潔にご記載ください

- Swaggerのex_transactionの部分のおけるタイポを発見しました。
- Responses => Model => ExTransaction => currencyにおいて、「通貨」と書くべきところ「通過」と記載されている。

お手数おかけいたしますが、ご確認をお願いいたします。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@kabanyasu 
ご指摘ありがとうございました。恥ずかしいミスをしておりました。
本日中には修正のリリースを行っておきます。よろしくお願い致します。

**Comment by nkuroda** [comment]
@kabanyasu 対応完了致しました。ご指摘ありがとうございました。
