### ISSUE TITLE
経費明細の代理登録

### ISSUE THREAD

**Issue by necochai** [moneyforward/expense-api-doc#62]
### 内容
お世話になります。
経費明細を指定したメンバーの経費として登録したいのですが、
可能でしょうか。
以下で{office_member_id}を指定してPOSTしたのですが、
認証したメンバーの経費として登録されてしまいました。

　/api/external/v1/offices/{office_id}/office_members/{office_member_id}/ex_transactions

よろしくお願いいたします。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@necochai 
こちらの不具合のご連絡ありがとうございました。
当初リリース以後にデグレが発生しておりました。
テストコードでのチェックも甘かったので、テストを厚くしております。
修正完了いたしております。お試しいただければと思います。
よろしくおねがいします。

**Comment by necochai** [comment]
@nkuroda 
迅速なご対応ありがとうございます。
無事登録することができました。
今後ともよろしくお願いいたします。
