### ISSUE TITLE
クラウド経費のAPIで利用されるトークンの有効期限について

### ISSUE THREAD

**Issue by RolandIchikawa** [moneyforward/expense-api-doc#63]
### 内容
クラウド経費のAPIで利用されるトークンの有効期限は、いつまでになるでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@RolandIchikawa 
現在の設定は90日ですが、今後変わりえます。
具体的に切れる時刻は、アクセストークンを返すAPIに有効期限フィールド付きで返されますので、そちらを参照してください。
なお、リフレッシュトークンで新しいアクセストークンの取得が可能です。
