### ISSUE TITLE
クラウド経費のセキュリティ対策について

### ISSUE THREAD

**Issue by RolandIchikawa** [moneyforward/expense-api-doc#64]
### 内容
標題の件、以下についてそれぞれ教えてください。
・不正攻撃対策は施されていますか？
・利用デバイスの制限は可能ですか？
・アクセスログの取得は可能ですか？
・BCP的な観点から何らかの対策はされていますか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@RolandIchikawa 
こちらはAPIに関する不具合やお問い合わせになりますので、
別口でお問い合わせいただければと思います。
