### ISSUE TITLE
クラウド経費へのログインについて

### ISSUE THREAD

**Issue by RolandIchikawa** [moneyforward/expense-api-doc#65]
### 内容
PC(Webブラウザ)からはOffice365アカウントでのログインが可能ですが、スマホアプリからはまだ出来ない、という認識で正しいでしょうか？また、今後の予定も合わせてお知らせください。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@RolandIchikawa 
はい現在スマホアプリでOffice365アカウントでのログインに対応しておりません。
また、現在のログイン認証周りについては、シングルサインオン周りの修正など（現在はユーザー自身がOffice365アカウントの紐づけなどをしなければいけませんが、これらを会社側の設定でできるようにするなど）、ウェブもスマホも大幅にリプレースを予定しています。

なお、申し訳ないですが、こちらのgithubのissueについては、APIに関する質問や不具合報告のみとなりますので、サービスのお問い合わせは別口でお願いできたらと思います。
