### ISSUE TITLE
既存の経費明細に領収書を紐付ける方法について

### ISSUE THREAD

**Issue by kaonash** [moneyforward/expense-api-doc#66]
### 内容
https://github.com/moneyforward/expense-api-doc/issues/9 とも関連するのですが、既存の経費明細に新たに領収書をアップロードして紐付けることは可能でしょうか？

`POST /api/external/v1/offices/{office_id}/me/upload_receipt`

でアップロード自体はできそうなのですが、経費明細の更新・追加APIのリクエストパラメータにmf_file_idが入っていないように見え、どのようにしてアップロードした領収書を紐付ければいいかがわかりません。

お手数をおかけしますが、上記についてご教示いただけますでしょうか。

### 開発通知用
@nkuroda @dito

**Comment by kaonash** [comment]
@nkuroda @dito 
本件、なにか分かりますでしょうか？

**Comment by nkuroda** [comment]
@kaonash 
すみません。現状まだ経費明細の登録、更新APIでできずでして、
APIを改修したいと考えております。
お手数ですが、そちらをお待ち頂ければと思います。

**Comment by kaonash** [comment]
@nkuroda 
ご返信ありがとうございます。
ということは、現状API経由で領収書付きで経費明細を登録する方法は存在しないという理解で合っていますでしょうか？

既存の経費明細に領収書を紐付けることは現状できないということは理解したのですが、それ以外の方法で経費明細と領収書を一緒に登録・更新する方法があるのかどうかを伺えればと思います。

**Comment by nkuroda** [comment]
@kaonash 

> ということは、現状API経由で領収書付きで経費明細を登録する方法は存在しないという理解で合っていますでしょうか？

こちらですが、領収書がついていない経費明細について領収書をつけるAPIは現在ありません。
ただ、領収書付きの経費明細を作ることはできます（ただし、基本的にはOCR処理やオペレーター入力処理を想定しているので、経費明細の内容の入力はできないAPIです）

以下APIとなります。
https://expense.moneyforward.com/api/index.html#/ex_transaction/upload_member_receipt

**Comment by kaonash** [comment]
@nkuroda 
承知しました。

> ただ、領収書付きの経費明細を作ることはできます（ただし、基本的にはOCR処理やオペレーター入力処理を想定しているので、経費明細の内容の入力はできないAPIです）
今必要としているのは、まさにこの明細の内容と一緒に領収書を登録することなので、`upload_member_receipt`ですとちょっと要件が満たせなさそうですね。。。

ひとまず既存の経費明細に領収書をつけられるようなAPIの改修をお待ちしたいと思います。

宜しくお願いいたします！

**Comment by nkuroda** [comment]
@kaonash 

承知しました。開発の方をお待ち頂ければと思います。
よろしくお願い致します！

**Comment by pachirel** [comment]
@nkuroda こちら、何かアップデートありますでしょうか。
他システムとのインテグレーションのために、経費申請の追加、明細の追加、明細へのファイル添付までを API で自動化できると良いなと考えています。

**Comment by nkuroda** [comment]
@pachirel 
申し訳ありません。進んでいない状況でしたので、再度検討にかけてみます。

**Comment by koyo-miyamura** [comment]
こちら時間が経過しており当時と状況も大きく変わっておりますので一旦クローズさせていただきたいと思います。
