### ISSUE TITLE
Curl コマンドでAPIを試す場合

### ISSUE THREAD

**Issue by kamikaze123** [moneyforward/expense-api-doc#7]
office : 事業所

https://expense.moneyforward.com/api/index.html#!/office/find_offices

このAPIリクエストを送る場合の例を教えていただけますか？

下のurlではテストができなくなっているので、どのようにリクエストを送れば良いのかわかりません。

https://expense.moneyforward.com/api/index.html#!/office/find_offices

--------------------------------------------------------------------------------

**Comment by nkuroda** [comment]
@kamikaze123 
お問い合わせ頂きありがとうございます。
curl で該当APIを叩くサンプルですが、

```
curl https://expense.moneyforward.com/api/external/v1/offices -H "Authorization: Bearer [ACCESS_TOKEN]"
```

となります。お試しください。よろしくお願いします。

**Comment by nkuroda** [comment]
READMEにも追記しておきます。

**Comment by kamikaze123** [comment]
curlコマンドを試してみたのですが、以下のメッセージが返ってきます。

{"messages":["ログインしてください"]}

----------------------------------------------------------------------------

原因は何でしょうか？

**Comment by kamikaze123** [comment]
なんとか出来ました。親切な対応ありがとうございます。
