### ISSUE TITLE
approving_ex_reports　の承認者情報を取得したい

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#70]
### 内容

/api/external/v1/offices/{office_id}/approving_ex_reports
事業所全体の承認待ちリストを返す

これを使うことで、経費申請一覧(管理者)のステータス『全承認待ち』を取り出すことができるのですが、この経費申請の承認者情報を取得する方法はないのでしょうか？

滞留している承認者に督促（メールするなど）をする仕組みを実現できないか考えています。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@skier0922 
こちら返信が遅くなり申し訳ございませんでした。
本件対応致しました（`ex_report_approvals`）のデータとなります。ご確認よろしくおねがいします。
https://expense.moneyforward.com/api/index.html#/ex_report/find_office_approving_ex_reports
