### ISSUE TITLE
支払明細の取得APIについて

### ISSUE THREAD

**Issue by InoueFunai** [moneyforward/expense-api-doc#73]
### 内容
先日issueをあげてすぐクローズし申し訳ありませんでした。

支払明細取得について、確認させていただきたくご質問させてください。
book_at_fromとbook_at_toがありますが、うまく条件がきかない状況です。
取得結果のどの項目に対して条件がきいていますでしょうか？

もしドキュメントがありましたら、申し訳ありません。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@InoueFunai 
ご連絡ありがとうございます。
こちらドキュメントにミスがございました。。
ドキュメント修正しておきますが、以下でお試しください。

`book_date_from`, `book_date_to`

**Comment by InoueFunai** [comment]
@nkuroda @dito
早速のご回答ありがとうございます。
承知いたしました、そちらで確認いたします。

また、swaggerでリターン値を確認したのですが、確認できずご教授頂けると幸いです。
費用計上日は返却値としてありますでしょうか？

**Comment by nkuroda** [comment]
@InoueFunai 
ご連絡の件ですが、残念ながら
費用計上日は返却値に含まれておりません。

![マネーフォワード クラウド経費APIドキュメント](https://user-images.githubusercontent.com/1215551/64674637-375fcf00-d4ac-11e9-95a1-e12300d920dd.png)

**Comment by InoueFunai** [comment]
承知いたしました、今後追加いただけると幸いです。
