### ISSUE TITLE
ex_transaction 3ヶ月以内に絞ったら処理前の伝票が拾えなくなった

### ISSUE THREAD

**Issue by mikomokaru** [moneyforward/expense-api-doc#78]
### 内容
2019-11-26あたりから、未確定の伝票だけ取得するために発行していた
```
/api/external/v1/offices/{office_id}/ex_transactions
```
へのGETが失敗するようになりました。
エラーとしては、「3ヶ月以内の伝票に絞れ」ということだったので、
query_object[recognized_at_from]を today - 3ヶ月に指定したところ、結果が帰ってくるようにはなったですが、まだ日付が入っていない伝票（≒オペレーターさん未着手の伝票）が漏れるようになってしまいました。
日付が入っていない伝票を検索に引っ掛けるパラメータの書き方があれば教えて下さい。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@mikomokaru 
なるほど、、日付が入っていない伝票ですね。こちら業務上必要ということになりますか？
（いずれオペレーター入力の結果等で入力がされるので、その反映まで待つというのは難しいでしょうか？）

**Comment by mikomokaru** [comment]
@nkuroda 
> なるほど、、日付が入っていない伝票ですね。こちら業務上必要ということになりますか？
はい、お金を使う現場向けに、
https://slack-files.com/TB8BUBH9T-FQEKXUXRB-a2e2ff4d57
こういうものを見せていて、最終行が今回の問題に該当するわけですが、これは出したいですね。

お答えからすると現状取る手段がないと思いますので提案ですが
```
recognized_at_to が未定義なら、日付空白の伝票も返してくれる
```
ようにしていただけるとうれしいです。

**Comment by mikomokaru** [comment]
@nkuroda 追記です。
24-365営業者からすると、土日・正月・GWなどあると、空白のままで大分待つことになります。

**Comment by nkuroda** [comment]
@mikomokaru 
なるほど承知しました。日付空を返すフラグをパラメーターに追加したいと思います。
日付の入っている明細とは別に、日付空白を取得頂くために、別途APIを叩いて頂くことになりますが、上記対応でお願いしてもよろしいでしょうか？

**Comment by mikomokaru** [comment]
@nkuroda はい、それでもOKです。
助かります。リリースされたら教えていただけますか？

**Comment by nkuroda** [comment]
@mikomokaru 
リリース完了しましたら、もちろんご連絡差し上げます！

**Comment by mikomokaru** [comment]
@nkuroda 
すいません、再オープンします。
この変更、他にも影響が出てました。（承認済みの伝票を弊社会計に渡す際にも日付範囲なしで取ってた）
幸い対応は簡単で、@nkurodaに特に恨みはありませんが、念の為、他に制約が増えているようでしたら教えてください。

また、APIのリリースは従来までのところ、比較的ステルスっぽく行われていると思いますが、
可能でしたら予告付きリリースへの移行を検討していただければと思います。

**Comment by nkuroda** [comment]
@mikomokaru 
お手数をおかけしております。

> 念の為、他に制約が増えているようでしたら教えてください。

期間指定以外について、現在は特に制約は増やしておりません。

> 可能でしたら予告付きリリースへの移行を検討していただければと思います。

本件でございますが、APIの機械的アクセスによる負荷問題が発生したため、
迅速に投入する必要があったという背景がございました。
使える機能が使えなくなる系の改修については、予告付きのリリースを検討して参ります。
引き続きよろしくおねがいいたします 🙇

**Comment by mikomokaru** [comment]
@nkuroda 
> 本件でございますが、APIの機械的アクセスによる負荷問題が発生したため、
> 迅速に投入する必要があったという背景がございました。

なるほど、そういう事態だったのですね。弊社も結構な原因を作っていると思うので、こちらこそ申し訳ありません。
一部の参照系にキャッシュをかませて、ちょっとでも負荷軽減にご協力させていただきたいと思います。

で、このissueはcloseせずにおこうと思います。
日付空白伝票問題が解決したら閉じていただければと思います。

**Comment by nkuroda** [comment]
@mikomokaru 
ご連絡遅くなりました。日付が空を抽出できるよう対応致しました。
下記APIについて、`is_recognized_at_blank` というパラメーターを追加しております。、
このパラメーターが設定されていれば、日付の期間指定は不要となります。
https://expense.moneyforward.com/api/index.html#/ex_transaction/find_office_ex_transactions

こちらをお試し頂ければと思います。よろしくおねがいいたします。

**Comment by mikomokaru** [comment]
@nkuroda 
早速実装し、性能がもとに戻りました。ありがとうございます。
本体側にも3ヶ月縛りが効いているようですね。
それに関して弊社の経理の声をお伝えしておきます。
```
オペレータさんが年を間違えることがまれにあるので、そういう情報を検出したいときにに3ヶ月縛りはつらい
```
とのことでした。

**Comment by nkuroda** [comment]
@mikomokaru 
ご確認とフィードバックありがとうございます。

> オペレータさんが年を間違えることがまれにあるので、そういう情報を検出したいときにに3ヶ月縛りはつらい

承知しました。こちらについても経費明細番号のレンジ指定だったりを考えたいと思います。
よろしくおねがいいたします。
