### ISSUE TITLE
ワークフロー設定をＡＰＩで取り出せるようになりませんか

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#79]
いつもありがとうございます。

### 内容
人事異動の際にメンバー情報や部門情報などはＡＰＩで取得できますので、人事情報との差異を出して、更新データは作れるのですが、ワークフロー情報は都度手作業でＣＳＶで出力して、そのデータを取り込んで変更分を作成しています。
APIでデータが取得できれば助かります。ご検討ください。

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@skier0922 
ご連絡ありがとうございます。
一点質問なのですが、従業員×申請種類に対してどのワークフローを利用するかの設定についてのAPIでよろしいですか？

（ワークフロー自体のAPI更新についてはデータ構造が複雑で難しい状況です）

**Comment by skier0922** [comment]
お世話になります。

大規模で使用する場合、人でワークフローをアサインするのは、あまり現実的ではなく、実際は所属に基づいてフロー設定をしています。

そのため、『事業所設定』『ワークフロー設定』でできるＣＳＶ出力をイメージしています。
せめてワークフロー、承認設定、分岐ルール　の出力が出来るとよいのですが。

**Comment by nkuroda** [comment]
@skier0922 
APIでワークフロー設定の取得、更新についての要望については、まだ他のユーザーの方から要望を受けたことはなかったりしますので、他の開発がある状況ですので、一旦要望として預からせていただければと思います。ご要望にすぐお応えできず心苦しいですが、何卒よろしくおねがいいたします。

**Comment by skier0922** [comment]
承知しました。

よろしくお願いします。
