### ISSUE TITLE
事業所に所属するメンバーを返す でdeptsの戻り値がNULL

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#80]
### 内容

/api/external/v1/offices/{office_id}/office_members/{id}
事業所に所属するメンバーを返す

を使って人事情報とのチェックを毎朝定期的に実行しておりますが、先週末から『depts：メンバーの所属部門リスト』の戻り値がnullになっています。

何か仕様が変わりましたでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@skier0922 
返信が遅くなり申し訳ございません。別途の経路でご連絡いただき対応したかと思いますが、こちらについては不具合が発生しておりました。大変申し訳ございません。3/12に修正完了しております。
よろしくお願いいたします。
