### ISSUE TITLE
APIから、経費申請書をダウンロードしたい

### ISSUE THREAD

**Issue by DaichiShirakawa** [moneyforward/expense-api-doc#81]
### 内容
MF経費 Webから、
申請一覧 -> (経費申請の詳細) -> (申請書のダウンロードボタン)
の操作で可能な、申請書のpdfダウンロードをAPI経由で行うことはできないでしょうか。

任意の申請の、申請書ファイルのバイナリ、
またはダウンロード可能なURLを返すAPIがあれば嬉しいです。

### 背景
MF クラウド経費を利用しており、
社内の経費申請フローの改善のためにAPIの活用を検討しております。

1. 社員が Slack に領収書画像を添付してメッセージを送る
2. Botが、SlackメールアドレスをもとにMF経費メンバーを特定し、メンバー代理で経費申請を行う
3. 業務フロー上、経費申請書を印刷する必要があるため、MFから申請書ファイルを取得し、Botから社員へファイルをフィードバックする

2の代理申請は、以下2つのAPIを活用することで実現できそうだと考えていますが、
私の認識に誤りがあれば、加えてアドバイスいただけると幸いです。
/api/external/v1/offices/{office_id}/office_members/{office_member_id}/upload_receipt
/api/external/v1/offices/{office_id}/office_members/{office_member_id}/ex_transactions

### 開発通知用
@nkuroda @dito

**Comment by DaichiShirakawa** [comment]
(操作ミスで送信してしまいました。現在修正版を書いています)

**Comment by nkuroda** [comment]
@DaichiShirakawa 

申請書をPDF変換したものを返すAPIの追加は提供検討したいと思います。
（それほど工数かからずできそうなものです）

> 2の代理申請は、以下2つのAPIを活用することで実現できそうだと考えていますが、
> 私の認識に誤りがあれば、加えてアドバイスいただけると幸いです。
> /api/external/v1/offices/{office_id}/office_members/{office_member_id}/upload_receipt
> /api/external/v1/offices/{office_id}/office_members/{office_member_id}/ex_transactions

上記で経費登録は可能ですが（クラウド経費では経費明細とよんでいます）、
その経費明細を月次などでまとめて申請する経費精算を出すことがまだAPIではできません。
こちらも今後検討したいと思っています。

すぐに期待にそえない点もございますが、よろしくお願いいたします。
