### ISSUE TITLE
事業所全体の取得時に400エラーがでる

### ISSUE THREAD

**Issue by hazeleye** [moneyforward/expense-api-doc#82]
### 内容
・GET　/api/external/v1/offices/{office_id}/me/ex_transactions　は正常動作
・GET　/api/external/v1/offices/{office_id}/ex_transactions　で400エラーがでる
・管理者権限のユーザーで実行
・スコープは全てつけてる

純粋に自分の明細取得から事業全体の取得を出す場合はURIの「me」を取るだけで動作すると考えていましたが、何かしら他の条件が必要でしょうか（１つの事業所だけでは動作せず２つ以上必要など）

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@hazeleye 
返信おそくなりすみません。以下2点を確認頂けますでしょうか？
アクセストークンを発行した人のクラウド経費上の権限、またアクセストークンに付与されてあるscope
アクセストークンを発行した人の権限がクラウド経費上で管理権限がないとそのAPIはアクセストークンに付与されているscopeが事業所全体のデータを取得する権限scopeであっても、401か403あたりの結果が返るかと思います。互角にjよろしくおねがい致します。
