### ISSUE TITLE
カスタムの申請フォームを利用した申請データ

### ISSUE THREAD

**Issue by ayamimata** [moneyforward/expense-api-doc#83]
### 内容
カスタムの申請フォームを利用した申請データについての質問です。
申請データはタイトルや承認者情報は取れますが、それ以外のカスタム項目は抽出することはできないのでしょうか？
### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@ayamimata 
現状APIではまだ取得はできないです。
今後実装を検討して参ります。
現状ですと、ウェブの方からCSVエクスポートをお試し頂くということになるかと思います。
よろしくおねがい致します。
