### ISSUE TITLE
部門　負担部門付替先　について

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#85]
### 内容
ＭＦ経費において、部門の階層が設定されたと思いますが、これとあわせて、部門の項目の中に『負担部門付替先』という項目が追加されております。

この項目は、ＡＰＩ上に反映さｒているのでしょうか？ドキュメント上は変わっていないようです。
部門を返す　/api/external/v1/offices/{office_id}/depts/{id}

また、同様に　『ex_transaction　経費明細』において、ＡＰＩ上の対応はされているのでしょうか？

負担部門付替先　をGUIで設定しても、ＡＰＩ側には考慮されていないのでしょうか？

### 開発通知用
@nkuroda @dito

**Comment by nkuroda** [comment]
@skier0922 
お問い合わせありがとうございます。
部門の多階層化のリリースに合わせた、APIの修正はまだ行っていません。
なお、負担部門付替先については、特に指定が無い場合は付替をしないことになっており、
APIで部門登録された場合は、付替が特に行われないとなります。

なお、負担部門付替については、厳密には、負担部門の付替がされるのは、仕訳についてのみ行われるので、経費明細の費用負担部門の置換えはされないようになっております。
（経費明細の費用負担部門を付替えしてしまうと、ワークフローの分岐等に問題が出るため、その付替は行っておりません）

また、部門APIについては修正を6月内には実施したいと考えています。APIの改修が完了しましたら、またご連絡致します。以上よろしくおねがい致します。

**Comment by nkuroda** [comment]
メールをほじり出し連携した

**Comment by nkuroda** [comment]
@skier0922
APIの対応完了しております。 `ex_journal_dept_id` というフィールドが仕訳の負担付替先部門です。
ご確認頂ければと思います。よろしくおねがいします。
https://expense.moneyforward.com/api/index.html#/dept/find_depts
