### ISSUE TITLE
expense_report_unit 経費集計 について

### ISSUE THREAD

**Issue by FS-MF** [moneyforward/expense-api-doc#86]
### 内容
expense_report_units(経費集計のリストを返す)に関するご質問です。
PGMとしては開発中で仕様はAPIドキュメントの通り、という
ステータスでしたら、その旨ご連絡いただけましたら幸いです。

①支払日の絞り込み
支払日の絞り込みができないのですが、以下のクエリ指定であっているでしょうか。
※以下の支払日のクエリ指定あり・なしとも同じレスポンス結果となる
（ex 2020/3/3 ～2020/6/31の支払日データを絞り込む場合、）
https://expense.moneyforward.com/api/external/v1/offices/{office_id}/expense_report_units?payment_date_from=2020-03-03&payment_date_to=2020-06-31

②office_id
応答結果のExpenseReportUnit　office_idについて、従業員idとドキュメント（Modelタブ）に
記述があるのですが、実際のレスポンス値では事業者idが返ってきます、どちらが正しいでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@FS-MF 
ご連絡が遅くなってしまい申し訳ございません。

①支払日の絞り込みについて

パラメーターの指定が正しくないようです。以下のようなリクエストとなります。となります。

```
curl -X GET "https://expense.moneyforward.com/api/external/v1/offices/:office_id/expense_report_units?query_object%5Bpayment_date_from%5D=2020-06-25&query_object%5Bpayment_date_to%5D=2020-06-25" -H "accept: application/json" -H "authorization: Bearer token"
```

https://expense.moneyforward.com/api/index.html#/expense_report_unit 
SwaggerUIを使ってAPIの試し打ちもできますので、上記にて実際にパラメーターを設定してみて、実行してみるのがわかりやすいかもしれません。
![image](https://user-images.githubusercontent.com/1215551/86052938-b3a2bd80-ba92-11ea-877c-eae13dea9e20.png)

**Comment by nkuroda** [comment]
> ②office_id
> 応答結果のExpenseReportUnit　office_idについて、従業員idとドキュメント（Modelタブ）に
> 記述があるのですが、実際のレスポンス値では事業者idが返ってきます、どちらが正しいでしょうか。

実際のレスポンスの事業所idが正しいのでドキュメントを今日中には修正しておきます。
以上よろしくおねがいします。

**Comment by nkuroda** [comment]
@FS-MF 

> ②office_id
> 応答結果のExpenseReportUnit　office_idについて、従業員idとドキュメント（Modelタブ）に
> 記述があるのですが、実際のレスポンス値では事業者idが返ってきます、どちらが正しいでしょうか。

こちらの記載の修正、遅くなりましたが完了しております。
ご報告ありがとうございました。
