### ISSUE TITLE
 /api/external/v2/offices/{office_id}/office_members 事業所に所属するメンバー一覧を返す で仕様通りの値が取得できない

### ISSUE THREAD

**Issue by skier0922** [moneyforward/expense-api-doc#87]
### 内容
office_member　のv2仕様ですが、仕様とResponse結果に相違があるのですが、これはいずれが正しく、修正されるのでしょうか？

取得値に　default_dept　あるが、仕様にはない。
office_member_depts:　の構造がおかしい？
他。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@skier0922 
ご連絡が遅くなってしまい申し訳ございません。
ご指摘の通り、`default_dept` がレスポンスとしては返っていますが、ドキュメントに記載されていませんでした。
こちらの件、本日夕方のリリースでドキュメント更新いたします。
よろしくおねがいします。

**Comment by skier0922** [comment]
よろしくお願いします。

**Comment by nkuroda** [comment]
@skier0922 
APIドキュメントの方を修正しておきました。
ご確認いただければと思います。よろしくおねがいいたします。
