### ISSUE TITLE
APIアプリケーション一覧で登録が６月末に突然消滅している。復旧したい。

### ISSUE THREAD

**Issue by KimihiroOno** [moneyforward/expense-api-doc#89]
### 内容
ZohoCRM 側からMF経費へAPI接続できていたものが、6/26の連携を最後に、6/29以降、下記のエラーが出ており、業務上のトラブルが発生しています。

Error due to - 'Error while generate new authtoken in refreshAccessToken - {"error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.","error":"invalid_grant"}'at lineNumber 247

APIアプリケーション一覧の画面 https://expense.moneyforward.com/oauth/applications では
アプリケーションの登録が無くなっています。

質問１）再登録はしたいと思いますが、もともとあったはずの情報を復旧いただくことは可能でしょうか。
質問２）誰がいつ削除したのか、原因を確認しなければ、今後の再発を防止できません。
　　　　調査していただく事は可能でしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@KimihiroOno 
ご連絡ありがとうございます。
アプリケーションを削除することはユーザー様の操作以外では削除する仕組み自体ありません。
よく頂く問い合わせなのですが、アプリケーションは会社管理になっておらず、
おそらく別のユーザーが管理していたアプリケーションなのではないかと思われます。（同僚の方など）
（クラウド経費にログインしているユーザー様と確認をしているユーザー様が同じかご確認頂ければと思います）

**Comment by KimihiroOno** [comment]
他のユーザーで管理者権限を持っているメンバーでは、ITメンバーはおりません。
「For Developer　API連携（開発者向け）」のリンクを押す可能性が低いのですが、一応確認してみます。
１）削除前（６月２６日以前）の情報は、貴社にはバックアップはあるでしょうか。
２）６月２６日～６月２９日までに、削除した履歴の、ユーザーID、日時やIPアドレスはわかりますでしょうか。
　　障害報告に、再発防止のための施策が無ければ、管理不足として見做されますため、ご協力をお願いしたく。

**Comment by nkuroda** [comment]
@KimihiroOno 
これ以上のやり取りはgithub上では適切ではないような気がしております。
調査上は利用しているapplicaiton_idなどを連携して頂くのが早いと思っておりますので、
ログイン後フォームのフィードバックフォームよりお手数ですが再度お問い合わせ頂けますでしょうか？
よろしくおねがいします。
