### ISSUE TITLE
経費明細に画像を登録する方法について

### ISSUE THREAD

**Issue by dsner** [moneyforward/expense-api-doc#9]
経費明細に画像を登録する方法についてですが
とりあえず以下APIで画像をアップロードし、
追加された経費明細を修正するというような方法を考えてみたのですが
画像アップロードの戻り値のIDが追加された経費明細のIDとは異なるようでしたのでうまく動作しませんでした。

`post /api/external/v1/offices/{office_id}/me/upload_receipt `
`put /api/external/v1/offices/{office_id}/me/ex_transactions/{id} `

どのようにすれば追加した経費に画像を登録する事ができるのか教えていただけると助かります。

以上、よろしくお願いします。

**Comment by nkuroda** [comment]
@dsner 
ご質問ありがとうございます。たしかに現在だとuploadしたファイルのidだけを返しており、経費明細のidを返していないですね。
追加するよう対応致します。よろしくお願いします。

**Comment by dsner** [comment]
追加対応のほうありがとうございます。
また対応後連絡していただけると助かります。

以上、よろしくお願いします。

**Comment by yamashush** [comment]
@nkuroda 
`file id` だけじゃなくて明細 `ex_transaction id ` があると後続処理に繋げやすくなります。
ぜひお願いします 🙏 \

**Comment by nkuroda** [comment]
@yamashush 
こちら対応を進めます

**Comment by nkuroda** [comment]
@yamashush 
こちらもリリース完了しております。ご確認よろしくおねがいします。

@dsner 
大変お待たせして申し訳ございません。
ご確認のほどよろしくおねがいします。

https://expense.moneyforward.com/api/index.html#/ex_transaction/upload_member_receipt

**Comment by yamashush** [comment]
@nkuroda 
ありがとうございます！
経費明細がとれるようになっていました 🎉 🎉 🎉
