### ISSUE TITLE
Office_memberエンドポイントの変更について

### ISSUE THREAD

**Issue by kuwazzy** [moneyforward/expense-api-doc#90]
### 内容

Office_memberのみ、v1のエンドポイントが2021/05に廃止、v2のエンドポイントが公開されていますが、他のエンドポイントについても近日中にv2エンドポイントへの移行の計画がありますでしょうか？ 現時点のタイミングでOffice_memberのみv2に変更するか他のエンドポイントもv2になったタイミングでまとめてv2対応するかの判断材料として情報をいただければと存じます。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@kuwazzy 
ご返信が遅くなってしまい申し訳ございません。
今のところは、`office_member` 以外にv1で提供しているAPIを廃止する予定は立っていません。
ただし、今後もどうしてもデータ構造自体を変えるといった変更があるため、その場合は一定期間後に廃止するAPIが出てくるかと思います。

今回、office_memberに関するAPIをv2エンドポイントにも用意し、v1について廃止予定とさせて頂いたのでは、
office_memberに関係する不可逆なデータ構造が発生したからです。
具体的には、以前は所属部門毎に役職設定ができませんでしたが、こちらが所属部門毎に役職設定できるようになりました。

現在v1の方のAPIでは、若干強引に値を取得することで、何とかAPIレスポンスを返しておりますが、
これをずっと維持するのは厳しいと考えており、一定期間はサポートしつつ、将来破棄のアナウンスをさせていただきました。
以上よろしくお願いいたします。今後ともよろしくお願いいたします。

**Comment by cdata-support** [comment]
@nkuroda 
詳細なご説明ありがとうございます。現在のステータスについて理解できましたのでクローズにてお願いいたします。

**Comment by kuwazzy** [comment]
@nkuroda
詳細なご説明ありがとうございます。現在のステータスについて理解できましたのでクローズにてお願いいたします。
