### ISSUE TITLE
支払先マスタ登録時に指定する勘定科目IDの把握について

### ISSUE THREAD

**Issue by ichika-r** [moneyforward/expense-api-doc#92]
### 内容
弊社システムから支払先情報を支払先マスタを定期連動することを検討しており、

```
POST /api/external/v1/offices/{office_id}/ex_destinations
```

により登録しようと考えておりますが、登録項目(ExDestinationInput)の中にある、

- default_ex_item_id
- default_cr_item_id
- withholding_tax_cr_item_id
- withholding_tax_cr_sub_item_id

の「勘定科目ID」「補助科目ID」を事前にAPI経由で把握する手段はありますでしょうか。

弊社システム側で該当項目に設定すべき「勘定科目コード」は分かるのですが、API 一覧には
勘定科目/補助科目に関する API が見つからず、コードからIDを把握する方法がわかりません。

### 開発通知用
@nkuroda

**Comment by ichika-r** [comment]
@nkuroda こちら、いかがでしょうか。

**Comment by nkuroda** [comment]
@ichika-r おまたせして申し訳ございません。今日中にご回答いたします。

**Comment by nkuroda** [comment]
@ichika-r
ご質問ありがとうございます。

> 「勘定科目ID」「補助科目ID」を事前にAPI経由で把握する手段はありますでしょうか。

現在、弊社システムの課題なのですが、勘定科目、補助科目については、マネーフォワードクラウド会計に依存しているという状況になっています。
現在、クラウド経費側自身で勘定科目、補助科目を持つようにサービスの開発を進めようとしているところです。
（クラウド会計と同期するような機構も同時に作ります）
このような状況のため、現在、勘定科目、補助科目を取得するAPIがクラウド経費で提供できておりませんが、
クラウド経費独自で勘定科目、補助科目を持つようになった場合には、すみやかにAPIの方も準備したいと考えております。

現在はおまたせすることになってしまい申し訳ございませんが、よろしくお願いいたします。

**Comment by ichika-r** [comment]
ありがとうございます。承知いたしました。
ご検討よろしくお願いいたします。
