### ISSUE TITLE
支払集計に含まれる支払明細リストの取得

### ISSUE THREAD

**Issue by ichika-r** [moneyforward/expense-api-doc#93]
### 内容

支払依頼において集計に紐づく支払明細を取得する手段はありますでしょうか。

経費精算の場合は、

```
GET /api/external/v1/offices/{office_id}/expense_report_units
```

にて集計情報を取得した後に、

```
GET /api/external/v1/offices/{office_id}/ex_report_units/{ex_report_unit_id}/ex_transactions
```

にて対応する申請、明細情報が取得できるのですが、支払依頼の場合は上記、前者に当たる API はあるものの、
後者に当たる API を見つけることができませんでした。

又、仮に支払依頼において後者に当たる API が存在しない場合、

```
GET /api/external/v1/offices/{office_id}/ex_invoice_transactions
```

にて取得した明細データを用いて、別 API との組み合わせにて、対応する「支払日」を取得する方法はありますでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@ichika-r 
返信おそくなってしまいまし大変申し訳ございません。
支払集計に紐づく、支払明細を取得するAPIについて作成いたします。
おそらくエンドポイントは以下になると思います。

`GET /api/external/v1/offices/{office_id}/invoice_report_units/{id}/ex_invoice_transactions`

APIが完成したらご連絡いたします。

> GET /api/external/v1/offices/{office_id}/ex_invoice_transactions
> にて取得した明細データを用いて、別 API との組み合わせにて、対応する「支払日」を取得する方法はありますでしょうか。

現在は、難しそうでしたので、`ex_invoice_transaction` の戻りの中に `invoice_report_unit` も含めるように検討したいと思います。経費明細は既にそのようになっているので支払明細もそれに合わせるようなイメージです。
こちらも対応進めますので完了しましたらご連絡差し上げます。
よろしくお願いいたします。

**Comment by ichika-r** [comment]
@nkuroda ありがとうございます。大変助かります。
お手数おおかけしますがよろしくお願いいたします。

**Comment by nkuroda** [comment]
@ichika-r 
ご連絡が遅くなりましてすみません。本件の対応完了しております。
よろしくおねがいいたします。
https://payable.moneyforward.com/api/index#/invoice_report_unit/find_invoice_report_unit_invoice_transactions

**Comment by ichika-r** [comment]
@nkuroda 追加いただきありがとうございます。活用させていただきます。
