### ISSUE TITLE
モバイルSuica、PASMOの履歴取得

### ISSUE THREAD

**Issue by Hirai0329** [moneyforward/expense-api-doc#94]
### 内容
私自身のスマホにインストールされている
モバイルSuicaの履歴（利用月日、種別、利用駅、残額）取得をして
自信で作ったアプリ連携したいと考えていますが、どのようにしたら可能になりますでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@Hirai0329 
お問い合わせありがとうございます。
現在のところモバイルSuicaなど、当社側がデータ連携で取得した履歴データについて提供するAPIはございません。
また、今後においてもクラウド経費でAPI提供する予定はございません。

引き続きよろしくおねがいいたします。

**Comment by Hirai0329** [comment]
ありがとうございます。
提供はされていないのですね。承知いたしました。
