### ISSUE TITLE
プロジェクトの登録・更新にて404エラー

### ISSUE THREAD

**Issue by y-takeda0** [moneyforward/expense-api-doc#95]
### 内容
いつもお世話になっております。
プロジェクトの登録・更新が上手くできず確認させて下さい。

プロジェクトの登録・更新を弊社システムで行うにあたり、APIドキュメント上のTry it outより動作の確認を
行ったところ404 エラー 「処理対象のレコードが存在しません」といったメッセージが返されました。

idはプロジェクト一覧にて取得したidを指定しており、project_codeにはデフォルトのパラメータで実行を行っております。

お手数ですがこちらご確認頂けないでしょうか。

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@y-takeda0 
404エラーが登録・更新で発生しているということになるようなので、
office_id パラメーターが適切ではないか、

> project_codeにはデフォルトのパラメータで実行を行っております。

body の パラメーターで、 parent_id が 'string' という文字列のままになっているのが、実在しないidであるため発生しているのではないかと思います。

私が手元でやったところ問題なく更新されました。
![image](https://user-images.githubusercontent.com/1215551/98497807-7ba15780-2288-11eb-879f-a0d927299872.png)
