### ISSUE TITLE
GASでアプリを作る際のRedirect URLについて

### ISSUE THREAD

**Issue by shugo1107** [moneyforward/expense-api-doc#96]
### 内容
お世話になっております。
GASを使ってOAuth認証を用いたアプリケーションを作ろうとしております。中身はこちらのMF請求書向けのブログ(https://tonari-it.com/gas-moneyforward-invoice-api-authorize/)とほぼ同じ内容で作っております。
ところが、MF経費側のアプリケーションを作成の画面で入力したRedirect URLに戻ってきてほしい場面で、「Redirect URIが不正です。」というエラーメッセージが発生し、GASに戻ることができずアクセストークンの取得ができません。どのような原因が考えられるでしょうかご教授いただけないでしょうか？
よろしくお願いいたします。
![MF経費エラー画面](https://user-images.githubusercontent.com/46769255/98620009-c33ae880-2347-11eb-80eb-3af41ede0389.png)

### 開発通知用
@nkuroda

**Comment by nkuroda** [comment]
@shugo1107 
エラーの発生箇所は認可コードの取得のタイミングになりますでしょうか？（`code` というパラメーターの取得まで至っていない状況となりますか？）

アプリケーション登録時に設定した `redirect_uri` と認可コード取得のリクエスト時にパラメーターで設定する、`redirect_uri` に相違がないことを確認して頂ければと思います。

**Comment by shugo1107** [comment]
> アプリケーション登録時に設定した redirect_uri と認可コード取得のリクエスト時にパラメーターで設定する、redirect_uri に相違がないことを確認して頂ければと思います。

こちらが原因で無事にredirectできました。ご指摘ありがとうございました。
