### ISSUE TITLE
update_office_ex_transaction のドキュメント不整合

### ISSUE THREAD

**Issue by yamashush** [moneyforward/expense-api-doc#97]
### 内容

`office_member_id` が API パスには含まれていないですが、パラメータにはパスにあると記載されているのでドキュメントがおかしいかも？ 🦆 

https://expense.moneyforward.com/api/index.html#/ex_transaction/update_office_ex_transaction

![image](https://user-images.githubusercontent.com/38120991/98784967-3a9f7380-243f-11eb-9c42-a756669aa2cd.png)

### 開発通知用

@nkuroda

**Comment by nkuroda** [comment]
@yamashush 
ご指摘の通り不要なパラメーターでした。ドキュメントを修正しておきます。

**Comment by yamashush** [comment]
やったー、ありがとうございます！ 🎉 🎉 🎉

**Comment by nkuroda** [comment]
@yamashush 
こちらもリリース完了しております。ご確認よろしくおねがいします。

**Comment by yamashush** [comment]
@nkuroda 直ってました！ありがとうございます！！
