### ISSUE TITLE
経費明細追加の API で領収書をアップロードすると OCR がかからない

### ISSUE THREAD

**Issue by yamashush** [moneyforward/expense-api-doc#98]
### 内容

https://expense.moneyforward.com/api/index.html#/ex_transaction/create_ex_transaction

領収書のアップロードは問題なくできるのですが `"process_type": "2"` にしても OCR が機能しないようです 😭 

```
        "ex_transaction": {
          "remark": "hogehoge",
          "recognized_at": "2020-11-12",
          "value": 100,
          "memo": "memo",
          "ex_item_id": "hogehoge",
          "receipt_input": {
            "content": Base64.strict_encode64(File.read("./tmp/hoge.jpg")),
            "content_type": "image/jpeg",
            "filename": "hoge.jpg",
            "process_type": "2",
          },
        },
```

`receipt_input` を↑と同じにして領収書単体でアップロードした場合は OCR がかかるのは確認しています。
https://expense.moneyforward.com/api/index.html#/ex_transaction/upload_member_receipt

### 開発通知用

@nkuroda

**Comment by nkuroda** [comment]
@yamashush 
ご連絡ありがとうございます。すみません。該当APIでは`"process_type": "2"` や `"process_type": "1"` については現状動作しないため、ドキュメントを修正します。`upload_receipt` のapiの方でのみそのパラメーターは有効でした。

**Comment by yamashush** [comment]
> upload_receipt のapiの方でのみそのパラメーターは有効でした。

なるほどですね、ありがとうございます！

@nkuroda 
領収書（OCR）をアップロードして、その明細 id を取得したい場合ってどうするのがよきでしょうか？
#9 がご対応いただけると解決する問題ではあるのですが、現状だとファイルをアップロードした後に明細を検索して my_file -> id で合致するものを探すしか思いつかなく 🙏 

https://expense.moneyforward.com/api/index.html#/ex_transaction/find_office_ex_transactions

**Comment by nkuroda** [comment]
@yamashush 

おっしゃるとおり現在ファイルのidだけ返しても経費明細をたどるAPIが存在しないため、
#9 の方の対応を進めます。本日中におそらくリリース出来ると思うので、併せてご連絡致します。

**Comment by nkuroda** [comment]
@yamashush 
こちらもリリース完了しております。ご確認よろしくおねがいします。

**Comment by yamashush** [comment]
ありがとうございます！
経費明細がとれるようになっていました 🎉 🎉 🎉
