### ISSUE TITLE
事業者の経費明細を追加 API だと領収書がアップロードされない

### ISSUE THREAD

**Issue by yamashush** [moneyforward/expense-api-doc#99]
### 内容

https://expense.moneyforward.com/api/index.html#/ex_transaction/create_office_ex_transaction

領収書の画像データがアップロードされず、明細だけが作成されます。
リクエスト内容は #98 と同じなので `receipt_input ` の内容が間違っているとは考えられず…。

### 開発通知用

@nkuroda

**Comment by nkuroda** [comment]
@yamashush 
こちらご指摘のとおりでした。
11/12中に修正リリーつ対応致します。

**Comment by yamashush** [comment]
わーい、ありがとうございます！！ 🎉 🎉 🎉

**Comment by nkuroda** [comment]
@yamashush 
リリース完了しております。ご確認頂ければと思います。

**Comment by yamashush** [comment]
@nkuroda ありがとうございます 🎉 🎉 🎉
